### ISSUE TITLE
additional-files on the aws-lambda-tools-defaults.json file

### ISSUE THREAD

**Issue by tarik-ayoub** [aws/aws-extensions-for-dotnet-cli#100]
Hi,
Is the additional-files option still supported on  aws-lambda-tools-defaults.json file? I have been trying to use it to solve a problem with dependency issues (libdl.so) but it apparently has no effect.

I went through some of the source code (as suggested here https://github.com/aws/aws-extensions-for-dotnet-cli/issues/54#issuecomment-456146241) and could not find references to it.

Thanks :)

**Comment by normj** [comment]
Support for `additional-files` still exists in the tool. You can find the code here https://github.com/aws/aws-extensions-for-dotnet-cli/blob/master/src/Amazon.Lambda.Tools/LambdaDotNetCLIWrapper.cs#L327

**Comment by tarik-ayoub** [comment]
Ok, thank you very much :)
