### ISSUE TITLE
deploy-serverless is packaging files from the wrong location

### ISSUE THREAD

**Issue by madmox** [aws/aws-extensions-for-dotnet-cli#103]
I would like to store my templates outside of the .NET solution folder, but can't find a way to do that.

When using `dotnet lambda deploy-serverless --template "C:/foo/template.yaml" --project-location "C:/bar/Project.Web"`, the command deploys a zip containing the files in `C:/foo` (i.e. the deployment template).

Is this an expected behavior?

**Comment by mschweitzer-sd** [comment]
dotnet lambda package-ci suffers from this same problem, and it was pretty maddening last year trying to narrow it down!

**Comment by madmox** [comment]
OK, I found a workaround after a bit of fiddling. Instead of using a single `deploy-serverless` command, use the following:

```powershell
dotnet lambda package `
    --project-location "$ProjectLocation" `
    --configuration "Release" `
    --framework "netcoreapp2.1" `
    --output-package "$PackageFilePath"

dotnet lambda deploy-serverless `
    --package "$PackageFilePath" `
    --profile "$AwsProfile" `
    --region $AwsRegion `
    --s3-bucket "$S3Bucket" `
    --s3-prefix "$S3Prefix" `
    --stack-name $StackName `
    --template "$TemplateFilePath" `
    --template-parameters $TemplateParameters
```

**Comment by klaytaybai** [comment]
Thanks for the feedback

**Comment by normj** [comment]
You can actually have the template outside of the project directory. In the `serverless.template` set the **S3Key** for AWS::Lambda::Function or **CodeUri** for AWS::Serverless::Function to the relative location of the project folder. It is how you can also use the `deploy-serverless` command to deploy multiple projects at the same time. This blog post has more information. https://aws.amazon.com/blogs/developer/aws-serverless-applications-with-multiple-net-core-projects/

**Comment by madmox** [comment]
Nice to know. It seems to work when using the `CodeUri` template property instead of the `--project-location` command option with both `package-ci` and `deploy-serverless` commands.

That said, I don't get the point of the `--project-location` command option, though. Intuitively it looks like the option should override the `CodeUri` for functions where it is left empty, but it doesn't. They still use the template's directory (when `CodeUri` is empty or undefined).

In addition, specifying `CodeUri` in the `Globals` section to a project relative path does not seem to work, even though the [SAM spec](https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst#supported-resources-and-properties) says the `Globals` section supports `CodeUri`. I double checked that I did not override the value in the functions. So you have to explicitly set the `CodeUri` on each function node, even if they all share the same project.

**Comment by ashishdhingra** [comment]
Hi @madmox,

Please confirm if this still an issue or if it could be closed.

Thanks,
Ashish

**Comment by madmox** [comment]
Don't know if the issues are still present, we are using the 2-steps deployment workaround mentioned in [this post](#issuecomment-583428076) now.
