### ISSUE TITLE
Is it possible to use Lambda Layers with references to .dll files?

### ISSUE THREAD

**Issue by SSkupien** [aws/aws-extensions-for-dotnet-cli#109]
Hi, I would like to create a Layer with custom libraries (.dll). Is it possible?
From my research, I found out that layers for .NET lambda works with NuGet references.

Details:
I want to deploy many Lambda functions that all of them would use the same model/methods that I have implemented in my .dll library. I would like to create a layer with that .dll so I won't need to have this library in every lambda .zip.
I know that I can create NuGet from my library and that way create a layer and have it working but this way each time I would like to upgrade version of my library it will require an update for all of lambda's even when having backward compatibility in .dll. All because of the specific version reference in lambda for NuGet.
If it will be possible to have reference to .dll in the layer then I would be able to update .dll library and then update Lambda's one by one when I would like to.

**Comment by klaytaybai** [comment]
More info on https://github.com/aws/aws-lambda-dotnet/issues/599

**Comment by sohail-sf** [comment]
But I have written a blog regarding publishing custom DLL's on lambda layer if it is very essential for some one
https://medium.com/@sohail-dev/publish-custom-dlls-to-aws-lambda-layer-e4ac37a59b85
