### ISSUE TITLE
Can the lambda package command accept runtime parameter which is supported by dotnet publish

### ISSUE THREAD

**Issue by vikasgarghb** [aws/aws-extensions-for-dotnet-cli#110]
Is there a way to pass in the `--runtime` parameter to `dotnet lambda package` command? The `--runtime` parameter is supported by `dotnet publish`.

**Comment by klaytaybai** [comment]
I think this needs work to avoid conflict with things like custom, unsupported runtimes.

**Comment by normj** [comment]
Since `dotnet lambda package` already sets the the `--runtime` for the underlying `dotnet publish` command is there a reason you want to override the behavior of the tool?

**Comment by vikasgarghb** [comment]
Yes. By default it is setting that to `rhel-XXX`. And there is no way we can change it to use a different runtime, for eg. `linux-x64`.

**Comment by normj** [comment]
I was just starting on the work to change the default RID to `linux-x64` for the upcoming .NET Core 3.1 support. While I'm doing that work I'll have the tool not set the RID if it finds the RID is being set via the `--msbuild-parameters` switch.

**Comment by bjorg** [comment]
As far as I can tell from the code, this should be fixed now, correct?

**Comment by ashishdhingra** [comment]
Hi @vikasgarghb,

Good afternoon.

I was going through backlog and came across this issue. Could you please verify if this is fixed in the latest version?

Thanks,
Ashish
