### ISSUE TITLE
Mistyped option doesn't trigger an error

### ISSUE THREAD

**Issue by bjorg** [aws/aws-extensions-for-dotnet-cli#115]
It would be nice, if `dotnet lambda` would error out when it encounters an unrecognized command line option.

For example, `dotnet lambda package --foobar` works just fine. Instead, the tool should say that `--foobar` is not supported.

**Comment by klaytaybai** [comment]
Thanks for the feedback

**Comment by klaytaybai** [comment]
Closing as a duplicate of https://github.com/aws/aws-extensions-for-dotnet-cli/issues/52
