### ISSUE TITLE
`~/.aws/config` not respected, config read only from `~/aws/credentials`

### ISSUE THREAD

**Issue by hauntingEcho** [aws/aws-extensions-for-dotnet-cli#117]
After running `aws configure` and setting your region to `us-east-2`, it will be put in `~/.aws/config` and will be returned by `aws configure get region`.  However, when attempting to run `dotnet.exe lambda package-ci --output-template compiled.template` from a folder whose `aws-lambda-tools-defaults.json` does not have a region set, you will still get the error message `Missing required parameter: --region`.

This can be worked around by adding `region=us-east-2` to the bottom of your `~/.aws/credentials` file.

**Comment by ashishdhingra** [comment]
Hi @hauntingEcho, 

Thanks for reporting the issue. I have validated that .NET CLI Lambda package-ci does not take region from ~/.aws/config if this parameter is not specified as part of command. I will have a developer look at this for further investigation.

Thanks,
Ashish

**Comment by normj** [comment]
Looks like this was a bug in the SDK that was fixed back in fall 2019 but the version of the SDK used by Amazon.Lambda.Tools hasn't been updated in quite awhile. I'm working on updating Amazon.Lambda.Tools to the latest version of the SDK which should fix the problem.

**Comment by hunanniu** [comment]
This issue should have been addressed
