### ISSUE TITLE
package-ci does not respect AWS_DEFAULT_REGION environment variable

### ISSUE THREAD

**Issue by hauntingEcho** [aws/aws-extensions-for-dotnet-cli#118]
## To reproduce:
1. add `region=us-east-2` to your profile in `~/.aws/credentials` ( #117 )
1. create a new bucket named `test-example` in us-west-2
1. go to the folder of an existing dotnet serverless application
1. run the command `AWS_DEFAULT_REGION=us-west-2 dotnet.exe lambda package-ci --output-template compiled.template -sb test-example` in git-bash on windows

you will receive the output:
```
Amazon Lambda Tools for .NET Core applications (3.3.1)
Project Home: https://github.com/aws/aws-extensions-for-dotnet-cli, https://github.com/aws/aws-lambda-dotnet

Error: S3 bucket must be in the same region as the configured region us-east-2. test-example is in the region us-west-2.
```

## expected behavior
success, as "If you specify an option by using one of the environment variables described in this topic, it overrides any value loaded from a profile in the configuration file." - https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html

**Comment by ashishdhingra** [comment]
Hi @hauntingEcho, 

Good morning.

Looking at the example above, looks like you are using .NET CLI. However, the documentation at https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html is for the AWS CLI. All AWS CLI commands have the [Command structure](https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-commandstructure.html) as below:

```
aws <command> <subcommand> [options and parameters]
```

Please let me know if you are facing the issue using the AWS CLI (not the .NET CLI) or if we could close this issue.

Thanks,
Ashish

**Comment by hauntingEcho** [comment]
Hi @ashishdhingra - this ticket is for the fact that the AWS dotnet CLI extensions do not respect the same environment configuration used by other AWS CLI products and libraries, which would greatly simplify some deployment tasks.  Is there currently any documentation on which environment variables which are supported by the dotnet extensions?

**Comment by ashishdhingra** [comment]
Hi @hauntingEcho, 

Thanks for your inputs. I do see that the behavior is not the same as AWS CLI. I will check with the development team for any documentation, if this is by design (since nothing is specified in Readme) or if this could be fixed in future releases. Also, we need to check the behavior in other SDKs (like for Java) and if its the same as AWS CLI. I will keep you posted on any updates.

Thanks,
Ashish

**Comment by hauntingEcho** [comment]
that makes sense!  From local testing, it does look like AWS_REGION is supported by boto3 as well (just not documented).  I've opened a separate ticket with them.
