### ISSUE TITLE
Deploy serverless ignore "profile-location"

### ISSUE THREAD

**Issue by DoMore87** [aws/aws-extensions-for-dotnet-cli#12]
According to the help for command deploy-serverless you can set
--profile-location 
Optional override to the search location for Profiles, points at a shared credentials file

I tried to set this option both in config file and as a command line option but the command seems to ignore it. 

Am I missing something?

**Comment by jbright** [comment]
Can you include the full command that you're using? I use `--profile-location` as part of [our deployment process](https://codingtradeoffs.com/2018/01/27/new-year-new-technology/) with no issues.

**Comment by DoMore87** [comment]
I tried:
dotnet lambda deploy-serverless --profile-location {pathToFile}

and also tried adding:

"profile":"serverless",
_"profile-location":**{pathToFile}**,_
"region" : "eu-west-1",

in aws-lambda-tools-defaults.json file.

The file I use for credentials sholud be ok, because as soon as I put it in the default folder "%UserProfile%\.aws" the above command (without --profile-location) worked perfectly.

I see in your blog post that you use this parameter for the command _deploy-function_, I am trying to use it for _deploy-serverless_. have you verified that it works also with this command?

**Comment by normj** [comment]
Are you passing in the path to the directory or including the file name as part of the profile location? This is relying on code from the .NET AWS sdk and off the top of my head I believe it requires the full path which includes the file name in it.

**Comment by normj** [comment]
Closed for lack of activity
