### ISSUE TITLE
--msbuild-parameters not working for dotnet lambda package-ci

### ISSUE THREAD

**Issue by simon10says** [aws/aws-extensions-for-dotnet-cli#122]
I've posted my issue at https://github.com/aws/aws-lambda-dotnet/issues/663#issue-613388019 which should be more appropriate here.

**Comment by simon10says** [comment]
Hi @normj , I'm wondering if you have a chance to look at this issue yet?

**Comment by chrisoverzero** [comment]
I am also running into this problem. The reason it's not working is from this code in the Template Processor Manager:

```csharp
// If the project is in the same directory as the CloudFormation template then use any parameters
// there were specified on the command to build the project.
if (IsCurrentDirectory(field.GetLocalPath()))
{
    if (!string.IsNullOrEmpty(this.DefaultOptions.TargetFramework))
        command.TargetFramework = this.DefaultOptions.TargetFramework;
    
    command.Configuration = this.DefaultOptions.Configuration;
    command.DisableVersionCheck = this.DefaultOptions.DisableVersionCheck;
    command.MSBuildParameters = this.DefaultOptions.MSBuildParameters;
}
```

I could easily open an MR to move `command.MSBuildParameters = this.DefaultOptions.MSBuildParameters;` outside of the `if` block, but I'm reluctant to do so because I don't know why it's there. (I don't know what problem this check avoids.) I expect it's an oversight, since the MSBuild parameters are specified as allowed parameters to the `package-ci` command and they're threaded through it in a way that looks intentional. It's only here that there's a mismatch.

**Comment by chrisoverzero** [comment]
Now that I've looked into it more, I'm not sure at all of the benefit of this check. `PackageDotnetProjectAsync` is only called from `ProcessUpdatableResourceAsync`, which is only called from `TransformTemplateAsync`. That's called from `DeployServerlessCommand` and `PackageCICommand`, which correspond to the commands `deploy-serverless` and `package-ci`. Both of these commands are or can be called from the root directory (next to the solution file) and walk the template's defined Functions to their corresponding project files. I'm not at all sure that this is the desired behavior.

An MR can't hurt, so I'll make one as a proposal.

**Comment by simon10says** [comment]
Exploring the MR from @chrisoverzero, I've found a rather quick workaround:

1. Add a `aws-lambda-tools-defaults.json` file in the project folder
2. In the json file, add:
```json
{
  "configuration": "Release",
  "msbuild-parameters": "/p:Configuration=Release /p:PublishReadyToRun=true /p:TieredCompilation=false /p:TieredCompilationQuickJit=false --self-contained false"
}
```

`package-ci` command will then be able to pick up the `msbuild-parameters` from the json file.

I've tested it and it works.

**Comment by arturomonge** [comment]
@simon10says Thanks. I tried it, but it didn't work for me. I added the line to `aws-lambda-tools-defaults.json` but I still get the build without the msbuild parameters, as I did when using the command line parameter:

```
[Container] 2020/09/08 17:19:47 Running command dotnet lambda deploy-serverless
--
142 | Amazon Lambda Tools for .NET Core applications (4.1.0)
143 | Project Home: https://github.com/aws/aws-extensions-for-dotnet-cli, https://github.com/aws/aws-lambda-dotnet
144 |  
145 | Processing CloudFormation resource LambdaApiFunction
146 | Initiate packaging of ./test-project for resource LambdaApiFunction
147 | Executing publish command
148 | ... invoking 'dotnet publish', working folder '/codebuild/output/src916057038/src/./test-project/bin/Release/netcoreapp3.1/publish'
149 | ... dotnet publish --output "/codebuild/output/src916057038/src/./test-project/bin/Release/netcoreapp3.1/publish" --configuration "Release" --framework "netcoreapp3.1" /p:GenerateRuntimeConfigurationFiles=true --runtime linux-x64 --self-contained false
```

In my case, the serverless.template is in the root of the solution, not in the project's folder, which is what causes the problem: 

```csharp
// If the project is in the same directory as the CloudFormation template then use any parameters
// there were specified on the command to build the project.
if (IsCurrentDirectory(field.GetLocalPath()))
{
    if (!string.IsNullOrEmpty(this.DefaultOptions.TargetFramework))
        command.TargetFramework = this.DefaultOptions.TargetFramework;
    
    command.Configuration = this.DefaultOptions.Configuration;
    command.DisableVersionCheck = this.DefaultOptions.DisableVersionCheck;
    command.MSBuildParameters = this.DefaultOptions.MSBuildParameters;
}
```

This is what @chrisoverzero's pull request is fixing: that msbuild parameters are not ignored if the Cloudformation template is not in the same folder as the project.

**Comment by arturomonge** [comment]
@simon10says Nevermind my last message... it works! Nice! Thank you! I omitted the bit where you suggested to create a new `aws-lambda-tools-defaults.json` in the **project's folder** and I simply added the line to my existing root `aws-lambda-tools-defaults.json` file. After creating the new file in the project's folder, the parameters are now passed to the `dotnet publish` command.

Thanks again!

**Comment by ashishdhingra** [comment]
Hi @simon10says,

Good afternoon.

I was going through the backlog and came across this issue. The `--msbuild-parameters` could be ignored due to the check mentioned at the code [TemplateProcessorManager.cs](https://github.com/aws/aws-extensions-for-dotnet-cli/blob/a24f8a887530b4fadfe346b3e364929a6c407c07/src/Amazon.Lambda.Tools/TemplateProcessor/TemplateProcessorManager.cs#L230). It checks if the project is in the same directory as the CloudFormation template; if yes, then it uses any parameters there were specified on the command to build the project. I'm not sure the reason behind this, may be it has to do something with the `dotnet publish` requirement.

I do notice that your solution contains `serverless.yml` template outside (one level up) of the project directory. I copied the template to project directory and the `--msbuild-parameters` are correctly handled.
**serverless.yml**
```YML
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  TestFunction3:
    Type: AWS::Serverless::Function
    Properties:
        Runtime: dotnetcore3.1
        FunctionName: "TestFunction3"
        Handler: AWSServerless2::AWSServerless2.Function::TestFunction3
        CodeUri: '.'
        MemorySize: 128
        Role: null
        Policies:
        - AWSLambdaBasicExecutionRole
        Timeout: 30
```
**package-ci command**
```
dotnet lambda package-ci --project-location . --configuration Release --profile default ` --region us-east-2 --s3-bucket test-bucket-1a1a --template ./serverless.yml --output-template  ./serverless-output.yml --msbuild-parameters -p:Version=6.6.6
```
**Output of package-ci command**
```
Amazon Lambda Tools for .NET Core applications (4.3.0)
Project Home: https://github.com/aws/aws-extensions-for-dotnet-cli, https://github.com/aws/aws-lambda-dotnet
	
Processing CloudFormation resource TestFunction3
Initiate packaging of . for resource TestFunction3
Executing publish command
Deleted previous publish folder
... invoking 'dotnet publish', working folder '/Users/username/Downloads/AWSServerless1/AWSServerless2/./././bin/Release/netcoreapp3.1/publish'
... dotnet publish --output "/Users/username/Downloads/AWSServerless1/AWSServerless2/./././bin/Release/netcoreapp3.1/publish" --configuration "Release" --framework "netcoreapp3.1" -p:Version=6.6.6 /p:GenerateRuntimeConfigurationFiles=true --runtime linux-x64 --self-contained false 
... publish: Microsoft (R) Build Engine version 16.7.0+7fb82e5b2 for .NET
... publish: Copyright (C) Microsoft Corporation. All rights reserved.
... publish:   Determining projects to restore...
... publish:   Restored /Users/username/Downloads/AWSServerless1/AWSServerless2/AWSServerless2.csproj (in 272 ms).
... publish:   AWSServerless2 -> /Users/username/Downloads/AWSServerless1/AWSServerless2/bin/Release/netcoreapp3.1/linux-x64/AWSServerless2.dll
... publish:   AWSServerless2 -> /Users/username/Downloads/AWSServerless1/AWSServerless2/bin/Release/netcoreapp3.1/publish/
Changed permissions on published file (chmod +rx AWSServerless2.pdb).
Changed permissions on published file (chmod +rx Amazon.Lambda.Serialization.SystemTextJson.dll).
Changed permissions on published file (chmod +rx AWSServerless2.runtimeconfig.json).
Changed permissions on published file (chmod +rx Amazon.Lambda.Core.dll).
Changed permissions on published file (chmod +rx AWSServerless2.dll).
Changed permissions on published file (chmod +rx AWSServerless2.deps.json).
Zipping publish folder /Users/username/Downloads/AWSServerless1/AWSServerless2/./././bin/Release/netcoreapp3.1/publish to /var/folders/5v/klr4lq9j0rd95h4xtmydvgrwqf_g0k/T/TestFunction3-CodeUri-637388810765026120.zip
... zipping:   adding: AWSServerless2.pdb (deflated 41%)
... zipping:   adding: Amazon.Lambda.Serialization.SystemTextJson.dll (deflated 47%)
... zipping:   adding: AWSServerless2.runtimeconfig.json (deflated 23%)
... zipping:   adding: Amazon.Lambda.Core.dll (deflated 46%)
... zipping:   adding: AWSServerless2.dll (deflated 56%)
... zipping:   adding: AWSServerless2.deps.json (deflated 67%)
Created publish archive (/var/folders/5v/klr4lq9j0rd95h4xtmydvgrwqf_g0k/T/TestFunction3-CodeUri-637388810765026120.zip).
Lambda project successfully packaged: /var/folders/5v/klr4lq9j0rd95h4xtmydvgrwqf_g0k/T/TestFunction3-CodeUri-637388810765026120.zip
Uploading to S3. (Bucket: test-bucket-1a1a Key: TestFunction3-CodeUri-637388810765026120-637388810801191520.zip)
... Progress: 100%
Writing updated template: ./serverless-output.yml
```

Looks like the `--msbuild-parameters` (or any other command line parameters) are ignored if any of the projects are outside of the current `serverless.yml` directory.

Please let me know if this provides required explanation and if this issue could be closed.

Thanks,
Ashish

**Comment by chrisoverzero** [comment]
>I do notice that your solution contains serverless.yml template outside (one level up) of the project directory. I copied the template to project directory and the --msbuild-parameters are correctly handled.

This doesn’t appear to be viable for solutions containing multiple projects. As described by normj on the associated PR:

>These commands [`package-ci` and `deploy-serverless`] support deploying multiple projects at the same time through CloudFormation.

**Comment by ashishdhingra** [comment]
Thanks @chrisoverzero for your comment. I do understand your concern. I will discuss this with developer.

**Comment by simon10says** [comment]
@ashishdhingra , as @chrisoverzero has commented, your suggestion is not viable for solutions containing multiple projects. 

My enclosed sample is for multiple projects which is why the `serverless.yml` is outside of the project's folder

**Comment by vickramravichandran** [comment]
The issue is that the original command line arguments are not passed to the command objects that are created internally. For example, `deploy-serverless` passes null/empty for the `args` constructor parameter when it instantiates `PackageCommand` (package-ci) or `PushDockerImageCommand` (push-image). See relevant code below. I have submitted a PR https://github.com/aws/aws-extensions-for-dotnet-cli/pull/152

TemplateProcessorManager.cs#L234
```
private async Task<UpdateResourceResults> PackageDotnetProjectAsync(IUpdateResourceField field, string location)
{
    if (field.Resource.UploadType == CodeUploadType.Zip)
    {
        var command = new Commands.PackageCommand(this.Logger, location, null);
```

TemplateProcessorManager.cs#L281
```
else if (field.Resource.UploadType == CodeUploadType.Image)
{
    this.Logger.WriteLine($"Building Docker image for {location}");
    var pushCommand = new PushDockerImageCommand(Logger, location, new string[0]);
```

**Comment by normj** [comment]
The PR for this was shipped as part of [Amazon.Lambda.Tools 5.0.2](https://www.nuget.org/packages/Amazon.Lambda.Tools/5.0.2).

**Comment by paul-michalik** [comment]
> Exploring the MR from @chrisoverzero, I've found a rather quick workaround:
> 
> 1. Add a `aws-lambda-tools-defaults.json` file in the project folder
> 2. In the json file, add:
> 
> ```json
> {
>   "configuration": "Release",
>   "msbuild-parameters": "/p:Configuration=Release /p:PublishReadyToRun=true /p:TieredCompilation=false /p:TieredCompilationQuickJit=false --self-contained false"
> }
> ```
> 
> `package-ci` command will then be able to pick up the `msbuild-parameters` from the json file.
> 
> I've tested it and it works.

It dies not work, if you are using `sam`
