### ISSUE TITLE
Publish-Layer fails to add a file to the uploaded layer zip

### ISSUE THREAD

**Issue by RNavaneethKumar** [aws/aws-extensions-for-dotnet-cli#128]
I am trying to publish a layer with the following command

```
dotnet lambda publish-layer --region us-east-1 --aws-access-key-id (accesskey) --aws-secret-key (secret) --project-location (location) --framework netcoreapp2.1 --s3-bucket (bucketname) --layer-name (layername) --layer-type runtime-package-store
```

However all the dependency files are zipped except for "microsoft.extensions.dependencyinjection.abstractions" as shown in the last line below.

![error](https://user-images.githubusercontent.com/22679526/85280302-7d1ede80-b4a5-11ea-909c-819fc9aa947a.jpg)

Though the error says that the file does not exist, it exists. I have cross checked several times that the dll file is present is present in the temp location created by the publish-layer command everytime. Has anyone faced this issue before? Am I doing something wrong?

Version of Amazon.Lambda.Tools is 4.0.0.

My friend however was on 3.3.1. It was working properly for him. He uninstalled 3.3.1 and installed 4.0.0. He got the same error. Later he went back to 3.1.1 and the surprisingly he got the error again. It does not work anymore in his laptop too.

**Comment by RNavaneethKumar** [comment]
![error](https://user-images.githubusercontent.com/22679526/85280246-65475a80-b4a5-11ea-97bb-af631e6c81e0.jpg)

**Comment by RNavaneethKumar** [comment]
@NGL321  Were you able to reproduce this issue? If not, let me try to setup a new project that can be shared.

**Comment by clearwaterstream** [comment]
@RNavaneethKumar just a thought. Check your SDK version on the machine where you are doing the publish. I believe the lambda tool will simply leverage whatever version you have installed on your machine. If you've updated your Visual Studio recently chances are you have the latest SDK.

If you have .NET Core version 3.1.4 or 3.1.401 (or higher) then you may have issues as runtime package store handling has been changed, and the lambda tool is not yet tested with the new runtime package store particulars.

You need to use SDK 3.1.1 as this is the official SDK that is used in the Lambda runtime environment ....

https://github.com/aws/aws-extensions-for-dotnet-cli/issues/113

**Comment by RNavaneethKumar** [comment]
My SDK version was higher than 3.1.4 and I guess that could have been the issue. Thanks @clearwaterstream
