### ISSUE TITLE
`quiet` option for package-ci

### ISSUE THREAD

**Issue by hauntingEcho** [aws/aws-extensions-for-dotnet-cli#134]
Currently, when running `lambda package-ci` with `--msbuild-parameters "-consoleloggerparameters:ErrorsOnly -verbosity:quiet -nologo"`, there is still a lot of log noise (e.g. `... zipping: Amazon.Kms.dll`, `... Progress: 30%`, `Executing publish command`, etc).  Having an option to not print non-error log messages would be ideal.

## Describe the Feature

A switch to only log errors, implying `--msbuild-parameters "-consoleloggerparameters:ErrorsOnly -verbosity:quiet -nologo"`

### Is your Feature Request related to a problem?

When our developers deploy our whole product to a test environment, we are calling `package-ci` on a bunch of projects at once (currently 25).  This generates a huge amount of log noise, which can make it hard to pick out errors

## Proposed Solution

support `--verbosity quiet` to match the [Dotnet CLI documentation](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet#sdk-options-for-running-a-command).

### Describe alternatives you've considered

* just letting the logs all go to stdout and relying on devs to find the error
* dumping the output of each package-ci call to separate log files, and telling the user to check them if there's a failure

## Additional Context

I'm maintaining the CI/CD setup for a team, including local build/deployment scripts, and having less log noise would greatly simplify troubleshooting issues that others may have.  This effectively blocks us from parallelizing the local build, since any issues will become lost in the noise of other executions.

### Environment

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change  

---

This is a :rocket: Feature Request

**Comment by ashishdhingra** [comment]
Need to discuss with team. May be supporting optional parameter to control verbose output in [BundleWithBuildLambdaZip](https://github.com/aws/aws-extensions-for-dotnet-cli/blob/f0392ca5ac29e829b93695a71e1447c679cafc59/src/Amazon.Lambda.Tools/LambdaPackager.cs#L561) should help here.

**Comment by ashishdhingra** [comment]
Hi @hauntingEcho,

Good morning.

I had this discussion with the team. We should not on MSBuild parameter to turn off AWS Lambda .NET CLI extensions specific logging, instead have a new separate AWS Lambda .NET CLI extensions flag. Please advise if you would be able to submit a PR for this change.

Thanks,
Ashish

**Comment by hauntingEcho** [comment]
Hello,
It's been over a year since I've really looked at this repository, and I'm not currently doing any work with lambdas, so it's unlikely that I'll be able to submit a PR in the near future.  When you say "should not rely on MSBuild parameter", I'm curious what you're referring to?  I had mentioned that it could be useful for:

* setting the lambda extension's quiet switch to also quiet MSBuild calls made by the lambda extension
* setting dotnet CLI's quiet switch to also quiet the lambda extension (and, by extension, MSBuild too)
