### ISSUE TITLE
dotnet lambda deploy-serverless fails to upload to S3 (access denied) unless the AWS creds are included in the command

### ISSUE THREAD

**Issue by VVillagomez** [aws/aws-extensions-for-dotnet-cli#138]
## Description
When deploying a lambda with the "dotnet lambda deploy-serverless" command and needed parameters, the command fails when attempting to upload the .zip package to the S3 bucket. The AWS credentials setup for the environment terminal have the required permissions and worked as expected when trying to upload a file to that same S3 bucket with the AWS CLI.

## Reproduction Steps
Running the command (with the real values instead of the placeholders):
dotnet lambda deploy-serverless -sn ${stack_name} -sb ${bucket_name} --template-parameters "${parameters}" --tags "${tags}"
fails after building the package .zip and attempting to upload it to the S3 bucket:
"Uploading to S3. (Bucket: ${bucket_name} Key: ${keyname}.zip)
Error uploading to ${bucket_file} in bucket ${bucket}: Access Denied"

A command with AWS CLI works however: aws s3 cp file.txt s3://${bucket_name}
OR including the --aws-access-key-id, --aws-secret-key, --aws-session-token params to the command

### Logs
Error: "Uploading to S3. (Bucket: ${bucket_name} Key: ${keyname}.zip) Error uploading to ${bucket_file} in bucket ${bucket}: Access Denied"

### Environment

* OS Info: OSX Catalina 10.15.6
* Build Environment: Visual Studio | VSCode + Terminal `dotnet lambda deploy-serverless`
* Targeted .NET Platform:  .netcore2.1

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @VVillagomez,

Good morning.

In order to troubleshoot the issue, please let me know on how the credentials are setup for your environment (environment variables or shared crendentials file, etc).

Thanks,
Ashish
