### ISSUE TITLE
dotnet lambda build without deploying?

### ISSUE THREAD

**Issue by rayhaanq** [aws/aws-extensions-for-dotnet-cli#145]
Hi, I noticed that the documentation shows that it's possible to do a `dotnet lambda deploy-function` command. Is there a way to just create the deployment package without deploying it?

I wanted to create a deployment package as part of a Gitlab CI pipeline, upload it to S3 then deploy using CodeDeploy. I also wanted to enable ReadyToRun as part of the build. How can I do this?

**Comment by ashishdhingra** [comment]
Hi @rayhaanq,

Good morning.

Thanks for posting guidance question. Please refer the [aws-extensions-for-dotnet-cli](https://github.com/aws/aws-extensions-for-dotnet-cli) repository. It details about the `dotnet lambda package-ci` and `dotnet lambda package` commands which would be used to create application bundle/package. Let me know if this provides necessary guidance.

Thanks,
Ashish

**Comment by rayhaanq** [comment]
Excellent, thank you. That's exactly what I was looking for. Is there any way to set metadata on package when uploading to s3 using `dotnet lambda package-ci`? I'm just following these instructions https://aws.amazon.com/blogs/devops/automatically-deploy-from-amazon-s3-using-aws-codedeploy/ and thought it would be nice to be able to to set some metadata. Otherwise, I guess I just need to use the normal `package` and then manually upload to s3

**Comment by rayhaanq** [comment]
Actually, just done `dotnet lambda help package` and it looks like we can set the output package
