### ISSUE TITLE
NET 5 AWS Lambda Support with Container Images

### ISSUE THREAD

**Issue by genifycom** [aws/aws-extensions-for-dotnet-cli#148]
Currently trying out:

https://aws.amazon.com/blogs/developer/net-5-aws-lambda-support-with-container-images/

Section

AWS CloudFormation deployment support

The publish to AWS Lambda appears to work, the docker image builds and uploads and is listed in the ECR repository and the aspnetcorefuction is listed in the ECR images .

But the Visual Studio build log shows CREATE_FAILED

Unable to determine service/operation name to be authorized (Service AWSLambdaInternal: Status Code: 403; Error Code: AccessDeniedException: Request xxxxxxxxx; Proxy: null).

Is this to do with my permissions or something else?

**Comment by genifycom** [comment]
Could this have to do with regions?

I can successfully publish in us-east-1 but I get the previous error when publishing to us-west-1

**Comment by normj** [comment]
Could you include the publish log from Visual Studio into this issue?

**Comment by brunolauze** [comment]
I can confirm like ca-central-1 is having the same error, just switching to us-east-1 made it. 
with the command line in a github actions, so I think it's only something about CloudFormation template?
New schema not available in other regions yet? One must understand, it's like 6 days old...

**Comment by normj** [comment]
The Lambda container image launch post mentioned that support was added to a few regions initially and more coming soon.

```
You can use container images to deploy your Lambda functions today in US East (N. Virginia), US East (Ohio), US West (Oregon), Asia Pacific (Tokyo), Asia Pacific (Singapore), Europe (Ireland), Europe (Frankfurt), South America (São Paulo). We are working to add support in more Regions soon.
```
https://aws.amazon.com/blogs/aws/new-for-aws-lambda-container-image-support/

**Comment by ashishdhingra** [comment]
Please keep track of Lambda announcements to check when the support is available in other regions. Closing this issue for now.
