### ISSUE TITLE
Allow EC2 role credentials during function deployment

### ISSUE THREAD

**Issue by bslatner** [aws/aws-extensions-for-dotnet-cli#15]
My build server is an EC2 instance with a role that allows it to do everything it needs to perfrom deployments.

The `dotnet lambda deploy-function` command doesn't understand this scenario. It assumes you either specify a credential profile or, if you don't, it uses credentials from environment variables. It would be super nifty if it supported using role credentials as well.

It's possible it already supports this and I'm doing something wrong. I tried removing the "profile" value from my `aws-lambda-tools-defaults.json` file and didn't specify a profile on the command line. I wound up with this error message:

> Error determining region for bucket dgi.deploy-lambda: Error determining region for bucket dgi.deploy-lambda: Access Denied

**Comment by Kralizek** [comment]
AFAIK the lambda tool supports the instance profile without issues.

I have a teamcity build server and several build agents and they all succesfully deploy functions without us specifying any credential.

Are you sure the instance role of your instance is correctly configured?

**Comment by normj** [comment]
There is a bug in the tooling that if profile is specified in the `aws-lambda-tools-defaults.json` and the profile can't be found then it throws an error about not finding credentials. I need to fix that.

The second issue is the IAM policy you have for your instance profile doesn't have permission to check bucket location. I have made a change for the next version to change this error to a warning if it fails to determine a bucket location. The check is just to make sure we can fail fast with a reasonable error message if the bucket you select is in a different region then where you are trying to deploy to.

**Comment by bslatner** [comment]
Hmm. Okay, I thought I had the permissions correct, but I'll give it another whack.

**Comment by bslatner** [comment]
Okay, my bad. It was a role policy issue. No permissions specified for the bucket. Need to fire that devops guy. Oh wait, that's me.

It would be nifty if, when the profile didn't exist, it fell back to the role credentials. Norm noted this is the expected behavior.

**Comment by normj** [comment]
I have made that change in the dev branch to go out with the next release https://github.com/aws/aws-extensions-for-dotnet-cli/commit/68e7329f587b18eb4ce6a7fd84c1b010eec83aa4

**Comment by normj** [comment]
Version 2.1.4 was just released with this fix to continuing looking for credentials when the profile can not be found.
