### ISSUE TITLE
Blocked by "security token included in request is invalid"

### ISSUE THREAD

**Issue by gitblit** [aws/aws-extensions-for-dotnet-cli#153]
I'd like to play with deploying a lambda.  Unfortunately, I am getting stymied by the tool's ability to use my credentials.  The `aws` cli and `serverless` cli both are working fine.  `dotnet lambda`, not so much.  I have tried using environment variables - but that makes no difference.  It's unclear if `dotnet lambda` is loading my stored credentials or what is going on.  Is there any verbose logging I can activate?

![image](https://user-images.githubusercontent.com/868217/103418914-b9bb4900-4b5e-11eb-8e7e-adc1e96aea3a.png)

**Comment by ashishdhingra** [comment]
Hi @gitblit,

Good morning.

Thanks for posting guidance question. Kindly refer [Credential and profile resolution](https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/creds-assign.html) for the order in which .NET SDK searches for credentials.

On Windows, [SDK Store](https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/sdk-store.html) could also be used to create profiles and store encrypted credentials (this could happen if you use AWS Toolkit for Visual Studio). If this is the case with your environment, then try renaming/moving `RegisteredAccounts.json`. I had seen similar issue in the past and SDK store was the reason the .NET CLI commands were not working.

Please let me know if this provides necessary guidance.

Thanks,
Ashish

**Comment by gitblit** [comment]
@ashishdhingra you are the man!

>  then try renaming/moving `RegisteredAccounts.json`.

I have this file from 2016 and must have been tinkering with VS integration (I'm a die hard Jetbrains user).  Renaming this file solved my issue.  Thanks for the quick response.
