### ISSUE TITLE
dotnet lambda unable to use AWS SSO profile credentials setup via aws configure sso

### ISSUE THREAD

**Issue by stang-tgs** [aws/aws-extensions-for-dotnet-cli#154]
## Description
the dotnet lambda tool does not properly use AWS SSO profiles set in `.aws/config` via `aws configure sso` 

## Reproduction Steps
`AWS_PROFILE=my_sso_profile dotnet lambda list-functions` returns:
```
Amazon Lambda Tools for .NET Core applications (5.0.0)
Project Home: https://github.com/aws/aws-extensions-for-dotnet-cli, https://github.com/aws/aws-lambda-dotnet

Error listing Lambda functions: Unable to get IAM security credentials from EC2 Instance Metadata Service.
```
where `my_sso_profile` is an AWS SSO profile setup via `aws configure sso` and in an environment where `aws sso login --profile=my_sso_profile` has already been invoked.

### Logs
n/a

### Environment

* Build Version: Amazon Lambda Tools for .NET Core applications (5.0.0)
* OS Info: ubuntu 20.04 LTS (WSL)
* Build Environment: dotnet 3.1 (Linux)
* Targeted .NET Platform:  

## Resolution
n/a

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Need to revisit this issue once PR https://github.com/aws/aws-sdk-net/pull/1701/ is implemented.

**Comment by ashishdhingra** [comment]
Updated packages released:
- [Amazon.ElasticBeanstalk.Tools 4.1.1](https://www.nuget.org/packages/Amazon.ElasticBeanstalk.Tools/4.1.1)
- [Amazon.ECS.Tools 3.3.1](https://www.nuget.org/packages/Amazon.ECS.Tools/3.3.1)
- [Amazon.Lambda.Tools 5.0.2](https://www.nuget.org/packages/Amazon.Lambda.Tools/5.0.2)

GitHub commit https://github.com/aws/aws-extensions-for-dotnet-cli/commit/6d063478e47da7918235e492ad2a77d9b6866564
