### ISSUE TITLE
How do I use the CLI to do a lambda serverless deployment for a dotnet 5 project.

### ISSUE THREAD

**Issue by battarro** [aws/aws-extensions-for-dotnet-cli#158]
### Good morning. 

I'm trying to use the CLI to do an automated deployments to AWS lambda of my C# lambda project.
With dotnet 3.1 I would do the following.

`dotnet lambda deploy-serverless  --configuration debug --stack-name custom-webhook-dev --s3-bucket custom-deployment-dev --template serverless.dev.template --region us-east-1 --s3-prefix custom-salesforce-integration- `

This will take care of my deployment to my dev environment, while my production deployment would be similar but replacing `dev` with `prod` and debug for release.

But with 5.0 I get the following issue :

`Amazon Lambda Tools for .NET Core applications (3.2.3)
Project Home: https://github.com/aws/aws-extensions-for-dotnet-cli, https://github.com/aws/aws-lambda-dotnet

Processing CloudFormation resource AspNetCoreFunction
Initiate packaging of . for resource AspNetCoreFunction
Unknown error executing command: Value cannot be null.
Parameter name: key
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Amazon.Lambda.Tools.LambdaUtilities.DetermineTargetFrameworkFromLambdaRuntime(String lambdaRuntime, String projectLocation) in C:\codebuild\tmp\output\src109826539\src\src\Amazon.Lambda.Tools\LambdaUtilities.cs:line 38
   at Amazon.Lambda.Tools.TemplateProcessor.TemplateProcessorManager.PackageDotnetProjectAsync(IUpdateResourceField field, String location) in C:\codebuild\tmp\output\src109826539\src\src\Amazon.Lambda.Tools\TemplateProcessor\TemplateProcessorManager.cs:line 223
   at Amazon.Lambda.Tools.TemplateProcessor.TemplateProcessorManager.ProcessUpdatableResourceAsync(String templateDirectory, IUpdateResourceField field) in C:\codebuild\tmp\output\src109826539\src\src\Amazon.Lambda.Tools\TemplateProcessor\TemplateProcessorManager.cs:line 167
   at Amazon.Lambda.Tools.TemplateProcessor.TemplateProcessorManager.TransformTemplateAsync(String templateDirectory, String templateBody) in C:\codebuild\tmp\output\src109826539\src\src\Amazon.Lambda.Tools\TemplateProcessor\TemplateProcessorManager.cs:line 95
   at Amazon.Lambda.Tools.Commands.DeployServerlessCommand.PerformActionAsync() in C:\codebuild\tmp\output\src109826539\src\src\Amazon.Lambda.Tools\Commands\DeployServerlessCommand.cs:line 167
   at Amazon.Common.DotNetCli.Tools.Commands.BaseCommand`1.ExecuteAsync() in C:\codebuild\tmp\output\src109826539\src\src\Amazon.Common.DotNetCli.Tools\Commands\BaseCommand.cs:line 44
   `

It seems to be missing the key for `DetermineTargetFrameworkFromLambdaRuntime `

What value should this be? What I'm trying to do is just automate the deployment to lambda of my project, Ideally i would like one file to deploy to dev, and 1 file to deploy to production.

This is the serverless.dev.template file.
![image](https://user-images.githubusercontent.com/10959815/106615655-a8d56d00-653a-11eb-93ac-54bc7a5105f1.png)

One thing that it is missing is the "Runtime" setting that was in 3.1.
Am I supposed to add this on this file or or the command line? And if yes, what value should it be?

The value on a 3.1 template was `"Runtime": "dotnetcore3.1",`
Thank you in advance.

**Comment by ashishdhingra** [comment]
Hi @battarro,
 
Please refer https://github.com/aws/aws-lambda-dotnet/tree/master/LambdaRuntimeDockerfiles for Lambda .NET 5 base image Readme. There is also a sample in the `aws-lambda-dotnet/LambdaRuntimeDockerfiles/dotnet5/sample/` folder. Could you try using that sample project and let me know if it works?

The .NET 5 Lambda support is supported as container image. Developer blog article [.NET 5 AWS Lambda Support with Container Images](https://aws.amazon.com/blogs/developer/net-5-aws-lambda-support-with-container-images/) could be a helpful reference. For your case, after you install latest version of AWS Lambda Templates using command `dotnet new -i Amazon.Lambda.Templates`, following templates would be available (user `dotnet new -all` command for list):
- Lambda Custom Runtime Function (.NET 5)
- Lambda Empty Function (.NET 5 Container Image)
- Lambda ASP.NET Core Web API (.NET 5 Container Image)
- Lambda Empty Serverless (.NET 5 Container Image)

 You could also refer the following articles if you want to use custom runtime for .NET 5:
- [.NET 5 on AWS](https://aws.amazon.com/blogs/developer/net-5-on-aws/) 
- [Exploring .NET 5 with the AWS Toolkit for Visual Studio](https://aws.amazon.com/blogs/developer/exploring-net-5-with-the-aws-toolkit-for-visual-studio/)

Hope this helps.

Thanks,
Ashish

**Comment by battarro** [comment]
> Hi @battarro,
> 
> Please refer https://github.com/aws/aws-lambda-dotnet/tree/master/LambdaRuntimeDockerfiles for Lambda .NET 5 base image Readme. There is also a sample in the `aws-lambda-dotnet/LambdaRuntimeDockerfiles/dotnet5/sample/` folder. Could you try using that sample project and let me know if it works?
> 
> The .NET 5 Lambda support is supported as container image. Developer blog article [.NET 5 AWS Lambda Support with Container Images](https://aws.amazon.com/blogs/developer/net-5-aws-lambda-support-with-container-images/) could be a helpful reference. For your case, after you install latest version of AWS Lambda Templates using command `dotnet new -i Amazon.Lambda.Templates`, following templates would be available (user `dotnet new -all` command for list):
> 
> * Lambda Custom Runtime Function (.NET 5)
> * Lambda Empty Function (.NET 5 Container Image)
> * Lambda ASP.NET Core Web API (.NET 5 Container Image)
> * Lambda Empty Serverless (.NET 5 Container Image)
> 
> You could also refer the following articles if you want to use custom runtime for .NET 5:
> 
> * [.NET 5 on AWS](https://aws.amazon.com/blogs/developer/net-5-on-aws/)
> * [Exploring .NET 5 with the AWS Toolkit for Visual Studio](https://aws.amazon.com/blogs/developer/exploring-net-5-with-the-aws-toolkit-for-visual-studio/)
> 
> Hope this helps.
> 
> Thanks,
> Ashish

the sample deployment file in aws-lambda-dotnet/LambdaRuntimeDockerfiles/dotnet5/sample/
uses `deploy-function`
What about `deploy-derverless` is this supported?

**Comment by ashishdhingra** [comment]
Hi @battarro,

I tested, the following steps work successfully:

- Install the latest version of `Amazon.Lambda.Tools` (version '5.0.1') 
- Create a new project using `Lambda Empty Serverless (.NET 5 Container Image)` template, command `dotnet new serverless.image.EmptyServerless`. This created the following files:
**.csproj**
```XML
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <AWSProjectType>Lambda</AWSProjectType>
    <!-- This property makes the build directory similar to a publish directory and helps the AWS .NET Lambda Mock Test Tool find project dependencies. -->
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.Core" Version="1.2.0" />
    <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="2.1.0" />
    <PackageReference Include="Amazon.Lambda.APIGatewayEvents" Version="2.4.0" />
  </ItemGroup>
</Project>
```
**serverless.template**
```JSON
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Transform": "AWS::Serverless-2016-10-31",
  "Description": "An AWS Serverless Application.",
  "Resources": {
    "Get": {
      "Type": "AWS::Serverless::Function",
      "Properties": {
        "PackageType": "Image",
        "ImageConfig": {
          "EntryPoint": [
            "/lambda-entrypoint.sh"
          ],
          "Command": [
            "Issue158_NET5ServerlessLambda::Issue158_NET5ServerlessLambda.Functions::Get"
          ]
        },
        "ImageUri": "",
        "MemorySize": 256,
        "Timeout": 30,
        "Role": null,
        "Policies": [
          "AWSLambdaBasicExecutionRole"
        ],
        "Events": {
          "RootGet": {
            "Type": "Api",
            "Properties": {
              "Path": "/",
              "Method": "GET"
            }
          }
        }
      },
      "Metadata": {
        "Dockerfile": "Dockerfile",
        "DockerContext": ".",
        "DockerTag": ""
      }
    }
  },
  "Outputs": {
    "ApiURL": {
      "Description": "API endpoint URL for Prod environment",
      "Value": {
        "Fn::Sub": "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
      }
    }
  }
}
```
**Function.cs**
```C#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;

using Amazon.Lambda.Core;
using Amazon.Lambda.APIGatewayEvents;

// Assembly attribute to enable the Lambda function's JSON input to be converted into a .NET class.
[assembly: LambdaSerializer(typeof(Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer))]

namespace Issue158_NET5ServerlessLambda
{
    public class Functions
    {
        /// <summary>
        /// Default constructor that Lambda will invoke.
        /// </summary>
        public Functions()
        {
        }


        /// <summary>
        /// A Lambda function to respond to HTTP Get methods from API Gateway
        /// </summary>
        /// <param name="request"></param>
        /// <returns>The API Gateway response.</returns>
        public APIGatewayProxyResponse Get(APIGatewayProxyRequest request, ILambdaContext context)
        {
            context.Logger.LogLine("Get Request\n");

            var response = new APIGatewayProxyResponse
            {
                StatusCode = (int)HttpStatusCode.OK,
                Body = "Hello AWS Serverless",
                Headers = new Dictionary<string, string> { { "Content-Type", "text/plain" } }
            };

            return response;
        }
    }
}
```
**aws-lambda-tools-defaults.json**
```JSON
{
  "Information": [
    "This file provides default values for the deployment wizard inside Visual Studio and the AWS Lambda commands added to the .NET Core CLI.",
    "To learn more about the Lambda commands with the .NET Core CLI execute the following command at the command line in the project root directory.",
    "dotnet lambda help",
    "All the command line options for the Lambda command can be specified in this file."
  ],
  "profile": "",
  "region": "",
  "configuration": "Release",
  "s3-prefix": "Issue158_NET5ServerlessLambda/",
  "template": "serverless.template",
  "template-parameters": "",
  "docker-host-build-output-dir": "./bin/Release/net5.0/linux-x64/publish"
}
```
You could set the `region` or else .NET CLI would use default region configured in your profile chain.
**Dockerfile**
```
FROM public.ecr.aws/lambda/dotnet:5.0

WORKDIR /var/task

# This COPY command copies the .NET Lambda project's build artifacts from the host machine into the image. 
# The source of the COPY should match where the .NET Lambda project publishes its build artifacts. If the Lambda function is being built 
# with the AWS .NET Lambda Tooling, the `--docker-host-build-output-dir` switch controls where the .NET Lambda project
# will be built. The .NET Lambda project templates default to having `--docker-host-build-output-dir`
# set in the aws-lambda-tools-defaults.json file to "bin/Release/net5.0/linux-x64/publish".
#
# Alternatively Docker multi-stage build could be used to build the .NET Lambda project inside the image.
# For more information on this approach checkout the project's README.md file.
COPY "bin/Release/net5.0/linux-x64/publish"  .
```

- Execute the command `dotnet lambda deploy-serverless`. It will ask for missing parameters like (CloudFormation stack name and S3 bucket name), build the Docker image, create ECR repository, push the Docker image to ECR repository, creates CLoudFormation stack, etc. Following is the output:
```
Amazon Lambda Tools for .NET Core applications (5.0.1)
Project Home: https://github.com/aws/aws-extensions-for-dotnet-cli, https://github.com/aws/aws-lambda-dotnet
	
Enter CloudFormation Stack Name: (CloudFormation stack name for an AWS Serverless application)
teststack-issue158
Enter S3 Bucket: (S3 bucket to upload the build output)
testbucket-issue158
Processing CloudFormation resource Get
Initiate packaging of . for resource Get
Building Docker image for /Users/<username>/dev/repros/Issue158_NET5ServerlessLambda/src/Issue158_NET5ServerlessLambda/.
Creating image tag from project: issue158_net5serverlesslambda
Executing publish command
... invoking 'dotnet publish', working folder '/Users/<username>/dev/repros/Issue158_NET5ServerlessLambda/src/Issue158_NET5ServerlessLambda/././bin/Release/net5.0/linux-x64/publish'
... dotnet publish "/Users/<username>/dev/repros/Issue158_NET5ServerlessLambda/src/Issue158_NET5ServerlessLambda/." --output "/Users/<username>/dev/repros/Issue158_NET5ServerlessLambda/src/Issue158_NET5ServerlessLambda/././bin/Release/net5.0/linux-x64/publish" --configuration "Release" /p:GenerateRuntimeConfigurationFiles=true --runtime linux-x64 --self-contained false 
... publish: Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET
... publish: Copyright (C) Microsoft Corporation. All rights reserved.
... publish:   Determining projects to restore...
... publish:   Restored /Users/<username>/dev/repros/Issue158_NET5ServerlessLambda/src/Issue158_NET5ServerlessLambda/Issue158_NET5ServerlessLambda.csproj (in 145 ms).
... publish:   Issue158_NET5ServerlessLambda -> /Users/<username>/dev/repros/Issue158_NET5ServerlessLambda/src/Issue158_NET5ServerlessLambda/bin/Release/net5.0/linux-x64/Issue158_NET5ServerlessLambda.dll
... publish:   Issue158_NET5ServerlessLambda -> /Users/<username>/dev/repros/Issue158_NET5ServerlessLambda/src/Issue158_NET5ServerlessLambda/bin/Release/net5.0/linux-x64/publish/
Changed permissions on published file (chmod +rx Amazon.Lambda.APIGatewayEvents.dll).
Changed permissions on published file (chmod +rx Issue158_NET5ServerlessLambda.runtimeconfig.json).
Changed permissions on published file (chmod +rx Issue158_NET5ServerlessLambda.dll).
Changed permissions on published file (chmod +rx Issue158_NET5ServerlessLambda.pdb).
Changed permissions on published file (chmod +rx Amazon.Lambda.Serialization.SystemTextJson.dll).
Changed permissions on published file (chmod +rx Issue158_NET5ServerlessLambda.deps.json).
Changed permissions on published file (chmod +rx Amazon.Lambda.Core.dll).
Inspecting Dockerfile to figure how to build project and docker image
Executing docker build
... invoking 'docker build', working folder '/Users/<username>/dev/repros/Issue158_NET5ServerlessLambda/src/Issue158_NET5ServerlessLambda/., docker file /Users/<username>/dev/repros/Issue158_NET5ServerlessLambda/src/Issue158_NET5ServerlessLambda/./Dockerfile, image name issue158_net5serverlesslambda:latest'
... docker build -f "/Users/<username>/dev/repros/Issue158_NET5ServerlessLambda/src/Issue158_NET5ServerlessLambda/./Dockerfile" -t issue158_net5serverlesslambda:latest .
... docker build: Sending build context to Docker daemon  380.9kB
... docker build: Step 1/3 : FROM public.ecr.aws/lambda/dotnet:5.0
... docker build:  ---> ba2bc20984a3
... docker build: Step 2/3 : WORKDIR /var/task
... docker build:  ---> Using cache
... docker build:  ---> 3619a1613042
... docker build: Step 3/3 : COPY "bin/Release/net5.0/linux-x64/publish"  .
... docker build:  ---> Using cache
... docker build:  ---> b04ddf7a2eea
... docker build: Successfully built b04ddf7a2eea
... docker build: Successfully tagged issue158_net5serverlesslambda:latest
Fetching ECR authorization token to use to login with the docker CLI
Executing docker CLI login command
... invoking 'docker login'
... docker login: WARNING! Using --password via the CLI is insecure. Use --password-stdin.
... docker login: Login Succeeded
Creating ECR Repository issue158_net5serverlesslambda
Taging image issue158_net5serverlesslambda:latest with issue158_net5serverlesslambda:get-b04ddf7a2eea-latest
... invoking 'docker tag'
Pushing image to ECR repository
... invoking 'docker push'
The push refers to repository [139480602983.dkr.ecr.us-east-2.amazonaws.com/issue158_net5serverlesslambda]
ac77a01a8779: Pushed 
20b520014f96: Pushed 
d5ac03f282c5: Pushed 
3880d8bcfa4c: Pushed 
5389fd645e89: Pushed 
d6fa53d6caa6: Pushed 
5a678a98c045: Pushed 
2fc1ed82d996: Pushed 
66a34dccfecd: Pushed 
get-b04ddf7a2eea-latest: digest: sha256:d19f3c3060022475de02ba7590d80eb557cf54cf8edd4d0131e5f2582c6c5753 size: 2202
Image 139480602983.dkr.ecr.us-east-2.amazonaws.com/issue158_net5serverlesslambda:get-b04ddf7a2eea-latest Push Complete. 
Uploading to S3. (Bucket: testbucket-issue158 Key: Issue158_NET5ServerlessLambda/teststack-issue158-serverless-637478611380181860.template)
... Progress: 100%
Found existing stack: False
CloudFormation change set created
... Waiting for change set to be reviewed
Created CloudFormation stack teststack-issue158
   
Timestamp            Logical Resource Id                      Status                                   
-------------------- ---------------------------------------- ---------------------------------------- 
2/2/2021 11:12 AM    teststack-issue158                       CREATE_IN_PROGRESS                      
2/2/2021 11:12 AM    GetRole                                  CREATE_IN_PROGRESS                      
2/2/2021 11:12 AM    GetRole                                  CREATE_IN_PROGRESS                      
2/2/2021 11:12 AM    GetRole                                  CREATE_COMPLETE                         
2/2/2021 11:12 AM    Get                                      CREATE_IN_PROGRESS                      
2/2/2021 11:12 AM    Get                                      CREATE_IN_PROGRESS                      
2/2/2021 11:13 AM    Get                                      CREATE_COMPLETE                         
2/2/2021 11:13 AM    ServerlessRestApi                        CREATE_IN_PROGRESS                      
2/2/2021 11:13 AM    ServerlessRestApi                        CREATE_IN_PROGRESS                      
2/2/2021 11:13 AM    ServerlessRestApi                        CREATE_COMPLETE                         
2/2/2021 11:13 AM    GetRootGetPermissionProd                 CREATE_IN_PROGRESS                      
2/2/2021 11:13 AM    ServerlessRestApiDeployment9d78fb6c57    CREATE_IN_PROGRESS                      
2/2/2021 11:13 AM    GetRootGetPermissionProd                 CREATE_IN_PROGRESS                      
2/2/2021 11:13 AM    ServerlessRestApiDeployment9d78fb6c57    CREATE_IN_PROGRESS                      
2/2/2021 11:13 AM    ServerlessRestApiDeployment9d78fb6c57    CREATE_COMPLETE                         
2/2/2021 11:13 AM    ServerlessRestApiProdStage               CREATE_IN_PROGRESS                      
2/2/2021 11:13 AM    ServerlessRestApiProdStage               CREATE_IN_PROGRESS                      
2/2/2021 11:13 AM    ServerlessRestApiProdStage               CREATE_COMPLETE                         
2/2/2021 11:13 AM    GetRootGetPermissionProd                 CREATE_COMPLETE                         
2/2/2021 11:13 AM    teststack-issue158                       CREATE_COMPLETE                         
Stack finished updating with status: CREATE_COMPLETE
   
Output Name                    Value                                             
------------------------------ --------------------------------------------------
ApiURL                         https://7qliaeyik9.execute-api.us-east-2.amazonaws.com/Prod/
```


Kindly note that you need to have Docker Desktop installed and properly configured. The .NET CLI command `dotnet lambda deploy-serverless` would use `docker build` command to build .NET 5 Docker image.

Also ensure your account has relevant permissions required for creating ECR repository and other deployment steps. You also need S3 bucket to upload the build output.

Hope this helps. Closing this issue since it provides guidance for the original request. Feel free to open a new issue in case you encounter any problem.

Thanks,
Ashish
