### ISSUE TITLE
Zip files not optimised when using Microsoft.NET.Sdk project type

### ISSUE THREAD

**Issue by bazwilliams** [aws/aws-extensions-for-dotnet-cli#16]
When I `dotnet lambda publish` in an `Microsoft.NET.Sdk.Web` project, much of the asp.net dlls are not included in the zip file leading to a lean zip file (often < 1MB). 

My current project requires lambdas driven by SNS and therefore I use the `Microsoft.NET.Sdk` project type; when I perform `dotnet lambda publish`, the resulting zip still contains those `Microsoft.AspNetCore.*` dlls with a resulting ZIP of around 16MB!

**Comment by normj** [comment]
If you have ASP.NET Core dependencies then you are going to want to have the `SDK` setting set to `Microsoft.NET.Sdk.Web`. The msbuild target files associated with that SDK is what has the filtering logic for the ASP.NET Core dependencies.

**Comment by bazwilliams** [comment]
Thanks - a dependent library had it listed as a dependency, luckily I'm in control of that library so was able to change the library avoiding the dependency. 

My Zip is now 1.2MB, still a little large, but much better. 

Incidentally, if I change the project setting to `Microsoft.NET.Sdk.Web` then the build fails with:

```
... publish: CSC : error CS5001: Program does not contain a static 'Main' method suitable for an entry point [csproj]
Failed to create application package
```

**Comment by normj** [comment]
Closing as I believe the original question was answered. For me to answer the `lack of Main` question I would need to see the whole csproj file. If that is still a problem feel free to open a separate issue for it.
