### ISSUE TITLE
Zip packages have unique hashes on every publish

### ISSUE THREAD

**Issue by aohotnik** [aws/aws-extensions-for-dotnet-cli#162]
## Description
Due to the use of temporary file names for layer manifests pulled from s3 bucket the produced zip package will have different hash every build. This happens because of 'dotnet publish' including manifest file name in deps.json files. 

## Reproduction Steps
1. Deploy a layer to s3 using layer publishing commands of cli extension.
2. Create a project having one function and a template file describing that function with layer from step 1 attached.
3. Run deploy-serverless or package-ci commands for this template.
4. Open the produced zip package and study contents of deps.json file
5. Note the random file name runtimeStoreManifestName property
6. Repeat command executed before and do step 5

### Logs

... dotnet publish --output "C:\********\bin\Release\netcoreapp3.1\publish" --configuration "Release" --framework "netcoreapp3.1" /p:GenerateRuntimeConfigurationFiles=true --runtime linux-x64 --self-contained false  --manifest "C:\Users\*******\AppData\Local\Temp\tmp8517.tmp"

### Environment

* Build Version: 5.0.1
* OS Info: Windows 10 and Amazon Linux 2
* Build Environment: Visual Studio 2019
* Targeted .NET Platform:  netcoreapp3.1

## Resolution
- [V] :wave: I can/would-like-to implement a fix for this problem myself

I already have fix for the issue, will PR it soon.

Removing this bug however may have a change in behavior due to how SAM/CF is bugged when handling AutoPublishAlias and zip packages with static content between publish, causing version already exists issue. IMHO bug should be fixed as it breaks expectation that packages should not be different when no change to code is introduced. Existing templates that will start failing should be fixed by using AutoPublishCodeSha256.

There is also a bug in SAM/CF that doesn't treat sole addition of AutoPublishCodeSha256 to a function, when it wasn't set before  and no other significant changes, leads to same version exists issue. In that case failing function can have an update to its description to force deployment to proceed. https://github.com/aws/serverless-application-model/issues/1497

---

This is a :bug: bug-report

**Comment by normj** [comment]
The PR for this was shipped as part of  [Amazon.Lambda.Tools 5.0.2](https://www.nuget.org/packages/Amazon.Lambda.Tools/5.0.2).
