### ISSUE TITLE
Relative paths in package-ci, breaking change in 5.0.2

### ISSUE THREAD

**Issue by tkoster** [aws/aws-extensions-for-dotnet-cli#165]
## Description

Version 5.0.2 of `Amazon.Lambda.Tools` introduced a change to the way paths are resolved by the `package-ci` command that differs from version 5.0.1. This was a breaking change for us that required us to pin version 5.0.1 in our build system.

As this was a patch version (not a major version) I assume this break was unintended.

## Reproduction Steps

I prepared a small C# serverless project here: [dotnet-lambda-repro.zip](https://github.com/aws/aws-extensions-for-dotnet-cli/files/6240881/dotnet-lambda-repro.zip) (3KB). I used `dotnet new serverless.EmptyServerless` and deleted unnecessary files.

1. Download and unzip the archive [dotnet-lambda-repro.zip](https://github.com/aws/aws-extensions-for-dotnet-cli/files/6240881/dotnet-lambda-repro.zip)
2. In the solution root directory, run `dotnet tool restore`. This installs version 5.0.2 of the tool in this project's sandbox.
3. In the solution root directory, run `dotnet lambda package-ci --project-location PathRepro --template template.yaml --s3-bucket thisisans3bucket --output-template template-packaged.yaml`.

The S3 bucket need not exist to reproduce the issue.

### Observed

Step 3 fails to build the project.

```
Amazon Lambda Tools for .NET Core applications (5.0.2)
Project Home: https://github.com/aws/aws-extensions-for-dotnet-cli, https://github.com/aws/aws-lambda-dotnet

Processing CloudFormation resource Get
Initiate packaging of . for resource Get
Unknown error executing command: Could not find a part of the path '.../dotnet-lambda-repro/PathRepro/PathRepro'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Amazon.Common.DotNetCli.Tools.Commands.BaseCommand`1.EnsureInProjectDirectory() in C:\codebuild\tmp\output\src013852975\src\src\Amazon.Common.DotNetCli.Tools\Commands\BaseCommand.cs:line 863
   at Amazon.Lambda.Tools.Commands.PackageCommand.PerformActionAsync() in C:\codebuild\tmp\output\src013852975\src\src\Amazon.Lambda.Tools\Commands\PackageCommand.cs:line 137
   at Amazon.Common.DotNetCli.Tools.Commands.BaseCommand`1.ExecuteAsync() in C:\codebuild\tmp\output\src013852975\src\src\Amazon.Common.DotNetCli.Tools\Commands\BaseCommand.cs:line 46
Error packaging up project in .../dotnet-lambda-repro/PathRepro/. for CloudFormation resource Get
```

### Expected

The command in step 3 should successfully compile and package the project, as it does with version 5.0.1.

You can experience this easily by editing `.config/dotnet-tools.json` and changing the `version` property to `5.0.1`.

```
Amazon Lambda Tools for .NET Core applications (5.0.1)
Project Home: https://github.com/aws/aws-extensions-for-dotnet-cli, https://github.com/aws/aws-lambda-dotnet

Processing CloudFormation resource Get
Initiate packaging of . for resource Get
Executing publish command
... invoking 'dotnet publish', working folder '.../dotnet-lambda-repro/PathRepro/./bin/Release/netcoreapp3.1/publish'
... dotnet publish --output ".../dotnet-lambda-repro/PathRepro/./bin/Release/netcoreapp3.1/publish" --configuration "Release" --framework "netcoreapp3.1" /p:GenerateRuntimeConfigurationFiles=true --runtime linux-x64 --self-contained false
... publish: Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET
... publish: Copyright (C) Microsoft Corporation. All rights reserved.
... publish:   Determining projects to restore...
etc
```

(If you used a nonexistent bucket name, the command fails there trying to upload to S3. That is fine, this issue is about packaging the code.)

### Environment

* Build Version: Amazon.Lambda.Tools 5.0.2
* OS Info: AmazonLinux (CodeBuild), MacOS
* Build Environment: Command line
* Targeted .NET Platform:  netcoreapp3.1

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Looks like the .NET CLI Lambda tools `5.1.0` is appending extra `PathRepro` in the path `PathRepro/PathRepro`.

**Comment by normj** [comment]
You are correct. This was unintentional breaking change and we will get it fixed up.

**Comment by ashishdhingra** [comment]
This is fixed in `Amazon.Lambda.Tools 5.1.1`
