### ISSUE TITLE
MSBuild Error MSB3030: apphost.exe not found

### ISSUE THREAD

**Issue by drvora** [aws/aws-extensions-for-dotnet-cli#168]
Starting April 16th we have started receiving build errors, build was successful on April 12th. To rule out code issues, I had tried to build code which was successful on 12th and it also failed. That led me to presume it had something to do with version 5.1.1 (released on April 14th) as there are no changes done to our build process whatsoever for months.  We are receiving following error during build. 

publish: C:\Program Files\dotnet\sdk\5.0.202\Microsoft.Common.CurrentVersion.targets(4919,5): error MSB3030: Could not copy the file "D:\a\1\s\TravelSwitch2013\TravelSwitch.SharedViews.Netcore\obj\Release\netcoreapp3.1\apphost.exe" because it was not found. [D:\a\1\s\TravelSwitch2013\TravelSwitch.SharedViews.Netcore\TravelSwitch.SharedViews.Netcore.csproj]

This issue is breaking our builds and ability to push updates to prod. Any help is appreciated.

**Comment by ashishdhingra** [comment]
Hi @drvora,

Good afternoon.

Looking at the checkin for `Amazon.Lambda.Tools 5.1.1`, I do not see any reason for it to cause the build to fail. The only thing that we committed is to fix a broken change made earlier while passing along the original command line arguments to the command chain. Kindly check the commit history https://github.com/aws/aws-extensions-for-dotnet-cli/commit/4c101790a804789f62e9131cb76cbad0e3fe9c56. Similar issue reported in Microsoft's repository https://github.com/dotnet/sdk/issues/3122. Not sure if it's related but might provide some pointers.

Thanks,
Ashish

**Comment by drvora** [comment]
Thanks for the prompt reply Ashish. We use Azure DevOps pipeline's "AWS Lambda .NET Core" task provided by AWS extensions. This task automatically does the install of Amazon.Lambda.Tools without any manual intervention. No project files have been changed, just a minor logic change in code. Only difference I see is the version change from 5.1.0 to 5.1.1. Also, I don't see a way to specify a version to use in case of an issue like this where I could just specify an old version until issue is resolved. It just runs "dotnet.exe tool install -g Amazon.Lambda.Tools" by itself. It does fail on dotnet publish.

**Comment by ashishdhingra** [comment]
@drvora Kindly try running the `dotnet publish` command and also the `dotnet lambda` command that your pipeline executes outside of the pipeline. I have seen some blog posts mentioning issues with Azure Pipelines with latest .NET 5. `Amazon.Lambda.Tools` does not update .NET 5 runtime. You may also force to install specific version of `Amazon.Lambda.Tools` using the `--version` flag. In worst case, you might have to open a support ticket with Azure support.
