### ISSUE TITLE
dotnet lambda deploy-serverless fails to upload to S3 (access denied)

### ISSUE THREAD

**Issue by jayeshnazre** [aws/aws-extensions-for-dotnet-cli#171]
## Description
dotnet lambda deploy-serverless fails to upload to S3 (access denied)
A few details -
I used AWS Toolkit for VS2019 and used Visual Studio.NET 2019 IDE (not visual studio code) to pick a sample .NET serverless application template. I am able to deploy the application via the VS2019 GUI by right clicking on the project in the IDE. However when I try to do the same via dotnet CLI command it error's out with access denied error for S3.

## Reproduction Steps
Run the command 
dotnet lambda deploy-serverless 
and you get - failed to upload to S3 (access denied) error

### Logs
Get error stating error uploading to S3. 

### Environment

* Build Version: dotnet 5.0.202
* OS Info: Windows 10 
* Build Environment: Terminal `dotnet` 
* Targeted .NET Platform:  
.NET Core 3.X  for AWS
---

This is a :bug: bug-report

**Comment by jayeshnazre** [comment]
This is the log when I do deployment of serverless via VS2019 .NET IDE
Processing 1 substitutions.
Processing substitution: $.Resources.StateMachine.Properties.DefinitionString.Fn::Sub
               Found element of type String
               Reading: C:\delthis\TradeReporting\mycode\AWSServerless1\AWSServerless1\state-machine.json
Processing CloudFormation resource GreetingTask
Initiate packaging of . for resource GreetingTask
Executing publish command
Deleted previous publish folder
... invoking 'dotnet publish', working folder 'C:\delthis\TradeReporting\mycode\AWSServerless1\AWSServerless1\.\bin\Release\netcoreapp3.1\publish'
... dotnet publish --output "C:\delthis\TradeReporting\mycode\AWSServerless1\AWSServerless1\.\bin\Release\netcoreapp3.1\publish" --configuration "Release" --framework "netcoreapp3.1" /p:GenerateRuntimeConfigurationFiles=true --runtime linux-x64 --self-contained false 
... publish: Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET
... publish: Copyright (C) Microsoft Corporation. All rights reserved.
... publish:   Determining projects to restore...
... publish:   Restored C:\delthis\TradeReporting\mycode\AWSServerless1\AWSServerless1\AWSServerless1.csproj (in 104 ms).
... publish:   AWSServerless1 -> C:\delthis\TradeReporting\mycode\AWSServerless1\AWSServerless1\bin\Release\netcoreapp3.1\linux-x64\AWSServerless1.dll
... publish:   AWSServerless1 -> C:\delthis\TradeReporting\mycode\AWSServerless1\AWSServerless1\bin\Release\netcoreapp3.1\publish\
Zipping publish folder C:\delthis\TradeReporting\mycode\AWSServerless1\AWSServerless1\.\bin\Release\netcoreapp3.1\publish to C:\Users\jnazre\AppData\Local\Temp\8\GreetingTask-CodeUri-Or-ImageUri-637572831983127765.zip
... zipping: Amazon.Lambda.Core.dll
... zipping: Amazon.Lambda.Serialization.SystemTextJson.dll
... zipping: AWSServerless1.deps.json
... zipping: AWSServerless1.dll
... zipping: AWSServerless1.pdb
... zipping: AWSServerless1.runtimeconfig.json
Created publish archive (C:\Users\jnazre\AppData\Local\Temp\8\GreetingTask-CodeUri-Or-ImageUri-637572831983127765.zip).
Lambda project successfully packaged: C:\Users\jnazre\AppData\Local\Temp\8\GreetingTask-CodeUri-Or-ImageUri-637572831983127765.zip
Uploading to S3. (Bucket: ******* Key: AWSServerless1/GreetingTask-CodeUri-Or-ImageUri-637572831983127765-637572832009888054.zip)
... Progress: 100%
Processing CloudFormation resource SalutationsTask
Using previous upload artifact s3://***/AWSServerless1/GreetingTask-CodeUri-Or-ImageUri-637572831983127765-637572832009888054.zip for resource SalutationsTask
Uploading to S3. (Bucket: **** Key: AWSServerless1/MyStack1-serverless2-637572832012770989.template)
... Progress: 100%
Found existing stack: False
CloudFormation change set created
... Waiting for change set to be reviewed
Created CloudFormation stack MyStack1
Config settings saved to C:\delthis\TradeReporting\mycode\AWSServerless1\AWSServerless1\aws-lambda-tools-defaults.json


**As you can see the deployment works from the IDE when I right click and say "publish AWS Lambda"**
**Below is the error on the same machine I get when I do the same via dotnet cli:** 
c:\delthis\TradeReporting\mycode\AWSServerless1\AWSServerless1>dotnet lambda deploy-serverless
Amazon Lambda Tools for .NET Core applications (5.1.2)
Project Home: https://github.com/aws/aws-extensions-for-dotnet-cli, https://github.com/aws/aws-lambda-dotnet

Processing 1 substitutions.
Processing substitution: $.Resources.StateMachine.Properties.DefinitionString.Fn::Sub
        Found element of type String
        Reading: c:\delthis\TradeReporting\mycode\AWSServerless1\AWSServerless1\state-machine.json
Processing CloudFormation resource GreetingTask
Initiate packaging of . for resource GreetingTask
Executing publish command
Deleted previous publish folder
... invoking 'dotnet publish', working folder 'c:\delthis\TradeReporting\mycode\AWSServerless1\AWSServerless1\.\bin\Release\netcoreapp3.1\publish'
... dotnet publish --output "c:\delthis\TradeReporting\mycode\AWSServerless1\AWSServerless1\.\bin\Release\netcoreapp3.1\publish" --configuration "Release" --framework "netcoreapp3.1" /p:GenerateRuntimeConfigurationFiles=true --runtime linux-x64 --self-contained false
... publish: Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET
... publish: Copyright (C) Microsoft Corporation. All rights reserved.
... publish:   Determining projects to restore...
... publish:   Restored c:\delthis\TradeReporting\mycode\AWSServerless1\AWSServerless1\AWSServerless1.csproj (in 103 ms).
... publish:   AWSServerless1 -> c:\delthis\TradeReporting\mycode\AWSServerless1\AWSServerless1\bin\Release\netcoreapp3.1\linux-x64\AWSServerless1.dll
... publish:   AWSServerless1 -> c:\delthis\TradeReporting\mycode\AWSServerless1\AWSServerless1\bin\Release\netcoreapp3.1\publish\
Zipping publish folder c:\delthis\TradeReporting\mycode\AWSServerless1\AWSServerless1\.\bin\Release\netcoreapp3.1\publish to C:\Users\jnazre\AppData\Local\Temp\8\GreetingTask-CodeUri-Or-ImageUri-637572836055926589.zip
... zipping: Amazon.Lambda.Core.dll
... zipping: Amazon.Lambda.Serialization.SystemTextJson.dll
... zipping: AWSServerless1.deps.json
... zipping: AWSServerless1.dll
... zipping: AWSServerless1.pdb
... zipping: AWSServerless1.runtimeconfig.json
Created publish archive (C:\Users\jnazre\AppData\Local\Temp\8\GreetingTask-CodeUri-Or-ImageUri-637572836055926589.zip).
Lambda project successfully packaged: C:\Users\jnazre\AppData\Local\Temp\8\GreetingTask-CodeUri-Or-ImageUri-637572836055926589.zip
Uploading to S3. (Bucket: ******* Key: AWSServerless1/GreetingTask-CodeUri-Or-ImageUri-637572836055926589-637572836074737582.zip)
Error uploading to AWSServerless1/GreetingTask-CodeUri-Or-ImageUri-637572836055926589-637572836074737582.zip in bucket *******: Access Denied

**Comment by jayeshnazre** [comment]
Also aws cli works on the same machine. So I know its not the credentials issue nor an issue with the access to upload file to s3

**Comment by jayeshnazre** [comment]
Any pointers help?

**Comment by ashishdhingra** [comment]
Hi @jayeshnazre, 

Good morning.

Thanks for posting the issue. Please let me know how you have configured the credentials. You need to configure your credentials in any of the search locations specified in the page [Credential and profile resolution](https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/creds-assign.html). AWS SDK for .NET searches for credentials in a certain order and uses the first available set for the current application. 

Kindly take note of the article [Using the SDK Store (Windows only)](https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/sdk-store.html). Since you are using AWS Toolkit for Visual Studio, it might be looking at `%USERPROFILE%\AppData\Local\AWSToolkit\RegisteredAccounts.json`. If such file exists, you may temporarily rename this file (or move this file to a different location) so that the default credentials (that work with AWS CLI) are used.

Hope this helps.

Thanks,
Ashish
