### ISSUE TITLE
Attempting to supply input .NET project for 'dotnet lambda package' results in 'The parameter is incorrect'

### ISSUE THREAD

**Issue by NinovanderMark** [aws/aws-extensions-for-dotnet-cli#175]
## Description
We have a .NET solution, created using the AWS serverless templates, and we're using the `dotnet lambda package` tool to package our Lambda's for deployment to AWS. I'm running into an issue with one of the projects, because it's sharing a folder with another project/solution, meaning I get the following error running this command for that project's folder:

```
publish: MSBUILD : error MSB1011: Specify which project or solution file to use because this folder contains more than one project or solution file.
```

Fortunately there's a command-line parameter that we can use to supply the project to build, namely `-pl` or `--project-location`. However, when I try to use that to refer to the project I intend to build I'm met with the following error:

```
Unknown error executing command: The parameter is incorrect : 'C:\Code\nvandermark\AWSPublishTest\AWSPublishTest.csproj'
```

I'm not sure what's going wrong, but looks to me like a bug. Alternatively, perhaps this command line parameter is not meant to point to a specific project, but rather an alternative path to look for projects, which obviously wouldn't help in my particular case.

In either case, I'm hoping you may be able to help me find a solution to this conundrum.

## Reproduction Steps

1. Create new .NET 3.1 application, based on AWS' serverless template.
2. Give the solution a different name from the project, ensure both are in the same folder
3. Attempting to run `dotnet lambda package` fails, because there are 2 different build targets
4. Run `dotnet lambda package -pl "AWSPublishTest.csproj"` to provide the project to build
5. `Unknown error executing command: The parameter is incorrect <ProjectPath>`

Alternatively, the following [example project](https://github.com/aws/aws-extensions-for-dotnet-cli/files/6649141/AWSPublishTest.zip) can be used instead of creating a new project.

### Logs
```
PS C:\Code\nvandermark\AWSPublishTest> dotnet lambda package -pl "AWSPublishTest.csproj"
Amazon Lambda Tools for .NET Core applications (5.0.1)
Project Home: https://github.com/aws/aws-extensions-for-dotnet-cli, https://github.com/aws/aws-lambda-dotnet

Unknown error executing command: The parameter is incorrect : 'C:\Code\nvandermark\AWSPublishTest\AWSPublishTest.csproj'
   at System.IO.Enumeration.FileSystemEnumerator`1.GetData()
   at System.IO.Enumeration.FileSystemEnumerator`1.FindNextEntry()
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Amazon.Common.DotNetCli.Tools.Commands.BaseCommand`1.EnsureInProjectDirectory() in C:\codebuild\tmp\output\src434706839\src\src\Amazon.Common.DotNetCli.Tools\Commands\BaseCommand.cs:line 863
   at Amazon.Lambda.Tools.Commands.PackageCommand.PerformActionAsync() in C:\codebuild\tmp\output\src434706839\src\src\Amazon.Lambda.Tools\Commands\PackageCommand.cs:line 137
   at Amazon.Common.DotNetCli.Tools.Commands.BaseCommand`1.ExecuteAsync() in C:\codebuild\tmp\output\src434706839\src\src\Amazon.Common.DotNetCli.Tools\Commands\BaseCommand.cs:line 46
```

### Environment
* Build Version: Amazon Lambda Tools for .NET Core applications (5.0.1)
* OS Info: Microsoft Windows 10 Pro build 19043
* Build Environment: PowerShell 7.1.3 using DotNet SDK 5.0.204
* Targeted .NET Platform:  3.1

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @NinovanderMark,

Good afternoon.

Thanks for posting the issue. The argument `-pl` (or `--project-location`) specifies the `The location of the project, if not set the current directory will be assumed.`. Hence it should point to directory containing the project. The error `publish: MSBUILD : error MSB1050: Specify which project or solution file to use because the folder "/Users/ashdhin/Downloads/./AWSPublishTest" contains more than one project or solution file.` appears to be thrown by the `dotnet publish` command since it is finding both `.csproj` and `.sln` file in the same directory. The .NET CLI Lambda extension tools passes the calculated project location (directory) to the `dotnet publish` command which fails. The only workaround at this stage is to move `.sln` file outside of the project's directory.

I will discuss this issue with developer for better workaround.

Thanks,
Ashish
