### ISSUE TITLE
multiple containers in aws-ecs-tools-defaults.json? 

### ISSUE THREAD

**Issue by mrsuau627** [aws/aws-extensions-for-dotnet-cli#179]
I have a service that I've built and deployed to ECS Fargate. I use `dotnet ecs deploy-service ` in a github action to push up the service and it works great.

I've been tasked with adding monitoring to the application using [Datadog](https://docs.datadoghq.com/). For Datadog, on something running in Fargate, it seems like the recommended way is to have a "sidecar container" running as part of the service. So what I'm looking to do is add an additional container to my task definition created by the deploy-service command that would be for the Datadog image to run in. 

Is there a way to achieve this using the deploy-service command and the aws-ecs-tools-defaults.json file? If not, can you think of another way to achieve something like this?

Thanks!

**Comment by ashishdhingra** [comment]
Hi @mrsuau627,

Good morning.

Thanks for posting guidance question.

Looking at the examples at https://github.com/aws/aws-extensions-for-dotnet-cli/tree/master/testapps/HelloWorldWebApp and  https://net-immersionday.workshop.aws/2-how-how-to-deploy-donet-apps/ecs-fargate/deploy-ecsfargate-task.html, there doesn't appear to be a way to specify additional containers for task definition. The `dotnet ecs deploy-service` invokes [DeployServiceCommand](https://github.com/aws/aws-extensions-for-dotnet-cli/blob/f0392ca5ac29e829b93695a71e1447c679cafc59/src/Amazon.ECS.Tools/Commands/DeployServiceCommand.cs#L18) which automatically creates task definition and container based on string name values. There is no option to specify multiple containers for a task definition.

For your requirement, you may refer [Tutorial: Creating a cluster with an EC2 task using the AWS CLI](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_AWSCLI_EC2.html) for some guidance.

Hope this helps.

Thanks,
Ashish

**Comment by mrsuau627** [comment]
Thank you for the quick reply @ashishdhingra . I will take a look at the links you provided and see if any might help accomplish what I'm going for. 

Another related follow-up question: how are the following command line params used from this tool for the `deploy-service` command?
```
      -t     | --template                     Path to the CloudFormation template
      -tp    | --template-parameters          CloudFormation template parameters. Format is <key1>=<value1>;<key2>=<value2>
      -ts    | --template-substitutions       JSON based CloudFormation template substitutions. Format is <JSONPath>=<Substitution>;<JSONPath>=...

```
My understanding is that deploy-service creates a CloudFormation template so not sure how these would be used. Is it possible to create a CloudFormation template that contains multiple containers and then have this reference that template and then it would know not to create/update the template that already exists? 

Thanks again!

**Comment by ashishdhingra** [comment]
@mrsuau627 You may reference the file https://github.com/aws/aws-extensions-for-dotnet-cli/blob/master/src/Amazon.ECS.Tools/ECSDefinedCommandOptions.cs for the ECS defined command options. Also refer [DeployServiceCommand](https://github.com/aws/aws-extensions-for-dotnet-cli/blob/f0392ca5ac29e829b93695a71e1447c679cafc59/src/Amazon.ECS.Tools/Commands/DeployServiceCommand.cs#L23), it doesn't appear to use the template parameters.
