### ISSUE TITLE
Cannot set parameter

### ISSUE THREAD

**Issue by kentcb** [aws/aws-extensions-for-dotnet-cli#18]
I'm using version `2.1.4` of `Amazon.Lambda.Tools`. I have a parameter in my YAML template like this:

```yaml
Parameters:
  Environment:
    Type: "String"
```
But when I try and set it like this:
```
dotnet lambda deploy-serverless -t serverless.yaml --template-parameters Environment=whatever
```
I get this output:
```
Skipping passed in template parameter Environment because the template does not define that parameter
```
The same deployment works if I use `sam` directly at the CLI, and the parameter is passed through as expected.

**Comment by normj** [comment]
It's probably an issue with the YAML parsing. I'll take a look.

**Comment by normj** [comment]
I have a fix checked in for the next release which should go out early next week.

**Comment by normj** [comment]
Version 2.2.0 of Amazon.Lambda.Tools was just released with this fix. Also in the release was support for .NET Core 2.1 in Lambda.

**Comment by normj** [comment]
Closing as I believe this has been resolved. Feel free to reopen or create a new issue if the problem persists.
