### ISSUE TITLE
How can I enable JSON syntax validation for the AWS::Serverless::StateMachine type?

### ISSUE THREAD

**Issue by macfarmw** [aws/aws-extensions-for-dotnet-cli#180]
## The Question

I am using the AWS Toolkit for Visual Studio to create an AWS Serverless application. I found in the documentation that the type AWS::Serverless::StateMachine is one of the supported resource types for SAM templates. My serverless.template file uses JSON format because that it what was generated when I created the project in Visual Studio using the *AWS Serverless Application with Tests (.NET Core -C#)* project template. 
I have added a simple HelloWorld state machine using the documentation and the `dotnet lambda deploy-serverless` creates it successfully in AWS.

However, all of the properties for the StateMachine show as invalid with the red squiggly warnings.
![image](https://user-images.githubusercontent.com/10874510/128608352-acc78f68-7584-44f9-9bfb-c8d4f087cbc3.png)

Is there anything I can do to make the Visual Studio JSON editor recognize these properties?

### Environment

* Build Version:  AWS Toolkit 1.21.3.0 
* OS Info: Windows 10 
* Build Environment: Visual Studio 2019 16.10.0 
* Targeted .NET Platform:  .NET Core 3.1

---

This is a :question: general question

**Comment by macfarmw** [comment]
I realize that there is a differ repo for the AWS Toolkit, so I have posted this question over there. I'll leave it open here a little while in case there is some overlap with this repo.

**Comment by ashishdhingra** [comment]
Similar to https://github.com/aws/aws-sdk-net/issues/1811

**Comment by ashishdhingra** [comment]
Hi @macfarmw,

Good afternoon.

Looks like the issue has been fixed in the `AWS Toolkit for Visual Studio` version `1.24.0.0`:

<img width="882" alt="Screen Shot 2022-01-14 at 1 27 57 PM" src="https://user-images.githubusercontent.com/67916761/149587895-e7c50d97-94e9-4a98-abb3-d0ea6a2833e5.png">

Used the below template (taken from https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html) as reference:
```JSON
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Transform": "AWS::Serverless-2016-10-31",
  "Description": "An AWS Serverless Application.",
  "Resources": {
    "MySampleStateMachine": {
        "Type": "AWS::Serverless::StateMachine",
        "Properties": {
            "Definition": {
                "StartAt": "MyLambdaState",
                "States": {
                    "MyLambdaState": {
                        "Type": "Task",
                        "Resource": "arn:aws:lambda:us-east-1:123456123456:function:my-sample-lambda-app",
                        "End": true
                    }
                }
            },
            "Role": "arn:aws:iam::123456123456:role/service-role/my-sample-role",
            "Tracing": {
                "Enabled": true
            }
        }
    }

  },
  "Outputs": {
    }
}
```
Please verify the same at your end and confirm if this issue could be closed (also please close the related issue https://github.com/aws/aws-toolkit-visual-studio/issues/171).

Thanks,
Ashish

**Comment by macfarmw** [comment]
@ashishdhingra Thanks for the update. I won't be able to test and confirm this. I'm no longer working on the project or company where this was happening. It's pretty clear though based on your screen shot that it's fixed.
