### ISSUE TITLE
How to choose between the Amazon.Lambda.Tools or the SAM CLI?

### ISSUE THREAD

**Issue by macfarmw** [aws/aws-extensions-for-dotnet-cli#182]
## The Question

It appears that the Amazon.Lambda.Tools package overlaps with features of the SAM CLI. I picked Amazon.Lambda.Tools because it happened to be the first thing I found. What are some factors that can be used to decide between Amazon.Lambda.Tools or SAM CLI for dotnet projects? Are there are any clear advantages or disadvantages between two tools?

---

This is a :question: general question

**Comment by ashishdhingra** [comment]
Hi @macfarmw,

Good morning.

Thanks for posting guidance question.

As page [What is the AWS Serverless Application Model (AWS SAM)?](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/what-is-sam.html) documents AWS SAM CLI as a tool to build serverless applications that are defined by AWS SAM templates and provides commands that enable you to verify that AWS SAM template files are written according to the specification, invoke Lambda functions locally, step-through debug Lambda functions, package and deploy serverless applications to the AWS Cloud, and so on. 

[Amazon.Lambda.Tools](https://www.nuget.org/packages/Amazon.Lambda.Tools) adds commands to the dotnet cli to deploy AWS Lambda functions. When using .NET CLI to develop .NET applications, this extension adds functionality to deploy, invoke, list, delete, etc. Lambda functions to actual AWS environment.

Following articles provide good examples on how to develop Lambda functions in .NET and test locally using SAM CLI:
- [Developing .NET Core AWS Lambda functions](https://aws.amazon.com/blogs/compute/developing-net-core-aws-lambda-functions/)
- [Using .NET Core in AWS Lambda with SAM and building an Auto-Scaling Manager](https://dev.to/antoniofalcao/using-net-core-in-aws-lambda-with-sam-and-building-an-auto-scaling-manager-3gjc) 

Hope this helps.

Thanks,
Ashish
