### ISSUE TITLE
ECS log configuration argument is overwritten with awslogs defaults

### ISSUE THREAD

**Issue by alex-rfsmart** [aws/aws-extensions-for-dotnet-cli#184]
```
dotnet ecs deploy-service --container-log-configuration {json}
```
Command line argument is ignored and the default settings are applied instead.

This is where the command line configuration is added. Several lines later, the defaults overwrite what I have specified. I'm trying to use a firelens configuration. Also, there seems to be a naming mismatch between what you would find in a task definition vs what the argument is expecting. The log driver field is `containerPath` in the code and `logDriver` in the ECS task definition.

https://github.com/aws/aws-extensions-for-dotnet-cli/blob/f0392ca5ac29e829b93695a71e1447c679cafc59/src/Amazon.ECS.Tools/ECSUtilities.cs#L378-L390

https://github.com/aws/aws-extensions-for-dotnet-cli/blob/f0392ca5ac29e829b93695a71e1447c679cafc59/src/Amazon.ECS.Tools/ECSUtilities.cs#L564-L573

**Comment by ashishdhingra** [comment]
Hi @alex-rfsmart,

Good morning.

Thanks for reporting the issue. Please advise if it would be possible for you to share the sample JSON file for reproduction.

Thanks,
Ashish

**Comment by alex-rfsmart** [comment]
I have replace the private information with empty strings in the following json.

```
{
  "region": "us-east-1",
  "profile": "",
  "configuration": "Release",
  "image-tag": "",
  "docker-build-working-dir": "",
  "cluster": "",
  "launch-type": "FARGATE",
  "launch-subnets": "",
  "launch-security-groups": "",
  "assign-public-ip": false,
  "task-definition-name": "",
  "task-cpu": "512",
  "task-memory": "2048",
  "platform-version": "LATEST",
  "task-definition-task-role": "",
  "task-execution-role": "",
  "container-name": "",
  "container-port-mapping": "80:80",
  "container-environment-variables": "\"ASPNETCORE_ENVIRONMENT\"=\"Production\"",
  "skip-image-push": false,
  "cluster-service": "",
  "desired-count": 1,
  "deployment-minimum-healthy-percent": 50,
  "deployment-maximum-percent": 200,
  "elb-target-group": "",
  "elb-container-port": 80,
  "vstoolkit-deployment-mode": "DeployService",
  "container-log-configuration": "{\"containerPath\": \"awsfirelens\", \"options\": {\"delivery_stream\": \"LogStream\", \"region\": \"us-east-1\", \"Name\": \"firehose\"}}"
}
```

**Comment by ashishdhingra** [comment]
Appears to be reproducible. The JSON for task definition has the following `logConfiguration`:
```JSON
"logConfiguration": {
        "logDriver": "awslogs",
        "secretOptions": null,
        "options": {
          "awslogs-group": "/ecs/WebApplicationNETCLIECSTestIssue184/WebApplicationNETCLIECSTestIssue184",
          "awslogs-region": "us-east-2",
          "awslogs-stream-prefix": "ecs"
        }
```

Also refer `logDriver` option at https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_storage

**Comment by ashishdhingra** [comment]
Fixed in [Amazon.ECS.Tools 3.4.3](https://www.nuget.org/packages/Amazon.ECS.Tools/3.4.3)
