### ISSUE TITLE
Supporting Apple Silicon M1 ARM Architecture

### ISSUE THREAD

**Issue by timdinh** [aws/aws-extensions-for-dotnet-cli#192]
We get the following error when issuing the command `dotnet lambda` on Apple M1 machine

```
Failed to load /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.20/libhostpolicy.dylib, error: dlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.20/libhostpolicy.dylib, 0x0001): tried: '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.20/libhostpolicy.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/libhostpolicy.dylib' (no such file), '/usr/lib/libhostpolicy.dylib' (no such file)
An error occurred while loading required library libhostpolicy.dylib from [/usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.20]
```

The machine has the following dotnet SDKs and runtimes installed

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.0
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.100/

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  3.1.414 [/usr/local/share/dotnet/sdk]
  5.0.402 [/usr/local/share/dotnet/sdk]
  6.0.100 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.20 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.20 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

## Describe the Feature
Add support so that the command `dotnet lambda` run without error on Apple M1 machine

### Is your Feature Request related to a problem?
see above

### Describe alternatives you've considered
There are no solutions that we know of

## Additional Context
We have an ASPNET Core WebApi solution that we are publishing as a serverless to AWS.

### Environment
* MacOS Monterey
* dotnet 6.0
* Apple M1 arm64 architect

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change  

---

This is a :rocket: Feature Request

**Comment by timdinh** [comment]
I was able to follow the instruction at https://github.com/aws/aws-extensions-for-dotnet-cli/blob/master/CONTRIBUTING.md and create a working version. Thanks.

**Comment by normj** [comment]
I have tested the `Amazon.Lambda.Tools` in my Apple M1 machine and it works for me but I think that is because I have just .NET 6 installed. I suspect having the 3.1 SDK also installed is getting things confused because currently the shipped tool is targeting .NET Core 2.1 and the 3.1 is the closest match and is being used.

I'm in the process of pushing out a new version of the tool that will target .NET Core 3.1 and .NET 6 which should mean on your machine it will pick the .NET 6 version.

**Comment by ashishdhingra** [comment]
Waiting for .NET 6 target support on AWS .NET CLI extensions.

**Comment by normj** [comment]
I have pushed version 5.3.0 of the Lambda tool that adds a .NET 6 target framework for build. This should unblock M1 users with only the ARM version of .NET 6 installed.

**Comment by ashishdhingra** [comment]
> I have pushed version 5.3.0 of the Lambda tool that adds a .NET 6 target framework for build. This should unblock M1 users with only the ARM version of .NET 6 installed.

@timdinh Please upgrade to latest version and verify if the issue is resolved.

**Comment by timdinhdotcom** [comment]
@normj @ashishdhingra Thanks guys, version 5.3.0 works now.
