### ISSUE TITLE
dotnet eb package / deploy from package command?

### ISSUE THREAD

**Issue by abbotware** [aws/aws-extensions-for-dotnet-cli#2]
Seems that you can't create a package (and then deploy later) using the eb tools like you can create a lambda package.

Is there are reason why not? 

It seems like it should be fairly simple to break up 'deploy-environment' into these two steps so it can be better suited for CI / Build systems.

**Comment by normj** [comment]
No reason its not there just needs to be added. 

Question about how this would work though. The deployment bundle sent to Beanstalk is a zip file that contains a manifest file which configures IIS, like the IIS App Path, and then all of the application bits which were collected using `dotnet publish`.

I can see how the IIS settings would not be known at the packaging state and should be set during the deployment state. So what I'm thinking I should do is assume the user has collected their application bits using `dotnet publish`. Then either the directory or the zip of `dotnet publish` is passed into `deploy-environment` where the deployment bundle is created with the manifest. Would that work for you?

**Comment by abbotware** [comment]
Well ideally, i just want a 2 step process so the 'build' (and zip) is separate from the 'deploy'

I suggest the following:

1. dotnet eb **package** -c Release  -cfg package.cfg.json
2. dotnet eb **deploy-environment-package**  -cfg deploy.cfg.json  

I suggest new commands/cfgs only because certain parameters only make sense for 'packaging' and others make sense for 'deploying'.  This makes it clear what parameters are required for each step and wont break existing functionality.

Wasn't aware of the manifest file. Does lambda require one too? (my lambda.zips don't seem to have one)

That could mean two ways to implement:

Option A
step 1 creates a zip + manifest
step 2 deploys the zip

Option B
step 1 creates a zip only
step 2 creates a manifest, adds it to the zip, and then deploys 

Option B seems like it could be more 'useful' since you don't need to create multiple zips for different deployment scenarios.  

Either way the functionality would then be similar to what I currently can be do with Lambda:

1. dotnet lambda package -c Release -o ..\PATH\To\package.zip
2. dotnet lambda deploy-function -cfg cfg.json  (cfg has package source ..\PATH\To\package.zip)

**Comment by abbotware** [comment]
been a few months... no updates on this?

**Comment by abbotware** [comment]
i created a PR (_work in progress_) but I don't think this feature is that hard and I am currently redoing my build pipelines (after 1 year) and will now need this feature

**Comment by normj** [comment]
This was released as part of version 3.1.0 of Amazon.ElasticBeanstalk.Tools
