### ISSUE TITLE
dotnet lambda function-deploy fails after updating to 2.1.302

### ISSUE THREAD

**Issue by Alex-BrickBridgeConsulting** [aws/aws-extensions-for-dotnet-cli#20]
I just updated .Net Core (2.1.302) and now I cannot deploy functions to Lambda. I am trying to deploy a 2.0 function and receive this error:
_Version for package `Amazon.Lambda.Tools` could not be resolved._ 

I have verified that the tools are installed under ~/.nuget. Thanks for any help.

I am on Mac OS 10.13.5.

_Alex

**Comment by normj** [comment]
I just verified on my Mac with no problems. Have you tried doing a **dotnet restore** in the project directory to regenerate the project.assets.json file?

**Comment by Alex-BrickBridgeConsulting** [comment]
Thanks, that worked.
