### ISSUE TITLE
Serverless MetaData / DockerBuildArgs are not being sent as --build-arg to docker

### ISSUE THREAD

**Issue by danyhoron** [aws/aws-extensions-for-dotnet-cli#201]
## Description

I have a serverless json file to deploy a .net 6 lambda function.
I configured my Dockerfile to accept some build arguments.
In the serverless metadata section I have the following config:
```json
{
  "Metadata": {
    "Dockerfile": "Dockerfile",
    "DockerContext": ".",
    "DockerTag": "",
    "DockerBuildArgs": {
      "PROJECT_PATH": "/src/path-to/project",
      "PROJECT_FILE": "project.csproj"
    }
  }
}
```
when I run: `dotnet lambda deploy-serverless -t serverless.json --profile <my-profle> -sb <my-s3-bucket> -sn <my-stack-name>`
I get the logs below.
`--build-arg` is missing from the `docker build` command
### Logs

```
... invoking 'docker build', working folder '/Users/<redacted>/Work/Development/my-project/., docker file /Users/<redacted>/Work/Development/my-project/Dockerfile, image name my-project:latest'
... docker build -f "/Users/<redacted>/Work/Development/my-project/Dockerfile" -t myproject:latest .
```
### Environment

* Build Version: `5.1.4`
* OS Info: `macOS Monterey`
* Build Environment: `VSCode + Terminal`
* Targeted .NET Platform:  6.0

## Resolution
- [ ] :wave: I can/would-like-to implement a fix for this problem myself

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Could be related to https://github.com/aws/aws-extensions-for-dotnet-cli/issues/198.

**Comment by danyhoron** [comment]
It behaves the same on 5.2.0 and on 5.1.4

**Comment by ashishdhingra** [comment]
> It behaves the same on 5.2.0 and on 5.1.4

@danyhoron Please advise if it was working in any of the earlier versions. If not, then this is most likely a feature request.

**Comment by danyhoron** [comment]
I couldn't find any official documentation on the Metadata property

**Comment by ashishdhingra** [comment]
[DockerCLIWrapper](https://github.com/aws/aws-extensions-for-dotnet-cli/blob/cdd490450e0407139d49248d94a4a899367e84df/src/Amazon.Common.DotNetCli.Tools/DockerCLIWrapper.cs#L24) supports parring additional options to the `docker build`. Not sure if this is similar to `DockerBuildArgs`. [SAM: Building applications](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-using-build.html) specifies `DockerBuildArgs` as the supported metadata parameter. [SAM CLI code](https://github.com/jonife/aws-sam-cli/blob/6a21402fe2cf37b7342633b54c9a02275677a657/samcli/lib/build/app_builder.py#L273) expects it to be of type dictionary. Refer [Set build-time variables (--build-arg)](https://docs.docker.com/engine/reference/commandline/build/#set-build-time-variables---build-arg).

This appears to be a feature request. Needs discussion with the team.

**Comment by ashishdhingra** [comment]
Discussed with the team. Good candidate for feature request. 

Just for reference: https://github.com/aws/aws-extensions-for-dotnet-cli/blob/master/src/Amazon.Lambda.Tools/TemplateProcessor/TemplateProcessorManager.cs#L289

**Comment by ashishdhingra** [comment]
Support for `DockerBuildArgs` is released in [Amazon.Lambda.Tools version 5.4.3](https://www.nuget.org/packages/Amazon.Lambda.Tools/5.4.3).
