### ISSUE TITLE
Lambda packaging with a function layer

### ISSUE THREAD

**Issue by anuradharajan** [aws/aws-extensions-for-dotnet-cli#202]
## Description

Getting this error when trying to package a dotnet core lambda with a layer

dotnet lambda package --region us-east-1 --function-layers arn:aws:lambda:us-east-1:********:layer:**************:9 --configuration release --framework netcoreapp3.1 --output-package output

Inspecting Lambda layers for runtime package store manifests
... arn:aws:lambda:us-east-1:*************:layer:**********:9: Skipped, does not contain a layer description manifest

## Reproduction Steps

1. Created a layer and uploaded packages.zip
2. packages.zip contains store folder with all packages and a artifact.xml
3. Getting an error when trying to package a lambda referencing the layer created

### Environment

* Build Version: 
* OS Info: 
* Build Environment: 
* Targeted .NET Platform:  .net core 3.1

## Resolution
- [ ] :wave: I can/would-like-to implement a fix for this problem myself

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @anuradharajan,

Good afternoon.

Could you please share the sample code solution and all the steps you took, to reproduce the issue? The error you are getting is pretty vague and doesn't help much here to provide any guidance.

Thanks,
Ashish

**Comment by anuradharajan** [comment]
> Hi @anuradharajan,
> 
> Good afternoon.
> 
> Could you please share the sample code solution and all the steps you took, to reproduce the issue? The error you are getting is pretty vague and doesn't help much here to provide any guidance.
> 
> Thanks, Ashish

Hi Ashish

The problem I am facing here is with the dotnet lambda package cli. I have mentioned the CLI command above. The package command works fine when there is no layers argument. But when I add the layer argument in the command, it tries to inspect the layer and complains that there is no layer description manifest. 

My layer does have the manifest (artifact.xml) which has the list of all Nuget packages in the layer. Do you know what is that the CLI is looking for when we get this error - 'No layer description manifest'

I saw this code in the CLI 

var p = ParseLayerVersionArn(arn);
                    var getLayerResponse = await lambdaClient.GetLayerVersionAsync(new GetLayerVersionRequest { LayerName = p.Name, VersionNumber = p.VersionNumber });

                    LayerDescriptionManifest manifest;
                    if (!LambdaUtilities.AttemptToParseLayerDescriptionManifest(**getLayerResponse.Description**, out manifest))
                    {
                        logger.WriteLine($"... {arn}: Skipped, does not contain a layer description manifest");
                        continue;
                    }

Looks like if this layer.Description is empty or if its not a json - it throws the error??

**Comment by anuradharajan** [comment]
All set with this
