### ISSUE TITLE
task-definition-volumes and container-mount-points is not working

### ISSUE THREAD

**Issue by garyzhuosim** [aws/aws-extensions-for-dotnet-cli#223]
### Describe the bug

When set these two parameter, it doesn't work

### Expected Behavior

It should be working

### Current Behavior

These two parameter is ignored

### Reproduction Steps

When deploy ecs service using `dotnet ecs deploy-service` command, these two parameter is not working

### Targeted .NET platform

.Net Core 3.1 and .Net 6

### CLI extension version

3.5.1

### Environment details (OS name and version, etc.)

Windows 10

**Comment by ashishdhingra** [comment]
Customer submitted PR needs review.
