### ISSUE TITLE
How Do You "dotnet lambda package-ci" for arm64?

### ISSUE THREAD

**Issue by hounddog22030** [aws/aws-extensions-for-dotnet-cli#228]
### Describe the issue

We are trying to use `dotnet lambda package-ci` to package for arm64

`dotnet lambda package --help` documentation shows `-farch | --function-architecture        The architecture of the Lambda function. Valid values: x86_64 or arm64. Default is x86_64`

Yet, `dotnet lambda package-ci --help` shows no switch for architecture.  

We have issued:

1. `dotnet lambda package-ci ... --runtime linux-arm64`
2. `dotnet lambda package-ci  ... --function-architecture arm64 --msbuild-parameters "--arch linux-arm64"`
3. `dotnet lambda package-ci ... --function-architecture arm64`

These do not produce any arm64 results, all produce the publish command as something like `dotnet publish --output "/codebuild/output/src054284391/src/bbapi/WebApi/./bin/Release/net6.0/publish" --configuration "Release" --framework "net6.0" /p:GenerateRuntimeConfigurationFiles=true --runtime linux-x64 --self-contained false` or an error

### Links

https://github.com/aws/aws-extensions-for-dotnet-cli

**Comment by ashishdhingra** [comment]
Hi @hounddog22030,

Good morning.

Thanks for reporting the issue. Upon investigating further:
- The `--function-architecture` for `dotnet lambda package` command sets the **[--runtime](https://github.com/aws/aws-extensions-for-dotnet-cli/blob/01735e390f52255c8c4bb3759c4643c45156d8e8/src/Amazon.Lambda.Tools/LambdaDotNetCLIWrapper.cs#L219)** argument if it is not already included as part of MSBuild parameters. For `--function-architecture` set as `arm64`, the `--runtime` argument is set to `linux-arm64`.
- The `dotnet lambda package-ci` command doesn't appear to have `--function-architecture` as one of the supported parameters as evident from [PackageCICommandOptions](https://github.com/aws/aws-extensions-for-dotnet-cli/blob/01735e390f52255c8c4bb3759c4643c45156d8e8/src/Amazon.Lambda.Tools/Commands/PackageCICommand.cs#L26).

For `dotnet lambda package-ci` command, the workaround is to specify `--msbuild-parameters` with value `--runtime linux-arm64`. In other words, the command would look like `dotnet lambda package-ci ... --msbuild-parameters "--runtime linux-arm64"`. Please let me know if it works for you.

Thanks,
Ashish

**Comment by hounddog22030** [comment]
>>Please let me know if it works for you.<<

Yep.  Thanks!  Do you want me to do a PR to add that to the documentation?

**Comment by ashishdhingra** [comment]
> > > Please let me know if it works for you.<<
> 
> Yep. Thanks! Do you want me to do a PR to add that to the documentation?

@hounddog22030 I don't think this workaround should be a part documentation update. This should instead be discussed with team on the missing `--function-architecture` for `dotnet lambda package-ci` command. I would label this is a `bug` so that it could be discussed with the team.

**Comment by normj** [comment]
@hounddog22030 For the `package-ci` command the tool uses the CloudFormation to determine what architecture to package the function for.  So if you want to use ARM then set the `Architectures` property on the function.

```json
    "Get": {
      "Type": "AWS::Serverless::Function",
      "Properties": {
        "Handler": "AWSServerless96::AWSServerless96.Functions::Get",
        "Runtime": "dotnet6",
        "Architectures" : ["arm64"],
        "CodeUri": "",
        "MemorySize": 256,
        "Timeout": 30,
        "Role": null,
        "Policies": [
          "AWSLambdaBasicExecutionRole"
        ],
        "Events": {
          "RootGet": {
            "Type": "Api",
            "Properties": {
              "Path": "/",
              "Method": "GET"
            }
          }
        }
      }
    }
```

**Comment by ashishdhingra** [comment]
Thanks @normj for the inputs.

@hounddog22030 Please refer existing example template https://github.com/aws/aws-extensions-for-dotnet-cli/blob/master/testapps/TestServerlessWebApp/serverless-arm.template as reference. If this helps, kindly confirm if this issue could be closed.

**Comment by hounddog22030** [comment]
> @hounddog22030 For the `package-ci` command the tool uses the CloudFormation to determine what architecture to package the function for. So if you want to use ARM then set the `Architectures` property on the function.
> 
> ```json
>     "Get": {
>       "Type": "AWS::Serverless::Function",
>       "Properties": {
>         "Handler": "AWSServerless96::AWSServerless96.Functions::Get",
>         "Runtime": "dotnet6",
>         "Architectures" : ["arm64"],
>         "CodeUri": "",
>         "MemorySize": 256,
>         "Timeout": 30,
>         "Role": null,
>         "Policies": [
>           "AWSLambdaBasicExecutionRole"
>         ],
>         "Events": {
>           "RootGet": {
>             "Type": "Api",
>             "Properties": {
>               "Path": "/",
>               "Method": "GET"
>             }
>           }
>         }
>       }
>     }
> ```

I have confirmed this is as @normj describes.  _Didn't see that coming ;-)_  Do you want me to do a PR to document that?

**Comment by normj** [comment]
@hounddog22030 I think a doc PR makes sense. I assume we are talking on the [README](https://github.com/aws/aws-extensions-for-dotnet-cli/#package-ci). Also I realized the help on `dotnet lambda package-ci --help` is pretty bad. If you want to make PR to improve it that would be great https://github.com/aws/aws-extensions-for-dotnet-cli/blob/master/src/Amazon.Lambda.Tools/Commands/PackageCICommand.cs#L15

**Comment by hounddog22030** [comment]
PR:  https://github.com/aws/aws-extensions-for-dotnet-cli/pull/229

**Comment by ashishdhingra** [comment]
> PR: #229
> 
> I didn't dive into https://github.com/aws/aws-extensions-for-dotnet-cli/blob/master/src/Amazon.Lambda.Tools/Commands/PackageCICommand.cs#L15 (yet)

@hounddog22030 Somehow I do not see any concrete changes in the PR https://github.com/aws/aws-extensions-for-dotnet-cli/pull/229.

**Comment by hounddog22030** [comment]
> I think a doc PR makes sense

Per @normj, I did a "doc PR".  Do you not see

> > PR: #229
> > I didn't dive into https://github.com/aws/aws-extensions-for-dotnet-cli/blob/master/src/Amazon.Lambda.Tools/Commands/PackageCICommand.cs#L15 (yet)
> 
> @hounddog22030 Somehow I do not see any concrete changes in the PR #229.

Sorry, I think the push failed.  Please check again, I've pushed and verified it's there now.

**Comment by normj** [comment]
Thanks for the doc PR @hounddog22030. I have merged in the changes.
