### ISSUE TITLE
Parameterizing swagger file

### ISSUE THREAD

**Issue by RidhwanDev** [aws/aws-extensions-for-dotnet-cli#24]
Hi,

My aim is to have multiple batch files which would deploy my serverless application to different environments (e.g dev/test/live). It is worth mentioning that these environments all live on separate aws accounts. The reason I need to use the swagger files is to set up CORS and Cognito Authentication. I realise CORS can be set up directly in the sam template, however Cognito Authentication cant. I would also like the functionality of using multiple user pools which using swagger allows me to do.

So far, I have created batch files that can deploy to different environments by using 
`dotnet lambda deploy-serverless --profile {profile} --s3-bucket {bucket} --stack-name {stack} --region {region}`

By not including the swagger file, this works fine to just deploy to different environments when I need to. 
However I need to set up Cors and Cognito Authentication manually via aws console. Also the console doesn't allow multiple user pool cognito authentication so that bit I can't do.

How can I parameterize the swagger file to pass in different values for different environments when running my batch files?
What parts of the swagger file is actually REQUIRED for the swagger to still work? (What bits can I strip out basically)

Thanks
Ridhwan

**Comment by normj** [comment]
This is more of a CloudFormation question than a .NET Core Lambda function. Sorry I'm not enough of a CloudFormation expert to answer this question. You should try the CloudFormation [forums](https://forums.aws.amazon.com/forum.jspa?forumID=92) which might be better to answer this question.
