### ISSUE TITLE
dotnet lambda deploy-serverless s3 upload timeouts

### ISSUE THREAD

**Issue by sudsy** [aws/aws-extensions-for-dotnet-cli#25]
Hi There,

I am receiving timeouts whenever I try to publish from the cli using` dotnet lambda deploy-serverless`

Error uploading to XXX in bucket YYY: A task was canceled.

I don't receive this error when publishing from Visual Studio.

Anecdotally it seems to timeout after 2 minutes.

Is there a setting somewhere that I can adjust to increase this timeout?

It's a problem because I am deploying files that need the executable bit set on them and the visual studio tool can't deal with that. I really need to deploy it from a linux machine.

I'd really appreciate any guidance or workarounds you can offer because this has blocked me on this project at the moment.

I tried creating the zip on linux and deploying with the --pac option but that didn't work either.

**Comment by normj** [comment]
How long does it take to deploy in VS even when the package doesn't work because of the executable bit? Are you behind a proxy when you use the command line? I'm wondering if the command line is failing to ever connect.

**Comment by sudsy** [comment]
A quick update. 

I loaded my project into AWS codebuild and tried a deploy there and everything works just fine with the faster connection. I guess this rules out most other causes and pins the issue down to a problem while running on slow connections.

**Comment by matthiasotto** [comment]
Same problem here. I tried reducing the size of some of my packages but some are still failing.

**Comment by sudsy** [comment]
I can confirm that this is still an issue in the 3.1.2 version of the aws.lambda.tools .

I created a new project which has a 19MB deployment package and it dies after reaching about 50% or 60%. I'm sure I can work around the bug by uploading my project to somewhere with a faster connection but it is a pain. I timed the upload and from the point where it says Uploading to S3 through to when it fails is 1 minute 40 seconds. I am guessing there must be an absolute limit for the upload of 90 seconds.

**Comment by stevieTheCoder** [comment]
I also have issues uploading to S3 via the CLI, through VS the upload completes successfully.  I would add I am behind a corporate proxy and am using CNTLM.

**Comment by mrwcjoughin** [comment]
I am having the same issues as of today, and I am on Visual Studio for Mac so I can't use the AWS Visual Studio extension as its not available for Visual Studio for Mac.
AWS please advise urgently!

**Comment by andreas271828** [comment]
I have the same issue on Linux. Amazon Lambda Tools for .NET Core applications (3.2.3).
Uploading the same file with aws s3 cp is working fine.

**Comment by seanferons** [comment]
Any updates on this? We have a stack in the China Ningxia region and the connection speed can be pretty slow most days, so our deploys are constantly timing out during the s3 upload. If we could override the timeout length with a parameter the deploys would go through fine.

**Comment by ashishdhingra** [comment]
Hi @sudsy,

Good morning.

I was going through the issue backlog and came across this one. I'm not sure if this is an issue in CLI extensions. Please let me know if this still an issue or if this could be closed. 

Thanks,
Ashish

**Comment by sudsy** [comment]
Seems to be fixed now. I simulated a slow connection and was able to get to 30% upload on a large file over 4 minutes. Previously it timed out at 90 seconds.
