### ISSUE TITLE
Skipped, error inspecting layer. Invalid Layer name

### ISSUE THREAD

**Issue by fracampit** [aws/aws-extensions-for-dotnet-cli#255]
### Describe the bug

I have the following layer versions:

```
arn:aws:lambda:eu-west-2:763336740511:layer:capabilities-assets:2
arn:aws:lambda:eu-west-2:763336740511:layer:capabilities-assets:1
```

When I run `dotnet lambda package --project-location $PROJECT_LOCATION  --function-layers $LAMBDA_LAYER_ARN  -o publish/$CI_PIPELINE_ID.zip`, where `$LAMBDA_LAYER_ARN` is either `arn:aws:lambda:eu-west-2:763336740511:layer:capabilities-assets:2` or `arn:aws:lambda:eu-west-2:763336740511:layer:capabilities-assets:1`, I get the following error:

```
Inspecting Lambda layers for runtime package store manifests
arn:aws:lambda:eu-west-2:763336740511:layer:capabilities-assets:2: Skipped, error inspecting layer.
Invalid Layer name: arn:aws:lambda:eu-west-2:763336740511:layer:capabilities-assets
```

### Expected Behavior

```
Inspecting Lambda layers for runtime package store manifests
... arn:aws:lambda:eu-west-2:763336740511:layer:capabilities-assets:2: Downloaded package manifest for runtime package store layer
```

### Current Behavior

```
Inspecting Lambda layers for runtime package store manifests
arn:aws:lambda:eu-west-2:763336740511:layer:capabilities-assets:2: Skipped, error inspecting layer.
Invalid Layer name: arn:aws:lambda:eu-west-2:763336740511:layer:capabilities-assets
```

### Reproduction Steps

n/a

### Targeted .NET platform

.NET 6, linux-x64

### CLI extension version

Amazon Lambda Tools for .NET Core applications (5.6.2)

### Environment details (OS name and version, etc.)

.NET 6, linux-x64

**Comment by fracampit** [comment]
Please let me if you need more details about the issue.

**Comment by ashishdhingra** [comment]
Hi @fracampit,

Good morning.

Thanks for reporting the issue. The error is possibly thrown during call to [IAmazonLambda.GetLayerVersionAsync()](https://github.com/aws/aws-extensions-for-dotnet-cli/blob/ceba1c22434bf4ac0b5b60f4158178e5f0858aaf/src/Amazon.Lambda.Tools/LambdaUtilities.cs#L545). I suspect that the region determined in the environment where `dotnet lambda package` is being executed is different from `eu-west-2` (region for the layers `arn:aws:lambda:eu-west-2:763336740511:layer:capabilities-assets:2` or `arn:aws:lambda:eu-west-2:763336740511:layer:capabilities-assets:1`).

Could you please share the following:
- ARN of the layer that is working for you?
- Try using `dotnet lambda package` with the `--region` parameter value `eu-west-2` (e.g. `dotnet lambda package --region eu-west-2 --project-location $PROJECT_LOCATION --function-layers $LAMBDA_LAYER_ARN -o publish/$CI_PIPELINE_ID.zip` and see if it works for you.

Thanks,
Ashish

**Comment by fracampit** [comment]
@ashishdhingra Thanks for the suggestion, that was it. 

The script was running in an environment that had the AWS_DEFAULT_REGION set to eu-west-1.
I have added a script that extracts the region from the arn:
`region=$(echo "$arn" | cut -d':' -f4)`

Providing the region extracted from the arn explicitly fixed the issue.
