### ISSUE TITLE
Bug: Publish optimization uses a hardcoded runtime linux-x64

### ISSUE THREAD

**Issue by derwasp** [aws/aws-extensions-for-dotnet-cli#26]
[LambdaDotNetCLIWrapper.cs](https://github.com/aws/aws-extensions-for-dotnet-cli/blob/92c7a3d91ad5167d82949c88130c03335fffa18b/src/Amazon.Lambda.Tools/LambdaDotNetCLIWrapper.cs#L97) has the following optimization, which is supposed to make the resulting zip smaller:

```csharp
                // If you set the runtime linux-x64 it will trim out the Windows and Mac OS specific dependencies but Razor view precompilation
                // will not run. So only do this packaging optimization if there are no Razor views.
                if (Directory.GetFiles(fullProjectLocation, "*.cshtml", SearchOption.AllDirectories).Length == 0)
                {
                    arguments.Append(" -r linux-x64 --self-contained false /p:PreserveCompilationContext=false");
                }
```

However, if one has a dependency on some native libraries using nuget packages and such a dependency package has a bunch of monikers and not only `linux` or `linux-x64`, but e.g. `rhel-x64`, the resulting output is unusable, since the publish result will contain a wrong library.
An example of such a package would be [LibGit2Sharp.NativeBinaries](https://www.nuget.org/packages/LibGit2Sharp.NativeBinaries/):

![image](https://user-images.githubusercontent.com/10754345/44299186-9414a880-a2f1-11e8-8496-5f9b639521cc.png)

**Temporary workaround**:

~Add an empty `.cshtml` file and a dependency to `Microsoft.AspNetCore.Razor` so the if in the optimization above is ignored.~

**Comment by normj** [comment]
Interesting. I'll take a look to see how we can better handle this.

**Comment by derwasp** [comment]
@normj well, my PR worked ;) I even have a test there!

**Comment by derwasp** [comment]
Update: The workaround doesn't actually work. I crossed it out in the description.
@normj is there a reason my PR is not a good solution? According to what I see, this is how things sort of worked before. But you had a manual parser that started with a rhel RID.

**Comment by normj** [comment]
Nothing wrong with the PR. I have the PR staged with the next release. I'm going to close this and use the https://github.com/aws/aws-extensions-for-dotnet-cli/pull/29 to track it.
