### ISSUE TITLE
Serverless application CI/CD pipeline

### ISSUE THREAD

**Issue by nirajvbhatt** [aws/aws-extensions-for-dotnet-cli#28]
Hi,
I am successfully using AWS Serverless Application as a mobile backend. We are still in DEV stage and it's so far so good.
I need some help setting up CI/CD pipeline. We are using GitHub for source repository.

I have a dotnet serverless aplication in .NET Core 2.1 environment to deploy multiple lambda functions.
I have cloudformation project that contains 2 templates 1)  Cognito user pools and roles 2) DynamoDB
I have attached an image showing my current setup in .NET environment. 
![awsarchitecture](https://user-images.githubusercontent.com/29375016/44324386-dc21ff80-a498-11e8-8445-f337d55ef29a.PNG)

I want to set up a codepipeline with source as Git so that
1) Any changes in above solution triggers the build
2) I want to deploy separate DEV/TESTING/UAT environment. My templates already takes these stages as input parameter to templates and create different resources.
3) How do I provide static stage variable values for 3 environment? For example, if I make some change, I want to deploy that change to DEV/TESTING etc. However I want to use same templates in all 3 environments but having different environment values. So should I create 3 new Git branches? If yes, how do I provide different input value to templates in these 3 branches?
4) Can I refer to any sample that mentions what should be the contents of serverless.template and build.yaml file for the CI/CD Pipeline? 

Thanks in advance.

**Comment by normj** [comment]
The short answer is you would have one template that is parameterized for the stage. Then have separate json files for each stage that contains the parameter values for that stage. When you setup the pipeline you can set the template configuration to that stage's json file.

This GitHub repo is Node.js based but you might find it helpful. https://github.com/aws-samples/aws-serverless-samfarm

If I can find time I'll try and give a more detail explanation but I didn't want to go answered waiting till I had time for a deeper answer.

**Comment by nirajvbhatt** [comment]
Hi @normj ,
Thank You very much for your reply. I am still struggling to set this up.
I am trying to follow https Building a serverless pipeline document (//docs.aws.amazon.com/lambda/latest/dg/build-pipeline.html) and trying to work it out for .net core 2.1.
I am able to setup basic Pipeline but without environment variables. However Codebuild still throws an error:
After following all steps, I am getting AWS COdeBuild error:
[Container] 2018/08/23 06:44:07 Waiting for agent ping
[Container] 2018/08/23 06:44:10 Waiting for DOWNLOAD_SOURCE
[Container] 2018/08/23 06:44:11 Phase is DOWNLOAD_SOURCE
[Container] 2018/08/23 06:44:11 CODEBUILD_SRC_DIR=/codebuild/output/src795065254/src
[Container] 2018/08/23 06:44:11 Phase complete: DOWNLOAD_SOURCE Success: false
[Container] 2018/08/23 06:44:11 Phase context status code: YAML_FILE_ERROR Message: YAML file does not exist

aws cloudformation package command doesn't really put output-template-file outputserverless.yaml file in my S3 bucket so clearly this command didn't work. Since I have serverless dotnet application, I have serverless.template file that defines all the resources however the document mentions a yaml file, so I think that's where my mistake is however I am not sure how to proceed in this case.  

My buildspec.yaml file:
My buildspec.yml file:
version: 0.2
phases:
  pre_build:
    commands:
      - pip install --upgrade awscli
  build:
    commands:
      - dotnet restore
      - dotnet build
  install:
    commands:
      - aws cloudformation package --template-file serverless.template --s3-bucket bha-codebuild-deployment-artifacts
                                   --output-template-file outputserverless.yaml
artifacts:
  type: zip
  files:
    - serverless.template
    - outputserverlesstemplate.yaml


Could you please give me a pointer on where I am going wrong?

**Comment by normj** [comment]
Here is a webinar I did a few months back for .NET Core Lambda and CI/CD that might help. Skip ahead about 27 minutes in to get to the CI/CD content.

https://youtu.be/IBeqDaMDjf0?t=1633

In my webinar I used the command `dotnet lambda package-ci` instead of `aws cloudformation package` because it takes care of building the .NET Core project into the Lambda package bundles and then does the same thing as `aws cloudformation package`. The `aws cloudformation package` doesn't have any knowledge on how to create the .NET Core Lambda package bundle.

Serverless.template is usually a JSON document unless you have converted it to YAML. So I suspect the `aws cloudformation package` command is not liking the fact you are taking a JSON as input and asking for YAML as output. Set output template to file with the json extension. The same is true if you use the `dotnet lambda package-ci` command.

**Comment by nirajvbhatt** [comment]
Hi @normj ,
Thank You for ur reply and input, I am trying to follow steps mentioned in webinar. 
I changed my buildspec.yml as below:
`version: 0.2
phases:
  pre_build:
    commands:
      - pip install --upgrade awscli
  build:
    commands:
      - dotnet restore
  install:
    commands:
      - dotnet lambda package-ci --s3-bucket bha-codebuild-deployment-artifacts --output-template updated-serverless.template.json
artifacts:
  files:
    - updated-serverless.template.json
  discard-paths: yes`

I am getting error in package-ci command. following is the build logs from codebuild:
[Container] 2018/09/02 22:46:36 Entering phase INSTALL
[Container] 2018/09/02 22:46:36 Running command dotnet lambda package-ci --s3-bucket bha-codebuild-deployment-artifacts --output-template updated-serverless.template.json
No executable found matching command "dotnet-lambda"

[Container] 2018/09/02 22:46:43 Command did not exit successfully dotnet lambda package-ci --s3-bucket bha-codebuild-deployment-artifacts --output-template updated-serverless.template.json exit status 1
[Container] 2018/09/02 22:46:43 Phase complete: INSTALL Success: false
[Container] 2018/09/02 22:46:43 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: dotnet lambda package-ci --s3-bucket bha-codebuild-deployment-artifacts --output-template updated-serverless.template.json. Reason: exit status 1

**Comment by nirajvbhatt** [comment]
Hi @normj ,
After rearranging pre build and build environment and removing install phase, as well as mentioning --template with json extension seems to be working. 
One question, how do include private nuget packages here? 
dotnet restore fails due to not able to restore private nuget package.
error NU1101: Unable to find package AWSHelper. No packages exist with this id in source(s): nuget.org [/codebuild/output/src640191078/src/github.com/***/***.sln]

Thanks.

**Comment by tamoj32** [comment]
In the webinar, it's using dotnet lambda to deploy package which uses Amazon.Lambda.Tools for 2.0. For .netcore 2.1 Amazon.Lambda.Tools will be installed globally. I have tried install it global but do not know how to set the path. any help?
=====================
Tools directory '/root/.dotnet/tools' is not currently on the PATH environment variable.
If you are using bash, you can add it to your profile by running the following command:

cat << \EOF >> ~/.bash_profile
# Add .NET Core SDK tools
export PATH="$PATH:/root/.dotnet/tools"
EOF

You can add it to the current session by running the following command:

export PATH="$PATH:/root/.dotnet/tools" 
=====================


version: 0.2
phases:
    install:
        commands:
            dotnet tool install -g Amazon.Lambda.Tools
    pre_build:
        commands:
            dotnet restore
    build:
        commands:
        - cd Utility
        - dotnet lambda package-ci --s3-bucket utility-s3 --output-template updated-serverless.template
artifacts:
    files:
    - Utility/updated-serverless.template
    discard-paths: yes

**Comment by normj** [comment]
@tamoj32 I'm working with the CodeBuild team to get ~/.dotnet/tools added to the path. They merged my [PR](https://github.com/aws/aws-codebuild-docker-images/pull/118) and it should take affect the next time they refresh the images.

**Comment by normj** [comment]
Sorry this happen a couple weeks ago but forgot to update the issue. The .NET Core 2.1 CodeBuild image has been updated to include the .NET Core Global Tools install directory into the PATH. So the Global Tools will be available right after installing them.

**Comment by niraj-bpsoftware** [comment]
Seems like still the issue exists, however aws.lambda.tools is installed. 
My codebuild logs:
[Container] 2019/02/07 23:43:43 Entering phase INSTALL
[Container] 2019/02/07 23:43:43 Running command dotnet tool install -g Amazon.Lambda.Tools
Tools directory '/root/.dotnet/tools' is not currently on the PATH environment variable.
If you are using bash, you can add it to your profile by running the following command:
 cat << \EOF >> ~/.bash_profile
# Add .NET Core SDK tools
export PATH="$PATH:/root/.dotnet/tools"
EOF
 You can add it to the current session by running the following command:
 export PATH="$PATH:/root/.dotnet/tools"
 You can invoke the tool using the following command: dotnet-lambda
Tool 'amazon.lambda.tools' (version '3.1.2') was successfully installed.
