### ISSUE TITLE
Extensions CLI publishes beanstalk environments with IMDSv1 enabled

### ISSUE THREAD

**Issue by shruti0085** [aws/aws-extensions-for-dotnet-cli#290]
### Describe the feature

Creating an issue here to track https://github.com/aws/aws-toolkit-visual-studio/issues/359 on the Visual Studio Toolkit.
The Visual Studio Toolkit leverages the AWS Extensions for Dotnet CLI to power some of the publish experiences including legacy beanstalk deploy support, so any changes to behavior will have to originate in this repository.

Beanstalk environments deployed using the CLI creates environment with IMDSv1 enabled instead of IMDSv2 which is now recommended by AWS.

### Use Case

Snippet from the original issue
IMDSv1 has been superseded by IMDSv2 and AWS is suggesting to upgrade to it everywhere, since IMDSv2 is inherently more secure. I noticed that when publishing applications with AWS Toolkit to Elastic Beanstalk, the EC2 instances have the IMDSv1 property activated.

### Proposed Solution

Support creating IMDSv2 enabled beanstalk environments

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Targeted .NET platform

Unavailable

### Environment details (OS name and version, etc.)

Windows

**Comment by ashishdhingra** [comment]
There is a related issue for .NET Deploy tool as well.

**Comment by ashishdhingra** [comment]
[Amazon.ElasticBeanstalk.Tools version 4.4.0](https://www.nuget.org/packages/Amazon.ElasticBeanstalk.Tools/4.4.0) adds support for new boolean command line parameter `--disable-imds-v1` which could be set to `true` to disable IMSDv1.
