### ISSUE TITLE
dotnet lambda package Failed to create application package

### ISSUE THREAD

**Issue by yanivkalo** [aws/aws-extensions-for-dotnet-cli#295]
### Describe the bug

I have dotnet 6.0 projects deployed using Jenkins and Serverless framework. I am using dotnet lambda package command to create a zip archive of the projects. Serverless framework then uses this zip file to deploy the lambda functions to AWS. We are also using the PublishReadyToRun=true flag in order to optimize our lambda runtime and lower the lambda cold starts. The command looks like this:
dotnet lambda package --configuration release --framework net6.0 --function-architecture arm64 --config-file ../../Serverless/aws-lambda-tools-defaults.json --msbuild-parameters -p:self-contained=true --output-package ../../Serverless/Artifacts/my-project.zip 

As I understand, in dotnet 6.0, it is mandatory to use self-contained=true along with PublishReadyToRun=true . As specified in the command above, I tried to add --msbuild-parameters -p:self-contained=true and also added the same flag in aws-lambda-tools-defaults.json configuration file but nothing seems to work. When I remove the PublishReadyToRun=true everything is working and the projects are being deployed successfully to AWS lambda. 
What cloud be wrong? 

### Expected Behavior

When using dotnet lambda package with PublishReadyToRun=true and --msbuild-parameters -p:self-contained=true , the zip file package should be created successfully.

### Current Behavior

When using dotnet lambda package with PublishReadyToRun=true and --msbuild-parameters -p:self-contained=true , the zip file package fails with the message "Failed to create application package".

### Reproduction Steps

1. Create a dotnet 6.0 lambda project.
2. Add <PublishReadyToRun>true</PublishReadyToRun> and <SelfContained>true</SelfContained> under the <PropertyGroup> section in the .csproj file.
3. Add  aws-lambda-tools-defaults.json with the line :
{
    "msbuild-parameters": "--self-contained true"
}
4. Run dotnet restore 
5. Run dotnet lambda package --configuration release --framework net6.0 --function-architecture arm64 --config-file ../../Serverless/aws-lambda-tools-defaults.json --msbuild-parameters -p:self-contained=true --output-package ../../Serverless/Artifacts/my-project.zip 

### Possible Solution

It seems that the flag --self-contained of the dotnet publish command is being always set to false no mater what I configure in the dotnet lambda package command and in the aws-lambda-tools-defaults.json configuration file.

### Targeted .NET platform

.net 6.0

### CLI extension version

Amazon Lambda Tools for .NET Core applications (5.8.1)

### Environment details (OS name and version, etc.)

Ubuntu, Amazon linux 2

**Comment by ashishdhingra** [comment]
@yanivkalo Good morning. Please share the detailed logs so that we could investigate further (specifically the underlying `dotnet publish` command. Also, could you try setting `--msbuild-parameters` with `/p` (instead of `-p`), for example `--msbuild-parameters "/p:self-contained=true"`.

Thanks,
Ashish

**Comment by yanivkalo** [comment]
Hi @ashishdhingra ,

I run the command:
dotnet lambda package --configuration release --framework net6.0 --function-architecture x86_64 **--msbuild-parameters "/p:self-contained=true"** --output-package ../Serverless/Artifacts/my-project-package.zip

and I see in the logs this line:
dotnet publish --output "/var/lib/jenkins/jobs/my-project-services/branches/dev/workspace/my-project/my-project.BulkSubmit/bin/release/net6.0/publish" --configuration "release" --framework "net6.0" **/p:self-contained=true** /p:GenerateRuntimeConfigurationFiles=true --runtime linux-x64 **--self-contained false** 
... publish: Microsoft (R) Build Engine version 17.1.0+ae57d105c for .NET
... publish: Copyright (C) Microsoft Corporation. All rights reserved.
... publish:   Determining projects to restore...

... publish:   Restored /var/lib/jenkins/jobs/my-project-services/branches/dev/workspace/my-project/my-project.BulkSubmit/my-project.BulkSubmit.csproj (in 2.82 sec).

... publish:   my-project.BulkSubmit -> /var/lib/jenkins/jobs/my-project-services/branches/dev/workspace/my-project/my-project.BulkSubmit/bin/release/net6.0/linux-x64/my-project.BulkSubmit.dll

Failed to create application package

**Comment by yanivkalo** [comment]
Another portion from the log:

... publish:          Creating directory "obj/release/net6.0/linux-x64/R2R".
... publish:        Done executing task "MakeDir".
... publish:        Task "ResolvePackageFileConflicts" skipped, due to false condition; ('$(SelfContained)' != 'true') was evaluated as ('True' != 'true').
... publish:        Using "PrepareForReadyToRunCompilation" task from assembly "/usr/share/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk/targets/../tools/net6.0/Microsoft.NET.Build.Tasks.dll".
... publish:        Task "PrepareForReadyToRunCompilation"
... publish:        Done executing task "PrepareForReadyToRunCompilation".
... publish:      1>Done building target "_PrepareForReadyToRunCompilation" in project "my-project.BulkSubmit.csproj".
... publish:      1>Target "_CreateR2RImages" in file "/usr/share/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.CrossGen.targets" from project "/var/lib/jenkins/jobs/my-project-services/branches/dev/workspace/my-project.Services/my-project.BulkSubmit/my-project.BulkSubmit.csproj" (target "CreateReadyToRunImages" depends on it):
... publish:        Building target "_CreateR2RImages" completely.
... publish:        Output file "obj/release/net6.0/linux-x64/R2R/Amazon.Lambda.Core.dll" does not exist.
... publish:        Using "RunReadyToRunCompiler" task from assembly "/usr/share/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk/targets/../tools/net6.0/Microsoft.NET.Build.Tasks.dll".
... publish:        Task "RunReadyToRunCompiler"
... publish:          /tmp/.nuget/packages/microsoft.netcore.app.crossgen2.linux-x64/6.0.3/tools/crossgen2 --targetos:linux
... publish:          --targetarch:x64
... publish:          -O
... publish:          -r:"/tmp/.nuget/packages/amazon.lambda.core/2.1.0/lib/net6.0/Amazon.Lambda.Core.dll"


I see "Output file "obj/release/net6.0/linux-x64/R2R/Amazon.Lambda.Core.dll" does not exist." . I am not sure what does it mean and if it is related.

**Comment by ashishdhingra** [comment]
@yanivkalo Could you share sample code solution to reproduce the issue? Somehow I'm unable to reproduce the issue locally.
