### ISSUE TITLE
aws-ecs-tools-defaults.json does not appear to parse desired-count

### ISSUE THREAD

**Issue by jbright** [aws/aws-extensions-for-dotnet-cli#3]
If you pass `--desired-count 1` or `-dc 1` on the command line for `dotnet ecs deploy-schedule-task`, the task count is correctly set. If you set the value in the default json file, the value is not found and it doesn't default to a value of 1 per the documentation. Instead it throws an error of 

```
Error creating CloudWatch Event target: 1 validation error detected: Value '0' at 'targets.1.member.ecsParameters.taskCount' failed to satisfy constraint: Member must have value greater than or equal to 1
```

A snippet of my json file:

```json
{
    ...
    "task-execution-role"         : "ecsTaskExecutionRule",
    "desired-count"               : 1,
    "task-cpu"                    : "1024",
    "task-memory"                 : "2048"
}
```

I can see in code where this is parse, but it's not clear why it's not picking up the json value.

**Comment by normj** [comment]
I found the issue and will get a fix out soon.

**Comment by jbright** [comment]
Thanks! I really appreciate the effort.

**Comment by normj** [comment]
Version 1.1.1 of `Amazon.ECS.Tools` is out that fixes this issue. Thanks for reporting the issue.
