### ISSUE TITLE
dotnet lambda deploy/list-function --profile

### ISSUE THREAD

**Issue by sercanyaldiz** [aws/aws-extensions-for-dotnet-cli#31]
Hi,
Version:
_Amazon Lambda Tools for .NET Core applications (2.2.0)_

**When running the lambda commands including the --profile , iam getting the following error:**
Error listing Lambda functions: Error calling AssumeRole for role arn:aws:iam::1213123213:role/administrator

Why doest this not work? I can run aws cli commands with this profile.
aws s3 ls --profile administrator

My config is as following:
[profile single]
region = eu-west-1
output = text

[profile administrator]
region = eu-west-1
role_arn = arn:aws:iam::121312313:role/administrator
source_profile=single
mfa_serial = arn:aws:iam::121312313:mfa/user@companny

Do i miss something?

**Comment by normj** [comment]
We need to add MFA support to this tool.

**Comment by dbaranovsky** [comment]
Any updates on this? it's painful indeed to not have mfa support

**Comment by normj** [comment]
Circling back on this issue. MFA support was added in version 3.3.0 

https://github.com/aws/aws-extensions-for-dotnet-cli/blob/master/RELEASE.CHANGELOG.md#release-2019-08-16
