### ISSUE TITLE
Certain lambda layers result in manifest error

### ISSUE THREAD

**Issue by baughj** [aws/aws-extensions-for-dotnet-cli#318]
### Describe the bug

Attempting to deploy a lambda layer without a layer description manifest results in an error:

```
Amazon Lambda Tools for .NET Core applications (5.10.5)
Project Home: https://github.com/aws/aws-extensions-for-dotnet-cli, https://github.com/aws/aws-lambda-dotnet

Inspecting Lambda layers for runtime package store manifests
... arn:aws:lambda:us-east-1:464622532012:layer:dd-trace-dotnet:15: Skipped, does not contain a layer description manifest
... arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension:57: Skipped, does not contain a layer description manifest
```

Same behavior was observed in https://github.com/aws/aws-extensions-for-dotnet-cli/issues/202 but not fixed or addressed.
Root cause seems to be: https://github.com/aws/aws-extensions-for-dotnet-cli/blob/006e4bab4e7a22119d21209326d37fbac9a82776/src/Amazon.Lambda.Tools/LambdaUtilities.cs#L551 

### Expected Behavior

Tooling should just use the layer, since the layers can be added later after creation using `aws lambda update-function-configuration` (without a similar error).

### Current Behavior

```
Amazon Lambda Tools for .NET Core applications (5.10.5)
Project Home: https://github.com/aws/aws-extensions-for-dotnet-cli, https://github.com/aws/aws-lambda-dotnet

Inspecting Lambda layers for runtime package store manifests
... arn:aws:lambda:us-east-1:464622532012:layer:dd-trace-dotnet:15: Skipped, does not contain a layer description manifest
... arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension:57: Skipped, does not contain a layer description manifest
```

### Reproduction Steps

Deploy (any) function using the publicly available Datadog layers for .NET eg `-fl arn:aws:lambda:us-east-1:464622532012:layer:dd-trace-dotnet:15,arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension:57`

### Possible Solution

I suggest that this be made a warning instead, as the CLI tooling enforces no such requirement.

### Targeted .NET platform

.NET 8

### CLI extension version

```
Package Id                                     Version         Commands
------------------------------------------------------------------------------------------
amazon.lambda.testtool-8.0                     0.15.2          dotnet-lambda-test-tool-8.0
amazon.lambda.tools                            5.10.5          dotnet-lambda
aws.codeartifact.nuget.credentialprovider      1.0.1           dotnet-codeartifact-creds
dotnet-ef                                      8.0.2           dotnet-ef
microsoft.dotnet-interactive                   1.0.510102      dotnet-interactive
```

### Environment details (OS name and version, etc.)

Windows 11 (WSL)

**Comment by normj** [comment]
The `Skipped, does not contain a layer description manifest` messages should just be informational that we are saying the layer you are using don't have an associated manifest of NuGet packages so it won't be used for trimming out .NET assemblies from the deployment bundle as part of the underlying `dotnet publish`. It should not be stopping deployment, is that what you are seeing?

**Comment by baughj** [comment]
No, I think this is just a case of user error re: misunderstanding the output. I had interpreted the message as indicating that the layers would not be used, but they are.

**Comment by normj** [comment]
Cool, glad everything is working for you.
