### ISSUE TITLE
Yaml templates with intrinsic functions that use the short form don't work

### ISSUE THREAD

**Issue by szilvaa** [aws/aws-extensions-for-dotnet-cli#32]
`dotnet lambda deploy-serverless` roundtrips the template using YamlDotNet so that it can update some values (Code Uri and such). This unfortunately completely destroys the intrinsic functions in the template. 

For example, add the following Condition to a template and then deploy it
```
  StandardStack: !Equals [!Ref 'AWS::StackName', bla]
```
If you look at what's get uploaded by `dotnet lambda deploy-serverless` in the CloudFormation console then you will see that the `!Equals` is dropped. This is a bug in YamlDotNet. I just created a PR to fix this [here](https://github.com/aaubry/YamlDotNet/pull/347).

**Comment by normj** [comment]
Closing this in favor of tracking in the PR
