### ISSUE TITLE
PM> Install-Package Amazon.Lambda.Tools Even I'm using .Net 8.0 version

### ISSUE THREAD

**Issue by developersatish** [aws/aws-extensions-for-dotnet-cli#330]
### Describe the bug

Install-Package Amazon.Lambda.Tools
Restoring packages for ****\QuizGamesServices.csproj...
  CACHE https://api.nuget.org/v3/vulnerabilities/index.json
  CACHE https://api.nuget.org/v3-vulnerabilities/2024.07.17.23.32.30/vulnerability.base.json
  CACHE https://api.nuget.org/v3-vulnerabilities/2024.07.17.23.32.30/2024.07.21.23.32.41/vulnerability.update.json
Install-Package : NU1202: Package Amazon.Lambda.Tools 5.10.7 is not compatible with net8.0 (.NETCoreApp,Version=v8.0). Package Amazon.Lambda.Tools 5.10.7 supports:
  - net6.0 (.NETCoreApp,Version=v6.0) / any
  - net8.0 (.NETCoreApp,Version=v8.0) / any
  - netcoreapp3.1 (.NETCoreApp,Version=v3.1) / any
At line:1 char:1
+ Install-Package Amazon.Lambda.Tools
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : NU1212: Invalid project-package combination for Amazon.Lambda.Tools 5.10.7. DotnetToolReference project style can only contain references of the DotnetTool type 
At line:1 char:1
+ Install-Package Amazon.Lambda.Tools
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package 'Amazon.Lambda.Tools 5.10.7' has a package type 'DotnetTool' that is not supported by project 'QuizGamesServices'.
At line:1 char:1
+ Install-Package Amazon.Lambda.Tools
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 

### Expected Behavior

It should install properly

### Current Behavior

Getting an error. 

### Reproduction Steps

PM> Install-Package Amazon.Lambda.Tools

### Targeted .NET platform

.Net 8.0

### CLI extension version

PM> Install-Package Amazon.Lambda.Tools

### Environment details (OS name and version, etc.)

Window 11

**Comment by bhoradc** [comment]
Hi @developersatish, 

Thanks for reporting this issue. Can you confirm if you are seeing the same issue with `dotnet tool install` command for global installation of ".NET tools"?

`dotnet tool install -g Amazon.Lambda.Tools`

Regards, 
Chaitanya
