### ISSUE TITLE
dotnet lambda package fails with source generators

### ISSUE THREAD

**Issue by petro2050** [aws/aws-extensions-for-dotnet-cli#334]
### Describe the bug

When I run `dotnet lambda package -o output.zip -c Release -f net8.0` on a Mac M1 computer, I get `CSC : error CS8034: Unable to load Analyzer assembly` for one of the dependent projects which is a source generator. The same command succeeds in Github Actions since the build server is running Linux.

It seems internally `dotnet lambda package` sets publish runtime identifier to linux-x64. On Mac, this seems to work for .NET 8 projects, but it fails for a source generator using .NET Standard 2.0.

### Expected Behavior

`dotnet lambda package` should run successfully on ARM-based Mac when the lambda uses a dependent source generator.

### Current Behavior

Compilation throws `CSC : error CS8034: Unable to load Analyzer assembly`

### Reproduction Steps

See the description

### Targeted .NET platform

.NET 8 for the lambda and other dependent projects except for a source generator project built in .NET Standard 2.0.

### CLI extension version

`dotnet lambda package`

### Environment details (OS name and version, etc.)

macOS Sonoma

**Comment by normj** [comment]
What happens when you run `dotnet publish -c Release -c Release -f net8.0` in the project directory?

**Comment by petro2050** [comment]
this works, but it generates artifacts for `osx-arm64`.

if i run `dotnet publish -c Release -f net8.0 -r linux-x64`, it will fail with the same error.

in both runs, i see a non-fatal error:

> error NETSDK1005: Assets file {project.assets.json for the generator} doesn't have a target for 'net8.0'. Ensure that restore has run and that you have included 'net8.0' in the TargetFrameworks for your project.

so it seems the issue may not be with lambda.

**Comment by normj** [comment]
Yeah it sounds like you have a regular .NET build issue. When you figure out I would be curious what the problem was in case we hear others having the problem. Is the source generator a public generator on NuGet?

**Comment by petro2050** [comment]
it's not. it's a project reference and the generator is in the same solution as the referencing project.

**Comment by bhoradc** [comment]
Hi @petro2050, 

Based on the information shared above, it appears that the issue you faced was related to your local .NET build environment and not directly related to the AWS SDK for .NET or the AWS Extensions for .NET CLI. Therefore, I will proceed to close this issue.

We appreciate if you are able to share the solution for your problem, which would benefit other users who may encounter similar issues.

Regards, 
Chaitanya
