### ISSUE TITLE
"Missing required parameter: --launch-type" error with deploy-scheduled-task.

### ISSUE THREAD

**Issue by elliot-creedy** [aws/aws-extensions-for-dotnet-cli#36]
[deploy-scheduled-task](https://github.com/aws/aws-extensions-for-dotnet-cli/blob/master/src/Amazon.ECS.Tools/Commands/DeployScheduledTaskCommand.cs) appears to be missing command options that are present in the comparable [deploy-service](https://github.com/aws/aws-extensions-for-dotnet-cli/blob/master/src/Amazon.ECS.Tools/Commands/DeployServiceCommand.cs).

Here's a close copy of what I am using in my build script:

```
dotnet ecs deploy-scheduled-task
--disable-interactive true
--project-location ExampleService
--region region
--profile default
--configuration Release
--tag exampleservice:latest
--cluster cluster
--launch-type EC2
--task-definition-name ExampleService
--task-definition-network-mode bridge
--task-definition-task-role arn:aws:iam::account-number:role/ecs-role
--container-name ExampleService
--container-memory-hard-limit 128
--container-memory-soft-limit 128
--container-port-mapping ''
--container-environment-variables '"ENVIRONMENT"="Production"'
--skip-image-push false
--rule ExampleService
--rule-target ExampleService
--schedule-expression 'cron(15 0 * * ? *)'
--cloudwatch-event-role arn:aws:iam::account-number:role/role-name
--desired-count 1
```

This will build the docker image and push it, then fail with the error `Missing required parameter: --launch-type` when it goes to update the scheduled task definition.

This is with version 3.0.0 of Amazon.ECS.Tools installed globally.

**Comment by klaytaybai** [comment]
@elliot-creedy, thank you for reporting this.  I'm not very familiar with this code, but this does seem to be a bug.  I will notify the people who can help out.

**Comment by ashishdhingra** [comment]
Hi @elliot-creedy,

Good morning.

I was going through backlog and came across this issue. Could you please check if this is fixed in the latest version? If you look at the code https://github.com/aws/aws-extensions-for-dotnet-cli/blob/4dc8a0609a2a45abe87092a068580ee3202d26af/src/Amazon.ECS.Tools/Commands/DeployScheduledTaskCommand.cs#L142, I could see the support for `--launch-type` argument.

Thanks,
Ashish

**Comment by elliot-creedy** [comment]
Sorry, it's been a long time since I worked on this and I don't have the necessary stuff to test it anymore.

**Comment by ashishdhingra** [comment]
> Sorry, it's been a long time since I worked on this and I don't have the necessary stuff to test it anymore.

@elliot-creedy Thanks for your reply. I will close this issue for now. Feel free to open a new issue in case this is not working.
