### ISSUE TITLE
task-cpu and task-memory are parsed from strings. Unclear in documentation

### ISSUE THREAD

**Issue by jbright** [aws/aws-extensions-for-dotnet-cli#4]
Because the documentation says:

```
     --task-cpu                              The amount of cpu to allocate for the task definition. Fargate only.
     --task-memory                           The amount of memory to allocated for the task definition. Fargate only.
```

it implies that number values should be set. For example:

```json
{
    "task-cpu"                    : 1024,
    "task-memory"                 : 2048
}
```

However, if you put in integer values, the values aren't parsed and the user is prompted to enter the value. Instead, you must provide string values:

```json
{
    "task-cpu"                    : "1024",
    "task-memory"                 : "2048"
}
```

Can the help be updated to reflect this? (If you keep it string values).

**Comment by normj** [comment]
I'll see if we can make the logic more flexible. The value is a string because you could also set the values with units like "0.5GB"

**Comment by jbright** [comment]
Ahhh. I'd also be fine with updated help text. I realize fargate is really, really new too. I have another question but instead of polluting this ticket, I'll pop it into Glitter.

**Comment by normj** [comment]
In version 1.1.1 of `Amazon.ECS.Tools` that I just released it will read cpu and memory from the json file as either string or int.
