### ISSUE TITLE
dotnet lambda deploy-function does not display code in AWS lambda editor

### ISSUE THREAD

**Issue by geordieboy** [aws/aws-extensions-for-dotnet-cli#42]
Deploying a lambda function creates the function in AWS but does not appear to load the code correctly using amazon.lambda.tools 3.1.0 on OSX 10.14 and dotnet core 2.1.302

steps to reproduce
--------------
dotnet lambda deploy-function
Amazon Lambda Tools for .NET Core applications (3.1.0)
Project Home: https://github.com/aws/aws-extensions-for-dotnet-cli, https://github.com/aws/aws-lambda-dotnet

Executing publish command
Deleted previous publish folder
... invoking 'dotnet publish', working folder '/Users/leeatkinson/Work/sharp/core/AWSLambda1/AWSLambda1/bin/Release/netcoreapp2.1/publish'
... Disabling compilation context to reduce package size. If compilation context is needed pass in the "/p:PreserveCompilationContext=false" switch.
... publish: Microsoft (R) Build Engine version 15.7.179.6572 for .NET Core
... publish: Copyright (C) Microsoft Corporation. All rights reserved.
... publish:   Restore completed in 50.69 ms for /Users/leeatkinson/Work/sharp/core/AWSLambda1/AWSLambda1/AWSLambda1.csproj.
... publish:   AWSLambda1 -> /Users/leeatkinson/Work/sharp/core/AWSLambda1/AWSLambda1/bin/Release/netcoreapp2.1/rhel.7.2-x64/AWSLambda1.dll
... publish:   AWSLambda1 -> /Users/leeatkinson/Work/sharp/core/AWSLambda1/AWSLambda1/bin/Release/netcoreapp2.1/publish/
Changed permissions on published dll (chmod +r AWSLambda1.dll).
Changed permissions on published dll (chmod +r Newtonsoft.Json.dll).
Changed permissions on published dll (chmod +r Amazon.Lambda.Core.dll).
Changed permissions on published dll (chmod +r Amazon.Lambda.Serialization.Json.dll).
Zipping publish folder /Users/leeatkinson/Work/sharp/core/AWSLambda1/AWSLambda1/bin/Release/netcoreapp2.1/publish to /Users/leeatkinson/Work/sharp/core/AWSLambda1/AWSLambda1/bin/Release/netcoreapp2.1/AWSLambda1.zip
... zipping:   adding: AWSLambda1.runtimeconfig.json (deflated 23%)
... zipping:   adding: AWSLambda1.pdb (deflated 27%)
... zipping:   adding: AWSLambda1.dll (deflated 56%)
... zipping:   adding: AWSLambda1.deps.json (deflated 81%)
... zipping:   adding: Newtonsoft.Json.dll (deflated 60%)
... zipping:   adding: Amazon.Lambda.Core.dll (deflated 57%)
... zipping:   adding: Amazon.Lambda.Serialization.Json.dll (deflated 56%)
Created publish archive (/Users/leeatkinson/Work/sharp/core/AWSLambda1/AWSLambda1/bin/Release/netcoreapp2.1/AWSLambda1.zip).
Enter Function Name: (AWS Lambda function name)
AWSLambda1
Updating code for existing function  <---- seems to upload code but does not display in editor

![screenshot 2018-10-31 at 08 40 03](https://user-images.githubusercontent.com/1053290/47775793-a09d8000-dce8-11e8-9919-550823df31bc.png)

**Comment by klaytaybai** [comment]
Are you uploading using a zip file?  The editor is designed to edit one file at a time, which conflicts with the zip upload choice.

**Comment by geordieboy** [comment]
Im not specifying an upload choice but i assume the CLI function uploads whatever the publish function produces which seems to be a zip file. all I am doing is following the guidance to deploy a function to AWS  ... did you read the post above?  the AWS lambda UI allows you to upload a zip BTW

**Comment by geordieboy** [comment]
Is there an option to upload the individual files in a zip instread of using the complied code with the toolkit from the CLI?

**Comment by normj** [comment]
The Lambda editor currently only the supports dynamic languages Node.js and Python where no build is required and there is a single file. For Go, Java and .NET a build is required which the console does not currently support which is why the Lambda editor will not be displayed. Also the zip file doesn't contain the code it contains the compiled assemblies.

Someday the Lambda console may support static languages in the editor.

**Comment by geordieboy** [comment]
Makes sense, cheers
