### ISSUE TITLE
Deploy-Function with config-file and project-location issue

### ISSUE THREAD

**Issue by davemcdermid** [aws/aws-extensions-for-dotnet-cli#48]
Hi,

When calling dotnet deploy-function with a project-location set to a sub-directory and config-file specified, it falls back to using interactive prompts instead of using parameters from the file.

Example that works (current dir in app):

`dotnet lambda deploy-function -cfg my-config-file.json`

Example that doesn't work (2 directories up):

`dotnet lambda deploy-function -pl ./src/App -cfg ./src/App/my-config-file.json`

This then prompts for the framework version:

`Enter Framework: (Target framework to compile, for example netcoreapp2.1.)`

The cfg file path seems correct, because if I deliberately make it wrong then I get an expected "Config file [...] cannot be found".

I can cd to the correct directory, but when running from a CI tool it's much more useful to specify the path and stay in the root directory.

**Comment by connorconway** [comment]
We are also experiencing the same issue. However, the above solution is not working for us. @klaytaybai was there any progress on this?

**Comment by MrZoidberg** [comment]
same issue.

**Comment by normj** [comment]
I have reproduced the issue and taking a look into why it is happening.

**Comment by normj** [comment]
I just published version 3.1.3 of Amazon.Lambda.Tools which has this issue fixed. Something to note the value for `-cfg` needs to be relative to `-pl`.

Thanks for reporting the issue.

**Comment by davemcdermid** [comment]
Great, thanks Norm. That makes sense.

Dave
