### ISSUE TITLE
When using -pcfg true tag, tag value written to file includes full ARN

### ISSUE THREAD

**Issue by jbright** [aws/aws-extensions-for-dotnet-cli#5]
Sorry if I'm being a pain. Think of this as a free QA person.

If you run a command that saves the config values back to the json file such as:

```bash
dotnet ecs deploy-task -cfg foo.json -pcfg true
```

When the tag is written back, it will pre-pend the ARN name. For example if my tag was:

```
"tag"     : "console-tester:latest"
```

When the file is written back, that is changed to 

```
"tag": "SECRETSTUFF.dkr.ecr.us-east-1.amazonaws.com/console-tester:latest",
```

If you run the task again, you actually create a new repository with that long name. 

(Sorry. I know you just released a version. Low priority bug. Just letting you know it's there.)

**Comment by normj** [comment]
Never be sorry, thanks for helping us make the product better!

I'll take a look into and get it fixed up.

**Comment by normj** [comment]
I pushed out version 1.1.2 of Amazon.ECS.Tools that fixes the tag being incorrectly written out. A new version of the AWS Toolkit for Visual Studio will be released with this fix as well soon.

Thanks for reporting the issue.

**Comment by normj** [comment]
The VS Toolkit has been released with this fix.
