### ISSUE TITLE
dotnet lambda deploy-serverless with template greater than 51,200 bytes

### ISSUE THREAD

**Issue by ckuehl** [aws/aws-extensions-for-dotnet-cli#50]
I am receiving the following error when using a serverless.template file that is greater than 50 KB:

```Error creating CloudFormation change set: 1 validation error detected: Value 'redacted' at 'templateBody' failed to satisfy constraint: Member must have length less than or equal to 51200```

Is there a workaround available? I don't see an option to automatically upload the template to S3, but perhaps I'm missing it.

**Comment by klaytaybai** [comment]
Hi @ckuehl,

As noted in the [CloudFormation limits documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html), the templateBody is capped at 51,200 bytes, so you won't be able to deploy it until that value is smaller.  However, you can use [nested stacks](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stack.html) or a separate upload to S3 as a workaround.

**Comment by ckuehl** [comment]
@klaytaybai I'm aware of the CloudFormation limit. I was specifically looking to see if there was a way to address this using the `dotnet lambda deploy-serverless` tooling. I don't see an option on the command to upload to S3, nor a way to point to an already-uploaded template in S3.

**Comment by normj** [comment]
Argh, I see the bug. In the code when checking to see if the template is greater then 50,000 I'm using templatePath and should be using templateBody. I'll get that fixed and released as soon as I can.

https://github.com/aws/aws-extensions-for-dotnet-cli/blob/51879ddf1e0a6fb989ed66685fe3487052c47482/src/Amazon.Lambda.Tools/Commands/DeployServerlessCommand.cs#L306-L313

**Comment by normj** [comment]
Version 3.1.2 of Amazon.Lambda.Tools was just released with this fix. Thanks for reporting the issue.
