### ISSUE TITLE
Nested Applications Require CAPABILITY_AUTO_EXPAND

### ISSUE THREAD

**Issue by alex-gausman** [aws/aws-extensions-for-dotnet-cli#51]
The recent introduction of nested applications to SAM requires that nested templates pass the value `CAPABILITY_AUTO_EXPAND` to `sam deploy` via the `--capabilities` parameter. How do I pass this value to `dotnet lambda deploy-serverless`?

Reference: https://aws.amazon.com/blogs/compute/announcing-nested-applications-for-aws-sam-and-the-aws-serverless-application-repository/

**Comment by normj** [comment]
I checked in the support to the [dev branch](https://github.com/aws/aws-extensions-for-dotnet-cli/commit/9f87144df6a82e3869c55a8a0cfaa58385accc85) and it will go out the next release.

**Comment by normj** [comment]
Version 3.1.2 of Amazon.Lambda.Tools was just released that now enables `CAPABILITY_AUTO_EXPAND`. Unlike `sam deploy` the capability is enabled by default and there is a flag to disable the capability if needed.

Thanks for letting me know about the missing setting.
