### ISSUE TITLE
no error for wrong parameter name

### ISSUE THREAD

**Issue by iamjaekim** [aws/aws-extensions-for-dotnet-cli#52]
cli tool version: `Tool 'amazon.lambda.tools' was reinstalled with the latest stable version (version '3.1.2').`

When a wrong parameter is given, it should print error for wrong parameter name instead of accepting the command. 

For example, --tag is not a valid option (certainly, tagname whatever is wrong) , yet it takes it and on its own, ignore and print the list function. 
`dotnet lambda list-functions --profile yourprofilename --region us-east-1 --tag whatever`

**Comment by klaytaybai** [comment]
Hi @jaekim09, this is a good piece of feedback.  Thanks.

**Comment by hunanniu** [comment]
No plan to address this
