### ISSUE TITLE
 aws-lambda-tools-defaults.json documentation

### ISSUE THREAD

**Issue by patoncrispy** [aws/aws-extensions-for-dotnet-cli#54]
Is there documentation for aws-lambda-tools-defaults.json somewhere? I've been Googling it and can't find anything. Only by sheer luck did I stumble across the template-substitutions property in an example and it would have come in handy a looong time ago. It would be great to see what other value I'm missing out on. 

Also, is it possible to define multiple template-substitutions? I tried using an array of strings but it doesn't seem to work.

Thanks!

**Comment by klaytaybai** [comment]
Hi @patoncrispy, I'm not aware of any more documentation either.   I think the best advice I could give you would be to look at the [relevant code](https://github.com/aws/aws-extensions-for-dotnet-cli/blob/master/src/Amazon.Lambda.Tools/LambdaToolsDefaults.cs) in our repository when you wish to use the defaults file.  This will also ensure that you are using a current source for your information.

Helpful files:
This will show you what you can use in the aws-lambda-tools-defaults.json file.
https://github.com/aws/aws-extensions-for-dotnet-cli/blob/master/src/Amazon.Lambda.Tools/LambdaToolsDefaults.cs

These will show you the information for the options you can use.
https://github.com/aws/aws-extensions-for-dotnet-cli/blob/master/src/Amazon.Lambda.Tools/LambdaDefinedCommandOptions.cs

https://github.com/aws/aws-extensions-for-dotnet-cli/blob/master/src/Amazon.Common.DotNetCli.Tools/Options/CommonDefinedCommandOptions.cs

**Comment by patoncrispy** [comment]
Yeah I've been scanning through the source code alright. Managed to find a few useful things (template-substitutions). Having this information surfaced somewhere though would let newcomers know the extent of the capabilities the tooling has.

**Comment by Coupz** [comment]
Thank you @normj 
Could have thought by myself but this was really helpful. 👍

**Comment by mungojam** [comment]
Documentation, or expanded information in the help text would be useful. There were two particular aspects that I didn't know until reading the comments in this issue:

1. That it was a json file. I assumed it might just be a text file with the parameters verbatim
2. The existence of a default file `aws-lambda-tools-defaults.json` so I didn't have to specify the name of the config file myself.

**Comment by benmccallum** [comment]
@normj, could you provide an example of setting the runtime via  the `ms-build-parameters` property of a aws-lambda-tools-defaults.json? I know it says "Add quotes around the value if the value contains spaces.", but is that for the whole thing or the value of the argument? 

I've tried:
* `-r rhel.7.2-x64` (reads switch as `rhel.7.2-x64`)
* `"\"-r rhel.7.2-x64\""` seems to read it better, but gives me : 
```
publish: MSBUILD : error MSB1001: Unknown switch.
... publish: Switch: -r rhel.7.2-x64
... publish: For switch syntax, type "MSBuild -help"
```

**Comment by dalton5** [comment]
Hi,

Is it possible to add the environement variable for the environement of development?

In fact, VS allows to setup appsettings.json, appsettings.testing.json, appsettings.json.production

It would be great to be able to rpovide environement varibel for the deployment of the lambda functions and automatically picking the good connection string .

Thanks,
