### ISSUE TITLE
Documentation - DotNetCliToolReference not supported?

### ISSUE THREAD

**Issue by abbotware** [aws/aws-extensions-for-dotnet-cli#56]
I see that there is a migration away from DotNetCliToolReference... is there any reason though I couldnt use DotNetCliToolReference and update the version to 3.0.1 ?  Or is that only or Lambda based projects?

**Comment by abbotware** [comment]
also a little more clarification -  I am ok with global tools for development, but on a build server, I would have special project call tools.csproj.  during the build process I do a restore and then run the CLI tools from that project.  This way I don't 'pollute' the build server and also control the tool versions via source control

**Comment by abbotware** [comment]
can you even run multiple (or specific version) of the global tools? 
It sounds like MS went from being able to safely 'version' tools - to single version in a, dare i say it...  global [assembly] cache ?

**Comment by normj** [comment]
In .NET Core 3.0 they are introducing the concept of local tools. So things are moving in a direction I think you will prefer. https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#local-dotnet-tools

For now I don't think there is anymore we can do so I'm going to close the issue.
