### ISSUE TITLE
Implement Layer support for .NET Core Lambda Functions

### ISSUE THREAD

**Issue by Kralizek** [aws/aws-extensions-for-dotnet-cli#58]
Hi,

One of the announcements at re:Invent was the introduction of layers in Lambda.

Whilst it's pretty easy to see the fit in dynamic runtimes like node.js and python, I wonder how applicable is this new feature to a build-ahead runtime like .NET Core.

I can imagine something like dynamic binding of any assembly present in /opt but the list of useful usages of dynamic binding is pretty short in .NET Core (as opposed to .NET Framework where assemblies might be referenced in the app.config file)

**Comment by normj** [comment]
For those tracking this feature the work is being done in the [lambda-layers](https://github.com/aws/aws-extensions-for-dotnet-cli/tree/lambda-layers) branch.

The design is written up [here](https://github.com/aws/aws-extensions-for-dotnet-cli/blob/lambda-layers/docs/Layers.md)

If you want to try the work in progress follow these steps to build and install from source:
* Clone Repo
* checkout lambda-layers branch
* Execute the following command at the repo root
  * `dotnet msbuild buildtools/build.proj /t:build-nuget-packages`
* Uninstall current tool
  * `dotnet tool uninstall -g amazon.lambda.tools`
* Install the newly built package
  * `dotnet tool install -g --add-source ./Deployment/nuget-packages/ Amazon.Lambda.Tools --version 3.2.0-beta1`

Current status is the **publish-layer**, **deploy-function** and **package** command have been updated to support layers. The **deploy-serverless** and **package-ci** commands need to be updated. I would also like to add some new commands to view and inspect the available layers.

Appreciate any feedback. Keep in mind this is still a work and process and the design is open change.

**Comment by bjorg** [comment]
Very exciting! This will be a huge win for projects with a large number of common assemblies between Lambda functions.

**Comment by normj** [comment]
The way I have been working on Layers for .NET is it essentially provides a cache of NuGet packages to your Lambda functions. So when you deploy your Lambda functions they won't have to include the NuGet packages with you function. 

For your local development though you will still need access to the NuGet packages since MSBuild will not be able to resolve the dependencies via a Lambda layer. Although that would be cool.

**Comment by bjorg** [comment]
I think this would be a HUGE win when porting legacy code that is tight up with a lot of nuget assemblies. That can be a really big simplifications for splitting up such applications over many smaller entry-point functions.

**Comment by petarrepac** [comment]
Is the only benefit of the Lambda Layers in reduced size of deployment package?
Is there also a faster cold-start?
Can we pre-JIT the DLLs in the Layer?

**Comment by normj** [comment]
Yes, there is an option to pre-JIT the DLLs but you need to create the layer on an Amazon Linux environment. Check out the [optimizing packaging](https://github.com/aws/aws-extensions-for-dotnet-cli/blob/lambda-layers/docs/Layers.md#optimizing-packages) in the preview docs.

**Comment by niraj-bpsoftware** [comment]
Hi, 
Has anyone used Layers and pre-JIT the dlls? I have .NET Core 2.1 with CI/CD Pipeline implemented using AWS CodeBuild/CodePipeline. I have limited knowledge on Linux. I am using buildspec.yaml file in my serverless visual studio project.
buildspec.yaml:

> version: 0.2
> phases:
>   install:
>     commands:
>       - dotnet tool install -g Amazon.Lambda.Tools
>   pre_build:
>     commands:
>       - dotnet restore --configfile NuGet.Config
>   build:
>     commands:
>       - cd BestHealth.AWS.Lambda
>       - dotnet lambda package-ci --template serverless.template --s3-bucket bha-codebuild-deployment-artifacts --output-template updated-serverless.template.json
> artifacts:
>   files:
>     - ./BestHealth.AWS.Lambda/updated-serverless.template.json
>   discard-paths: yes

If anyone can provide step by step instructions on how to use layers and pre-jit dlls to be used for lambda in this CI/CD environment, it would be great.

**Comment by normj** [comment]
The PR has been submitted. I would appreciate any feedback. The PR is long so I recommend checking out the [layer docs](https://github.com/aws/aws-extensions-for-dotnet-cli/blob/lambda-layers/docs/Layers.md)

https://github.com/aws/aws-extensions-for-dotnet-cli/pull/63

**Comment by Kralizek** [comment]
Wow! That's a nice morning surprise! :D

I read through the docs you linked and I didn't see any sample of a lambda function using a layer (or maybe I just need a stronger coffee?).

So I have few questions that maybe could be explictly answered in the documentation
- how is a function affected when planning to use a layer?
- how is the ci/cd process affected when planning to use a layer?

Apoligies if I overlooked and the answers are already replied :P

**Comment by bjorg** [comment]
That is a lot of code! Scanning through it, I wasn't able to answer the following: will it be possible to create the assets locally for a runtime package store without having a layer being created as part of the process? Similar to how it is possible to package a Lambda function without deploying it.

Here is the workflow I'm thinking of.
1. Use `Amazon.Lambda.Tools` to create a runtime package store
1. Use `Amazon.Lambda.Tools` to create Lambda packages for all functions referencing the runtime package store from the previous step
1. Use a 3rd party tool to create the lambda layer for the runtime package store and deploy the Lambda functions referencing the layer

**Comment by normj** [comment]
Version 3.2.0 of Amazon.Lambda.Tools got released today with the Layer support. Here is the blog post for the feature. https://aws.amazon.com/blogs/developer/aws-lambda-layers-with-net-core/

I'm gonna close this issue now that the feature has been released.

@Kralizek The function is affected by not having to include any of the dependencies from the layer into the deployment bundle, this can greatly reduce your upload size. Also you have the option to pre-jit the assemblies in the layers which can reduce cold start time. But you have to create the layer on an Amazon Linux instance. For CI/CD the package and packge-ci commands were also updated for this release. If you use the package command then it is up to you to set the DOTNET_SHARED_STORE environment variable when you deploy. The package command will tell you what the value should be set to.

@bjorg As we talked offline I would appreciate your feedback now that it is released and you can play around with the feature how we could best support your use cases.

**Comment by RamiSh** [comment]
I don't seem to find any documentation on how to utilize the --config-file switch. [This doc](https://aws.amazon.com/blogs/developer/aws-lambda-layers-with-net-core/) isn't sufficient to get me started in a more complex scenario. Also, how would this work for a customized manifest file that pulls references from a custom nuget server?

**Comment by klaytaybai** [comment]
@RamiSh, please open a new issue regarding your documentation concern.
