### ISSUE TITLE
Segfault with latest lambda tools

### ISSUE THREAD

**Issue by hmvs** [aws/aws-extensions-for-dotnet-cli#60]
Segfault on `dotnet lambda` command

`kernel: [42898.833720] dotnet-lambda[3674]: segfault at 0 ip 0000000000000000 sp 00007ffd8abced58 error 14 in dotnet-lambda[3ff000+1000]`

Is there anything else I need to provide to understand what is the issue? 

dotnet --info
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.104
 Commit:    73f036d4ac

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /snap/dotnet-sdk/29/sdk/2.2.104/

Host (useful for support):
  Version: 2.2.2
  Commit:  a4fd7b2c84

.NET Core SDKs installed:
  2.2.104 [/snap/dotnet-sdk/29/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.2 [/snap/dotnet-sdk/29/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.2 [/snap/dotnet-sdk/29/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.2 [/snap/dotnet-sdk/29/shared/Microsoft.NETCore.App]

```

dotnet tool list -g
```
Package Id               Version      Commands     
---------------------------------------------------
amazon.lambda.tools      3.1.2        dotnet-lambda
```

**Comment by NashSequeira** [comment]
what was the resolution? I am also getting segfaults on ubuntu 20.04

**Comment by NashSequeira** [comment]
fwiw: Its an issue with how globally installed tools interact with snap installed dotnet: 
https://github.com/dotnet/installer/issues/491#issuecomment-464173079
ended up just setting the following env vars: 
```
export LD_LIBRARY_PATH=/snap/dotnet-sdk/current/lib/x86_64-linux-gnu
export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
```

**Comment by NashSequeira** [comment]
fwiw: i ended up doing a clean install of the dotnet runtime and sdks using apt instead of snap

**Comment by hmvs** [comment]
We moved the discussion to this issue https://github.com/dotnet/runtime/issues/3464
