### ISSUE TITLE
When deploy function with function-layers, it does not keep my configuration

### ISSUE THREAD

**Issue by ifew** [aws/aws-extensions-for-dotnet-cli#61]
Version: 3.2.0-beta1

I'm not sure this correctly or bug

Because I using CLI deploy function it keeps my configuration
When I deploy function with function-layers, it does not keep my configuration
- Memory reset to 256MB
- Timeout reset to 30 seconds
- Clear all Environment Variables and have only DOTNET_SHARED_STORE

Thankyou

**Comment by klaytaybai** [comment]
Hi @ifew, thank you for reporting this.  I'll prioritize working on this so changes can be made before it gets out of beta.  I haven't setup a reproduction yet or done a full code review, but I do see a couple spots in the code that might be problematic.

**Comment by normj** [comment]
Thanks for trying out the beta version. What version where you upgrading from. When the tool switch from being a `DotNetCliToolReference` to a Global Tool we changed the behavior so that values from the `aws-lambda-tools-defaults.json` file are always applied. This was highly request change.

**Comment by ifew** [comment]
> Thanks for trying out the beta version. What version where you upgrading from. When the tool switch from being a `DotNetCliToolReference` to a Global Tool we changed the behavior so that values from the `aws-lambda-tools-defaults.json` file are always applied. This was highly request change.

Hi, I use a Global Tool and I think aws-lambda-tools-defaults.json is a high priority to follow them, but I want to share my scenarios

For the first time, I deploy and using the config from aws-lambda-tools-defaults.json. after that, I set up environment variables for using on AWS Environment and its difference within aws-lambda-tools-defaults.json

Previously I use version 3.1.2, and I can deploy update function with keeps my environment variables on AWS Environment

Thank you for doing it, I love these tools

**Comment by clearwaterstream** [comment]
Hi, same issue here. I'm using Amazon Lambda Tools for .NET Core applications (3.3.1).

After deploy, all my environmental variables get cleared, and one is added -- DOTNET_SHARED_STORE which is needed for the lambda layers.

As per `dotnet lambda help deploy-function` if ` --environment-variables` is set then they would be replaced, if `--append-environment-variables` is set then they would be added to an existing set. If nothing is specified I'm presuming the environmental variables would not be touched ....

Please take a look, thanks!!

**Comment by ashishdhingra** [comment]
Hi @ifew,

Could you please try the latest version of Lambda tools and see if this is still an issue? Kindly confirm.

Thanks,
Ashish

**Comment by ifew** [comment]
> Hi @ifew,
> 
> Could you please try the latest version of Lambda tools and see if this is still an issue? Kindly confirm.
> 
> Thanks,
> Ashish

Hi @ashishdhingra ,

I try on version 4.0 with `dotnet lambda deploy-function memberlist-crt-ado -fms 128 -ft 600`, and it's work!!
not clear environment variables and can set lambda config
