### ISSUE TITLE
dotnet lambda package support for --no-build

### ISSUE THREAD

**Issue by JonCubed** [aws/aws-extensions-for-dotnet-cli#64]
It would be very helpful if the `dotnet lambda package` command supported the `--no-build` switch of the `dotnet publish` command. We run dotnet commands separately so we only need package to publish not restore or build. Currently we have a work around by using `--msbuild-parameters` and passing in  `'/property:NoBuild=true'` however this is not very intuitive.

It should also be noted that the `--no-build` switch was introduced to the publish command in the [ .NET Core 2.1 SDK](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish?tabs=netcore21)

I'd also be happy to contribute a PR for this if required

**Comment by normj** [comment]
I didn't realize they added the `--no-build` switch. Sounds like a useful feature to add. I can put this request on my backlog but I would also happily take a PR if you want to speed up this getting done.

**Comment by LechuckThePirate** [comment]
> /property:NoBuild=true

Can you give me some directions on how to use that? We are running our pipelines with bitbucket and powershell 7.0 doesn't support sdk 2.1 so we had to upgrade the image to 3.1 but now I'm forced to install sdk 2.1 because dotnet lambda package -f netcoreapp2.1 tries to build and fails :(

Thanks!

**Comment by ashishdhingra** [comment]
Hi @JonCubed,

Good afternoon. 

I was going through the backlog and came across this issue. The .NET Lambda tools support the switch `--msbuild-parameters` which you could use to pass additional MSBuild parameters. For your scenario, the command `dotnet lambda package --msbuild-parameters "--no-build"` works. Please confirm this at your end and confirm if this issue could be closed.

Thanks,
Ashish
