### ISSUE TITLE
dotnet lambda deploy-serverless produces "Device not configured" on mac

### ISSUE THREAD

**Issue by fafner** [aws/aws-extensions-for-dotnet-cli#65]
Whenever I try to run 'dotnet lambda deploy-serverless' on a project created from the 'serverless.AspNetCoreWebAPI' template, I first get asked for the stack and S3 bucket names, and after entering the bucket name, I get a message saying

> Warning: Unable to determine region for bucket ******, assuming bucket is in correct region: Device not configured

After this, the project is built and packaged, but the upload to S3 fails with pretty much the same message:

> Error uploading to ******.zip in bucket ******: Device not configured

I've also tried this with a completely new unchanged project from the same template, with the same result. 

My IAM user has all permissions for S3, and I'm able to perform S3 operations like list and cp etc from the command line, so I don't think it's a permissions issue.

I'm using Amazon Lambda Tools for .NET Core applications (3.1.2) and macOS 10.14.4 beta.

**Comment by normj** [comment]
The "Device not configured" error implies you are having networking issues making any calls to AWS at least from this tool. Are you behind a proxy or anything?

**Comment by fafner** [comment]
Apparently my aws-lambda-tools-defaults.json had a typo in the "region" field. I was able to deploy after changing it.
