### ISSUE TITLE
Two steps deploy of a ECS service

### ISSUE THREAD

**Issue by Kralizek** [aws/aws-extensions-for-dotnet-cli#66]
Hi!

I'm trying to the dotnet ecs commands to build/push an image and deploy the service in two distinct steps.

I can successfully build the image by using 'dotnet ecs push-image' and I was planning to use 'dotnet ecs deploy-service' to deploy it without building the image again but I fail to see which parameters I should use to have the cli reuse a previously built image.

Thanks

**Comment by normj** [comment]
The ECS tools don't currently have that support. 

I would like to do some refactoring on this tool to instead having the huge list of switches for `deploy-service` have it allow you to provide a JSON document that defines the task definition. The containers in the task definition could point to either already published ecr repositories or local projects that should be built and published and then deployed with the task definition.

**Comment by Kralizek** [comment]
OTOH, the (huge) list of parameters is easier to handle in a ci/cd flow compared to a file

**Comment by thylux** [comment]
@Kralizek I started working with ECS Tools today and I see a -sip   | --skip-image-push parameter.
Looks like this feature is already implemented.

**Comment by ashishdhingra** [comment]
Hi @Kralizek,

Please review the last comment from @thylux. Kindly confirm if this is no longer an issue and if this could be closed.

Thanks,
Ashish

**Comment by Kralizek** [comment]
@ashishdhingra I'm not working with this anymore so I don't have any freshly updated knowledge about the situation
