### ISSUE TITLE
How do I specify the version label of the code I'm deploying with "dotnet eb deploy-environment"?

### ISSUE THREAD

**Issue by kalexii** [aws/aws-extensions-for-dotnet-cli#7]
There it is, in the issue name. Sorry for asking a question instead of reporting an issue, but I don't seem to be able to find the right CLI switch and I would like to be able to specify something that would help to trace the app version to an actual commit, or specify something more semantic.

Edit:

https://github.com/aws/aws-extensions-for-dotnet-cli/blob/9ba000390c21c781a65f432877c3f4016a6c566c/src/Amazon.ElasticBeanstalk.Tools/Commands/DeployEnvironmentCommand.cs#L107

As far as I understand, this is where it is configured. Is it possible to make it into a command?

**Comment by normj** [comment]
We don't have version label as a parameter but we should. I'll try and get that updated for you soon so you can optional specify a version label.

**Comment by normj** [comment]
Never mind, I see you sent PR. I'll take a look.

**Comment by normj** [comment]
Closing in favor of tracking this with the pull request https://github.com/aws/aws-extensions-for-dotnet-cli/pull/8
