### ISSUE TITLE
Version 3.2.0 fails for ASP.Net Core 2.1.6

### ISSUE THREAD

**Issue by starkcolin** [aws/aws-extensions-for-dotnet-cli#71]
Using dotnet lambda package-ci (or package) for a project using ASP.Net Core version 2.1.6 fails using version 3.2.0.
This was not the case with previous versions.
As per https://github.com/aws/aws-lambda-dotnet 2.1.6 should be supported.

**Comment by normj** [comment]
I just updated the config file that has the version to check for to include 2.1.6. It should be back to working in a few minutes as the CloudFront invalidation completes.

**Comment by starkcolin** [comment]
Appears to be fixed now. Thanks
