### ISSUE TITLE
Nested CloudFormation stacks deployment with deploy-serverless

### ISSUE THREAD

**Issue by TizianoCoroneo** [aws/aws-extensions-for-dotnet-cli#72]
I'm trying to split up my 1000+ LOC CloudFormation template into multiple smaller templates, but I can't figure out how to tell the `dotnet lambda deploy-serverless` command to:
first package my nested templates and upload to S3 (since the `AWS::CloudFormation::Stack` resource requires `TemplateURL` to be a S3 url);
inject the returned S3 URL into the main template and deploy the resulting template.

I've found online some ways to do this using the `aws cloudformation package` CLI command, but I would prefer a more straightforward way to achieve this, maybe adding an extra argument to `deploy-serverless`.

**Comment by klaytaybai** [comment]
Hi @TizianoCoroneo, thanks for your feedback on this.  I think it will have to be a new feature for our .NET CLI extensions.  In the meantime, consider using the AWS CLI to package your nested templates.  

Can you please clarify what you might want an extra argument to deploy-serverless to do?

This would also seem to better resolve https://github.com/aws/aws-extensions-for-dotnet-cli/issues/50

**Comment by hunanniu** [comment]
Recommend to use CDK to achieve this
