### ISSUE TITLE
 dotnet lambda publish-layer error (Unknown error executing command: The filename or extension is too long)

### ISSUE THREAD

**Issue by sjaramillo-cr** [aws/aws-extensions-for-dotnet-cli#73]
Hello everyone, im getting this error while trying to publish a layer in the latest tooling (as of 20190329), any ideas?

PS C:\masked\Shared.Framework> dotnet lambda publish-layer --layer-name tb-framework --pl .\Shared.Framework.csproj --layer-type runtime-package-store --framework netcoreapp2.1 --s3-bucket masked-bucket --region sa-east-1
Amazon Lambda Tools for .NET Core applications (3.2.0)
Project Home: https://github.com/aws/aws-extensions-for-dotnet-cli, https://github.com/aws/aws-lambda-dotnet

... invoking 'dotnet store' for manifest C:\masked\Shared.Framework.csproj into output directory C:\masked\AppData\Local\Temp\tb-framework-636894804424153463\dotnetcore/store
... store: Microsoft (R) Build Engine version 16.0.450+ga8dc7f1d34 for .NET Core
... store: Copyright (C) Microsoft Corporation. All rights reserved.
... store:   Restore completed in 382.67 ms for C:\masked\Shared.Framework.csproj.
... store:   Restore completed in 417.87 ms for C:\masked\Shared.Framework.csproj.
... store:   Restore completed in 456.12 ms for C:\masked\Shared.Framework.csproj.
... store:   Restore completed in 352.88 ms for C:\masked\Shared.Framework.csproj.
... store:   Restore completed in 884.95 ms for C:\masked\Shared.Framework.csproj.
... store:   Restore completed in 299.23 ms for C:\masked\Shared.Framework.csproj.
... store:   Restore completed in 569.19 ms for C:\masked\Shared.Framework.csproj.
... store:   Restore completed in 1.49 sec for C:\masked\Shared.Framework.csproj.
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018: The "FilterResolvedFiles" task failed unexpectedly. [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object. [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018:    at Microsoft.NET.Build.Tasks.LockFileExtensions.GetTransitivePackagesList(LockFileTarget lockFileTarget, LockFileTargetLibrary package, IDictionary`2 libraryLookup) [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ProjectContext.GetTransitiveList(String package) [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018:    at Microsoft.NET.Build.Tasks.FilterResolvedFiles.ExecuteCore() [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018: The "FilterResolvedFiles" task failed unexpectedly. [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object. [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018:    at Microsoft.NET.Build.Tasks.LockFileExtensions.GetTransitivePackagesList(LockFileTarget lockFileTarget, LockFileTargetLibrary package, IDictionary`2 libraryLookup) [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ProjectContext.GetTransitiveList(String package) [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018:    at Microsoft.NET.Build.Tasks.FilterResolvedFiles.ExecuteCore() [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018: The "FilterResolvedFiles" task failed unexpectedly. [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object. [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018:    at Microsoft.NET.Build.Tasks.LockFileExtensions.GetTransitivePackagesList(LockFileTarget lockFileTarget, LockFileTargetLibrary package, IDictionary`2 libraryLookup) [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ProjectContext.GetTransitiveList(String package) [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018:    at Microsoft.NET.Build.Tasks.FilterResolvedFiles.ExecuteCore() [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018: The "FilterResolvedFiles" task failed unexpectedly. [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object. [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018:    at Microsoft.NET.Build.Tasks.LockFileExtensions.GetTransitivePackagesList(LockFileTarget lockFileTarget, LockFileTargetLibrary package, IDictionary`2 libraryLookup) [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ProjectContext.GetTransitiveList(String package) [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018:    at Microsoft.NET.Build.Tasks.FilterResolvedFiles.ExecuteCore() [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018: The "FilterResolvedFiles" task failed unexpectedly. [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object. [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018:    at Microsoft.NET.Build.Tasks.LockFileExtensions.GetTransitivePackagesList(LockFileTarget lockFileTarget, LockFileTargetLibrary package, IDictionary`2 libraryLookup) [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ProjectContext.GetTransitiveList(String package) [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018:    at Microsoft.NET.Build.Tasks.FilterResolvedFiles.ExecuteCore() [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018: The "FilterResolvedFiles" task failed unexpectedly. [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object. [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018:    at Microsoft.NET.Build.Tasks.LockFileExtensions.GetTransitivePackagesList(LockFileTarget lockFileTarget, LockFileTargetLibrary package, IDictionary`2 libraryLookup) [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ProjectContext.GetTransitiveList(String package) [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018:    at Microsoft.NET.Build.Tasks.FilterResolvedFiles.ExecuteCore() [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018: The "FilterResolvedFiles" task failed unexpectedly. [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object. [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018:    at Microsoft.NET.Build.Tasks.LockFileExtensions.GetTransitivePackagesList(LockFileTarget lockFileTarget, LockFileTargetLibrary package, IDictionary`2 libraryLookup) [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ProjectContext.GetTransitiveList(String package) [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018:    at Microsoft.NET.Build.Tasks.FilterResolvedFiles.ExecuteCore() [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [C:\masked\Shared.Framework.csproj]
... store: C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [C:\masked\Shared.Framework.csproj]
... store:   Files were composed in C:\masked\AppData\Local\Temp\tb-framework-636894804424153463\dotnetcore\store\x64\netcoreapp2.1\
... store:   The list of packages stored is in C:\masked\AppData\Local\Temp\tb-framework-636894804424153463\dotnetcore\store\x64\netcoreapp2.1\artifact.xml
Uploading runtime package store manifest to S3
Uploading to S3. (Bucket: masked-bucket Key: tb-framework-636894804424007602/artifact.xml)
... Progress: 100%
Upload complete to s3://masked-bucket/tb-framework-636894804424007602/artifact.xml
Create zip file of runtime package store directory
Unknown error executing command: The filename or extension is too long
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Amazon.Lambda.Tools.LambdaPackager.BundleWithBuildLambdaZip(String zipArchivePath, String rootDirectory, IDictionary`2 includedFiles, IToolLogger logger) in E:\JenkinsWorkspaces\aws-extensions-for-dotnet-cli\src\Amazon.Lambda.Tools\LambdaPackager.cs:line 548
   at Amazon.Lambda.Tools.LambdaPackager.BundleDirectory(String zipArchivePath, String sourceDirectory, Boolean flattenRuntime, IToolLogger logger) in E:\JenkinsWorkspaces\aws-extensions-for-dotnet-cli\src\Amazon.Lambda.Tools\LambdaPackager.cs:line 153
   at Amazon.Lambda.Tools.Commands.PublishLayerCommand.CreateRuntimePackageStoreLayerZipFile(String layerName, String s3Prefix) in E:\JenkinsWorkspaces\aws-extensions-for-dotnet-cli\src\Amazon.Lambda.Tools\Commands\PublishLayerCommand.cs:line 254
   at Amazon.Lambda.Tools.Commands.PublishLayerCommand.PerformActionAsync() in E:\JenkinsWorkspaces\aws-extensions-for-dotnet-cli\src\Amazon.Lambda.Tools\Commands\PublishLayerCommand.cs:line 111
   at Amazon.Common.DotNetCli.Tools.Commands.BaseCommand`1.ExecuteAsync() in E:\JenkinsWorkspaces\aws-extensions-for-dotnet-cli\src\Amazon.Common.DotNetCli.Tools\Commands\BaseCommand.cs:line 44

**Comment by normj** [comment]
Could you share your Shared.Framework.csproj file?

**Comment by lester-s** [comment]
Hello I am also experiencing an error quite similar to this one. When trying to publish a .net core serverless app in AWS using the Amazon.Lambda.Tools.

Zipping publish folder C:\GitlabRepo\Margot\.\GOTWeb_Customer\bin\Release\netcoreapp2.1\publish to C:\GitlabRepo\Margot\testPackage Unknown error executing command: Nom de fichier ou extension trop long at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo) at System.Diagnostics.Process.Start() at Amazon.Lambda.Tools.LambdaPackager.BundleWithBuildLambdaZip(String zipArchivePath, String rootDirectory, IDictionary2 includedFiles, IToolLogger logger) in E:\JenkinsWorkspaces\aws-extensions-for-dotnet-cli\src\Amazon.Lambda.Tools\LambdaPackager.cs:line 548
at Amazon.Lambda.Tools.LambdaPackager.BundleDirectory(String zipArchivePath, String sourceDirectory, Boolean flattenRuntime, IToolLogger logger) in E:\JenkinsWorkspaces\aws-extensions-for-dotnet-cli\src\Amazon.Lambda.Tools\LambdaPackager.cs:line 153
at Amazon.Lambda.Tools.LambdaPackager.CreateApplicationBundle(LambdaToolsDefaults defaults, IToolLogger logger, String workingDirectory, String projectLocation, String configuration, String targetFramework, String msbuildParameters, Boolean disableVersionCheck, LayerPackageInfo layerPackageInfo, String& publishLocation, String& zipArchivePath) in E:\JenkinsWorkspaces\aws-extensions-for-dotnet-cli\src\Amazon.Lambda.Tools\LambdaPackager.cs:line 133
at Amazon.Lambda.Tools.Commands.PackageCommand.PerformActionAsync()
at Amazon.Common.DotNetCli.Tools.Commands.BaseCommand1.ExecuteAsync() in E:\JenkinsWorkspaces\aws-extensions-for-dotnet-cli\src\Amazon.Common.DotNetCli.Tools\Commands\BaseCommand.cs:line 44

If you have any ways to fix this.

Thank you.

**Comment by cookiekitty** [comment]
I am also having the exact same issue with attempting to publish a .NET Core Serverless app in AWS with the "Unknown error executing command: The filename or extension is too long" message. This app was deployed as .NET Core 2.0 in the exact same file structure with no issues, previously. The only thing that has been changed is upgrading it to .NET Core 2.1 and the new AWS Tools so that we could deploy from within Visual Studio.

**Comment by boblodgett** [comment]
For Windows:
	-What version of Windows are you using?
	-Do you know if you have long path names enabled or disabled?

Are you building through Visual Studio or building your project from the command line?

Are you publishing through Visual Studio or the command line?

Are you able to share your .csproj file?

**Comment by cookiekitty** [comment]
Windows 10 Pro version 1803
I do not think I have long path names enabled.
I am building through Visual Studio.
I am publishing through the Visual Studio AWS menu. (right click on the project -> publish to AWS).

`<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>

    <AWSProjectType>Lambda</AWSProjectType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.Core" Version="1.1.0" />
    <PackageReference Include="Amazon.Lambda.DynamoDBEvents" Version="1.1.0" />
    <PackageReference Include="Amazon.Lambda.Serialization.Json" Version="1.5.0" />
    <PackageReference Include="Amazon.Lambda.APIGatewayEvents" Version="1.2.0" />
    <PackageReference Include="AWSSDK.Core" Version="3.3.100.5" />
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="3.3.100.5" />
    <PackageReference Include="AWSSDK.Lambda" Version="3.3.100.5" />
    <PackageReference Include="kafka-sharp" Version="1.3.0" />
    <PackageReference Include="Microsoft.TypeScript.Compiler" Version="3.1.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AwsLambdaUtilities\AwsLambdaUtilities.csproj" />
    <ProjectReference Include="..\ServerlessLogic\MyApplicationLogic.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="node_modules\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Update="api.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="AuthKey_8VGHXTGR4J.p8">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
`

**Comment by boblodgett** [comment]
I have a potential fix for this issue in this PR: https://github.com/aws/aws-extensions-for-dotnet-cli/pull/77

**Comment by cookiekitty** [comment]
When can we expect v3.2.3 of the Amazon.Lambda.Tools to release? I'm in a production bind and cannot publish until this is fixed!

**Comment by boblodgett** [comment]
v3.2.3 of Amazon.Lambda.Tools has been released to publish from the cli. The release of the Amazon Toolkit for Visual Studio to incorporate the Amazon.Lambda.Tools change is pending.

**Comment by cookiekitty** [comment]
v3.2.3 has not fixed the issue, I'm still unable to publish if my node_modules folder is part of my serverless project. I still get the same error about the filename or extension is too long.

If I remove node_modules from my project, I am able to publish but it breaks my JS lambdas without it present.

Was the fix not actually put into 3.2.3?? I'm getting desperate here.

**Comment by normj** [comment]
Yes, as @boblodgett we have not shipped an updated version of the toolkit with the fix. We hope to do that soon. There are a couple other CR being finished up and then we can release it.

**Comment by lester-s** [comment]
I came with a work around that is working for me. i am using terraform to recreate the steps of the publish operation. But i think you can do something quite similar with the aws CLI by:
-dotnet lambda package -pl <csproj location folder> -o <zip package location>
-aws s3 cp <zip package location <s3 uri of the package>
- set the app lambda as using a s3 for the source code instead of zip and pointing to the new package you uploaded.

**Comment by szmulder** [comment]
I have the same problem with 3.2.2 and upgrade to 3.2.3 fixed it.

**Comment by normj** [comment]
I just published version 1.15.2.0 of the AWS Toolkit for Visual Studio that contains the fix that was previously released with the command line tools.
