### ISSUE TITLE
Nuget Package Version 3.2.1 Broken

### ISSUE THREAD

**Issue by WillCallahan** [aws/aws-extensions-for-dotnet-cli#76]
## Issue

The latest version of Amazon.Lambda.Tools (3.2.1), [available from Nuget](https://www.nuget.org/packages/Amazon.Lambda.Tools), cannot be installed because the package is missing the `DotnetToolSettings.xml` file.

## Replication

```bash
$ dotnet tool install --global --version 3.2.1 Amazon.Lambda.Tools

Tool 'amazon.lambda.tools' failed to update due to the following:
The settings file in the tool's NuGet package is invalid: Settings file 'DotnetToolSettings.xml' was not found in the package.
Tool 'amazon.lambda.tools' failed to install. Please contact the tool author for assistance.
```

**Comment by tofalck** [comment]
@WillCallahan, @normj - I can confirm this issue as it also broke our Codepipeline build. We are cherry picking 3.2.0 until the issue is resolved.

![image](https://user-images.githubusercontent.com/2613099/56427160-18715e00-62bb-11e9-850b-ed0ab67100eb.png)

**Comment by psbmiller** [comment]
I am having this issue as well:
![image](https://user-images.githubusercontent.com/40210690/56430529-383d5d80-628c-11e9-8be3-3f18d83552cc.png)

**Comment by normj** [comment]
I have reproduced the problem on OSX but not Windows and I'm investigating the issue. Can others let me know what platform they are installing/updating the tool on?

**Comment by psbmiller** [comment]
@normj I'm running mine in CodeBuild

![image](https://user-images.githubusercontent.com/40210690/56430995-f2819480-628d-11e9-8f7c-4fc2c32e6b98.png)

**Comment by KseniiaPelykh** [comment]
Hi @normj 

we are working with microsoft/dotnet:2.1-sdk docker image
![image](https://user-images.githubusercontent.com/4716985/56431589-8b360580-62ca-11e9-8b57-d66db1e6d662.png)

**Comment by normj** [comment]
Thanks for letting me know the OS. Sorry for this happening and know this is my top issue to get this fixed as fast possible.

**Comment by KseniiaPelykh** [comment]
We're using 3.2.0 version at the moment, so no problem @normj . Thank you for helping!

**Comment by tofalck** [comment]
Codebuild default settings too.

No worries Norm - stuff happens 😊👍

**Comment by normj** [comment]
Version 3.2.2 is out which fixes the problem. I apologize again for this happening.

For those that are curious we have been refreshing our build infrastructure and this was the first release to happen from Linux which triggered a file permission issue with the files that got added to the NuGet package. We will be adding more validations in our release process to ensure this doesn't happen again. I appreciate all of your support/feedback for these tools.

**Comment by tofalck** [comment]
Thanks for a quick fix 👍😊

**Comment by WillCallahan** [comment]
This is working for me on Max OSX 10.14 and Alpine Linux 3.7.3.

Thanks!!!

**Comment by moedeveloper** [comment]
I am still getting this error using the Ubuntu bash on windows.  I am trying to install version 3.3.1
