### ISSUE TITLE
No executable found matching command "dotnet-lambda"

### ISSUE THREAD

**Issue by ebol2000** [aws/aws-extensions-for-dotnet-cli#82]
I'm not sure the exact cause of this issue but let me describe what I'm seeing in case others are running into this issue. First off, I'm trying to use this extension on my "build machine" which in this case happens to be a Jenkins Slave, a Windows Server 2016 standard. 

When I run the command locally, and directly in the Cmd window...
   `dotnet lambda deploy-function --profile sandbox`
... everything works perfectly. However, when I run this same command from my Jenkins (which generates and deploys the script as a .bat file) I get the error 
`No executable found matching command "dotnet-lambda`

Some facts

- I'm logged on as the same user as the Jenkins Windows service
- I've already installed the tools (obviously)
- I'm located in the same directory as the .csproj file ... this error happens with `donet lambda help` BTW

**Work Around**
While reading through a very similar issue (https://github.com/ElectronNET/Electron.NET/issues/189) I learned that the actual exe lives at `c:\users\{username}\.dotnet\tools\dotnet-lambda.exe`. Therefore I was able to work around this by manually calling the exe like 

`"%USERPROFILE%\.dotnet\tools\dotnet-lambda.exe" deploy-function --profile %AwsProfileName%`

As I mentioned, I'm not sure this is actually an issue with this project or somehow related to the way Jenkins is running the bat file, etc.

**Comment by normj** [comment]
Yeah, as much as I like .NET Core Global Tools this is a weakness with the the tool chain that the directory where global tools is installed is not added to the PATH until the first tool is installed with the `dotnet tool install -g` command. 

There isn't anything we can do about this and we have had to do similar workaround in our tooling when we are unsure if the dotnet tools directory will be in the path.

**Comment by ebol2000** [comment]
Actually I did run the command `dotnet tool install --global Amazon.Lambda.Tools` just before this call and it responded that it was already installed. So in this case the extension exe is just not resolving for some reason. This is why when I call the extension exe directly it works fine.

**Comment by normj** [comment]
When you call `dotnet tool install --global Amazon.Lambda.Tools` or some other global tool it ensure the dotnet tools folder is part of the PATH but in your case Jenkins would need to be restarted to pick up the change to the environment variable.

**Comment by ebol2000** [comment]
Ah, of course! Perfect, that worked now with the `dotnet lambda` command. Thanks!

**Comment by thinkOfaNumber** [comment]
I know this is closed, but you can install the tool locally. This is better for build servers, IMHO, as part of the build chain should include `nuget install` and `dotnet tool restore`, so you get all build requirements as they are added and tested in your local repository, and it reduces the number of "do this first" steps to get a new build server running.

then instead of `dotnet lambda deploy-function ...`, you would run: `dotnet tool run dotnet-lambda ...`
