### ISSUE TITLE
Package v3.2.3 Produces Errors During Install

### ISSUE THREAD

**Issue by meowcatmcmeow** [aws/aws-extensions-for-dotnet-cli#84]
While trying to prepare my existing ASP.NET web API for use as a Lambda Function, I needed to install the Amazon.Lambda.Tools package [as described here](https://aws.amazon.com/blogs/developer/deploy-an-existing-asp-net-core-web-api-to-aws-lambda/). However, when installing the NuGet package, it fails and gives the following error messages:

`
Package 'Amazon.Lambda.Tools 3.2.3' has a package type 'DotnetTool' that is not supported by project 'WebApi'
`
`
NU1212: Invalid project-package combination for Amazon.Lambda.Tools 3.2.3. DotnetToolReference project style can only contain references of the DotnetTool type
`
`
NU1202: Package Amazon.Lambda.Tools 3.2.3 is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1). Package Amazon.Lambda.Tools 3.2.3 supports: netcoreapp2.1 (.NETCoreApp,Version=v2.1) / any
`

I checked multiple times that the target framework for the project was set to .NET Core 2.1, and that there were no package conflicts. After running over everything with a fine-toothed comb, I could not find any conceivable problems that could cause these errors. Any help or advice would be very much appreciated.

Technical details:
- IDE: Visual Studio 2019 Community Edition
- Operating System: Windows 10 Home Edition (x86_64)
- Project Type: ASP.NET Web API (.NET Core v2.1)

**Comment by klaytaybai** [comment]
Hi @meowcatmcmeow, sorry for the confusion.  It looks like we should probably edit or remove that documentation you referenced.  It seems to be largely deprecated.  For the updated guide on how to set up ASP.NET projects for use with Lambda, please see the [README](https://github.com/aws/aws-extensions-for-dotnet-cli) in this repo.

**Comment by meowcatmcmeow** [comment]
@klaytaybai, thank you for the advice. I've started following the steps there and everything seems to be working quite well.
