### ISSUE TITLE
No executable found matching command "dotnet-lambda" on TRAVIS CI

### ISSUE THREAD

**Issue by seannguyn** [aws/aws-extensions-for-dotnet-cli#88]
So I use Travis CI and dotnet lambda, and below one of the stage:

      script:
        - echo "Deploy to AWS"
        - dotnet tool install --global Amazon.Lambda.Tools
        - dotnet tool update --global Amazon.Lambda.Tools
        - dotnet-lambda package --configuration release --framework netcoreapp2.1 --output-package bin/release/netcoreapp2.1/deploy-package.zip

When the dotnet lambda is run:

the Error is: No executable found matching command "dotnet-lambda"

As you can see, I have installed Amazon.Lambda.Tools in the line before dotnet lambda

So I am not sure what the issue is

**Comment by normj** [comment]
An awkward aspect of .NET Core Global tools is the directory `~/.dotnet/tools` must be part of the path in order for the tool to be found. Normally on a dev machine this was taken care you by the dotnet CLI when install your first tool and restart your shell.

In a CI system like travis the `~/.dotnet/tools` folder might not have a been added to the current shell that is running your build script.

I would suggest either manually adding `~/.dotnet/tools` to your path as part of your travis build script or directly run the command `~/.dotnet/tools/dotnet-lambda` in your build script to avoid the path issue.

**Comment by seannguyn** [comment]
Thank you very much. Explicitly specifying: **~/.dotnet/tools/dotnet-lambda** works
