### ISSUE TITLE
Can I add a new dependency using dotnet layers?

### ISSUE THREAD

**Issue by hasanfd** [aws/aws-extensions-for-dotnet-cli#91]
Can I add a new dependency to the project, that does not exist in the original .csproj file, by using dotnet layers?

Thanks

**Comment by hasanfd** [comment]
As far as I understand, dotnet layers only support runtime package store feature right now and as stated [here](https://github.com/dotnet/designs/issues/8)  runtime package stores is for:
* Smaller deployments
* Lower disk space usage
* Faster startup times
They don't provide dynamic .dll load or binding. So, I am closing my issue.

**Comment by normj** [comment]
Just to confirm our .NET tooling only supports Runtime Package store for assemblies to be automatically loaded. In theory if you wanted to use dynamic loading of dlls using Assembly.LoadX you could just use the basic Lambda feature which would dump the dlls in a folder of your choosing under /opt. I find .NET Core dynamic dll binding pretty tricky so I would be careful going down that path.
