### ISSUE TITLE
Request: break build if --function-layers is specified, but unable to retrieve information

### ISSUE THREAD

**Issue by TommyN** [aws/aws-extensions-for-dotnet-cli#95]
Is there a way to get
```
dotnet lambda package --function-layers <layer>
```
to fail instead of skipping and building without the layer?

This is what I see in my build log:
```
arn:aws:lambda:eu-west-1:xyz:layer:MyNewLayer:1: Skipped, error inspecting layer. Access Denied
```

**Comment by klaytaybai** [comment]
Thanks for the feedback on this.  Would you prefer to see it break immediately or after all layers have been tried so you can see the logs of each?

**Comment by TommyN** [comment]
I only have a single layer at the moment, so for me it would be ok to break immediately
