### ISSUE TITLE
Amazon.Lambda.Tools does not seem to support Microsoft.NETCore.App 3.0 

### ISSUE THREAD

**Issue by l1x** [aws/aws-extensions-for-dotnet-cli#96]
I get the following error when building with netcoreapp3.0:

```
dotnet lambda package --configuration release --framework netcoreapp3.0 --output-package bin/release/netcoreapp3.0/deploy-package.zip
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      3.0.1 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The .NET Core frameworks can be found at:
  - https://aka.ms/dotnet-download
```

Is this expected?

**Comment by klaytaybai** [comment]
Hi @l1x.  I don't think this error is expected.  Reading https://github.com/dotnet/core/issues/3487# might help you out.

You can read more about working with .NET Core 3.0 in Lambda [here](https://aws.amazon.com/blogs/developer/net-core-3-0-on-lambda-with-aws-lambdas-custom-runtime/).

**Comment by l1x** [comment]
Thanks. I think 3.1 is a LTS and it is going to be supported as a runtime. I am going to wait for that.

**Comment by scionwest** [comment]
Hi @l1x - I have a repository that you can use as reference for deploying a .Dotnet Core 3.0 Runtime into Lambda using the AWS extensions for the Dotnet CLI.

The repository [is here](https://github.com/scionwest/convey-serverless-lambda). There is a file called [Program.cs](https://github.com/scionwest/convey-serverless-lambda/blob/master/ConveyApi/Program.cs) where I [instantiate an instance of Lambda entry class](https://github.com/scionwest/convey-serverless-lambda/blob/master/ConveyApi/Program.cs#L27). My Lambda entry is wrapped by an Amazon `HandlerWrapper` and `LambdaBootstrap` instance. You just need to add the [Amazon.Lambda.RuntimeSupport](https://github.com/scionwest/convey-serverless-lambda/blob/master/ConveyApi/ConveyApi.csproj#L16) NuGet package.

The repository can be cloned and ran as-is. You can deploy the Dotnet Core 3.0 runtime into your AWS environment, the Readme includes instructions to do so via the Lambda Dotnet CLI extension.
