### ISSUE TITLE
Re-package a lambda

### ISSUE THREAD

**Issue by phillip-haydon** [aws/aws-extensions-for-dotnet-cli#98]
I have a lambda package that was created using `dotnet lambda package ....`, however during the deployment I need to unzip the archive, modify the variables, then re-zip it and upload it to S3.

On Windows I cannot use `create-archive` or `7zip` as it modifies the permissions. You've already resolved this issue so I'm wondering if there is a way or you can expose a way to just re-zip the directory. 

This is to get around the issue of:

> Runtime failed to start: fork/exec /var/task/bootstrap: permission denied <nil>

**Comment by normj** [comment]
The permissioning is a pain. I suspect I won't have time to get to this feature request but I'm open to a PR for the feature. I initial thought is there would be a new `--no-build` switch similar to `dotnet publish` command. The tricky part is how do we determine which folder should be zipped. I could see somebody else wanting to use this feature and they have already triggered a build in the project folder and then just want the tool to zip up the previous build. So there could be use case for both current logic of using the `dotnet publish` location or using the current location like your use case. Maybe if the current location or `--project-location` contain a project file use the normal logic to determine the publish location. If it doesn't then assume the current directory or `--project-location` should be the start of what should be zipped.

**Comment by phillip-haydon** [comment]
@normj is there a way to zip the folder on Linux? I have a problem where using the zip tool from the lambda tools was working on Windows, but broke when there was sub-folders. So I changed to build on Linux. But I still get the same runtime fail error on Linux.

**Comment by normj** [comment]
Do you mean can you zip a folder on Linux with the golang program we embedded into Lambda tools? If so no. We only use that tool on Windows. The Lambda tools detect which platform it is running on and if it is Windows use the special embedded golang tool. Otherwise use the `zip` command line tool when on non-windows platforms.

Did I understand the question correctly?

**Comment by phillip-haydon** [comment]
Haha sort of.

So I’m moving the build from windows to linux. And the deploy from windows to linux.

When I deploy, I need to unzip. Update some configuration. Zip it up. And deploy.

I can’t figure out how to zip on linux preserving the permissions. So I’m wondering if you can tell me how to zip.

**Comment by augustoproiete** [comment]
these bots are ... Not useful
